// plugins/native-ui/src/ui/components/textarea/index.tsx
import { type FieldState, field } from "@fcalell/ui-core/variants";
import { TextInput, type TextInputProps } from "react-native";
import { cn } from "../../lib/cn";
import { useFieldState } from "../../lib/field";

// A multi-line surface outgrows the field's control floor and needs its own
// vertical interior, so both ride the overlay as literal numerics.
const BOX = "min-h-20 w-full py-2 text-callout text-ink-1";

export interface TextareaProps extends TextInputProps {
	// Same state contract as Input: `error` pins the danger border,
	// `useFieldState` moves the default onto the `focused` cell.
	state?: FieldState;
}

export function Textarea({
	state,
	className,
	onFocus,
	onBlur,
	...rest
}: TextareaProps) {
	const tracked = useFieldState(state, onFocus, onBlur);
	return (
		<TextInput
			multiline
			textAlignVertical="top"
			className={cn(
				field({ state: tracked.state, layout: "input" }),
				BOX,
				className,
			)}
			placeholderTextColorClassName="text-ink-3"
			onFocus={tracked.onFocus}
			onBlur={tracked.onBlur}
			{...rest}
		/>
	);
}

// plugins/solid-ui/src/ui/components/textarea/index.tsx
import { field } from "@fcalell/ui-core/variants";
import type { ComponentProps } from "solid-js";
import { mergeProps, splitProps } from "solid-js";
import { cn } from "#lib/cn";
import { fieldMutedClass, fieldShellClass } from "#lib/field";

// A multi-line surface outgrows the field's control floor and needs its own
// vertical interior, so both ride the overlay as literal numerics.
const BOX =
	"flex min-h-16 max-h-64 w-full min-w-0 resize-none overflow-y-auto py-2 field-sizing-content";

type TextareaProps = ComponentProps<"textarea">;

function Textarea(props: TextareaProps) {
	const merged = mergeProps({ rows: 3 as const }, props);
	const [local, rest] = splitProps(merged, ["class"]);
	return (
		<textarea
			class={cn(
				field({ state: "default", layout: "input" }),
				fieldShellClass,
				BOX,
				merged.disabled && fieldMutedClass,
				local.class,
			)}
			{...rest}
		/>
	);
}

export type { TextareaProps };
export { Textarea };
