// plugins/native-ui/src/ui/components/status/index.tsx
import type { StatusState } from "@fcalell/ui-core/descriptors";
import {
	STATUS_CHIP,
	status,
	statusContentTone,
} from "@fcalell/ui-core/variants";
import {
	Circle,
	CircleAlert,
	CircleCheck,
	CircleDot,
	CircleX,
	Clock,
	type LucideIcon,
} from "lucide-react-native";
import { Pressable, Text as RNText, View } from "react-native";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { Glyph } from "../../lib/glyph";
import { useWords } from "../../lib/words";

export interface StatusProps extends Closed {
	state: StatusState;
	label?: string;
	onOpen?: () => void;
}

export const STATUS_MARK: Record<StatusState, LucideIcon> = {
	active: CircleDot,
	waiting: Clock,
	done: CircleCheck,
	attention: CircleAlert,
	failed: CircleX,
	idle: Circle,
};

// An icon and a word; the color follows the state. With `onOpen` it is a chip.
export function Status({ state, label, onOpen }: StatusProps) {
	const words = useWords();
	const word = label ?? words[state];
	const inner = (
		<>
			<Glyph
				icon={STATUS_MARK[state]}
				tone={statusContentTone(state)}
				size={16}
			/>
			<RNText className={status({ state })}>{word}</RNText>
		</>
	);
	if (onOpen) {
		return (
			<Pressable
				accessibilityRole="button"
				accessibilityLabel={word}
				onPress={onOpen}
				className={cn(
					STATUS_CHIP,
					"flex-row items-center gap-pair self-start active:bg-wash-press",
				)}
			>
				{inner}
			</Pressable>
		);
	}
	return <View className="flex-row items-center gap-pair">{inner}</View>;
}

// plugins/solid-ui/src/ui/components/status/index.tsx
import type { StatusState } from "@fcalell/ui-core/tokens";
import { STATUS_CHIP, status } from "@fcalell/ui-core/variants";
import { Show } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { RING, WASH } from "#lib/interact.ts";
import { StatusGlyph } from "#lib/status-glyph.tsx";
import { useWords } from "#lib/words.tsx";

// An icon and a word; the consumer maps its own states onto the six and the
// color follows the state. With `onOpen` it is a 44 px chip.
export type StatusProps = Closed & {
	state: StatusState;
	label?: string;
	onOpen?: () => void;
};

export function Status(props: StatusProps) {
	const words = useWords();
	const word = () => props.label ?? words[props.state];
	const inner = () => (
		<>
			<StatusGlyph state={props.state} />
			<span>{word()}</span>
		</>
	);
	return (
		<Show
			when={props.onOpen}
			fallback={
				<span
					class={cn(status({ state: props.state }), "inline-flex items-center")}
				>
					{inner()}
				</span>
			}
		>
			<button
				type="button"
				onClick={() => props.onOpen?.()}
				class={cn(
					status({ state: props.state }),
					STATUS_CHIP,
					"inline-flex cursor-pointer items-center transition-colors duration-(--duration-fast) ease-ui",
					WASH,
					RING,
				)}
			>
				{inner()}
			</button>
		</Show>
	);
}
