// plugins/react-ui/src/ui/components/status/index.tsx
import { cn } from "@fcalell/ui-core/cn";
import type { StatusState } from "@fcalell/ui-core/tokens";
import { STATUS, STATUS_LABEL } from "@fcalell/ui-core/variants";
import type { Closed } from "../../lib/closed.ts";
import { useWords } from "../../lib/words.tsx";
import { StatusDot } from "./dot.tsx";

const BOX = "inline-flex items-center min-w-0";
const WORD = "truncate";

/** A work state: a dot in the state's colour beside its word. */
export interface StatusProps extends Closed {
	/** The state the dot's colour and the default word name. */
	state: StatusState;
	/** The word, when the state's own word does not say it. */
	label?: string;
}

/** A dot and a word, a mark: a status that moves is a `Picker` whose options carry states. */
export function Status({ state, label }: StatusProps) {
	const words = useWords();
	return (
		<span className={cn(STATUS, BOX)}>
			<StatusDot state={state} />
			<span className={cn(STATUS_LABEL, WORD)}>{label ?? words[state]}</span>
		</span>
	);
}

// plugins/solid-ui/src/ui/components/status/index.tsx
import type { StatusState } from "@fcalell/ui-core/tokens";
import { STATUS_CHIP, status } from "@fcalell/ui-core/variants";
import { Show } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { RING, WASH } from "#lib/interact.ts";
import { StatusGlyph } from "#lib/status-glyph.tsx";
import { useWords } from "#lib/words.tsx";

// An icon and a word; the consumer maps its own states onto the six and the
// color follows the state. With `onOpen` it is a 44 px chip.
export type StatusProps = Closed & {
	state: StatusState;
	label?: string;
	onOpen?: () => void;
};

export function Status(props: StatusProps) {
	const words = useWords();
	const word = () => props.label ?? words[props.state];
	const inner = () => (
		<>
			<StatusGlyph state={props.state} />
			<span>{word()}</span>
		</>
	);
	return (
		<Show
			when={props.onOpen}
			fallback={
				<span
					class={cn(status({ state: props.state }), "inline-flex items-center")}
				>
					{inner()}
				</span>
			}
		>
			<button
				type="button"
				onClick={() => props.onOpen?.()}
				class={cn(
					status({ state: props.state }),
					STATUS_CHIP,
					"inline-flex cursor-pointer items-center transition-colors duration-(--duration-fast) ease-ui",
					WASH,
					RING,
				)}
			>
				{inner()}
			</button>
		</Show>
	);
}
