// plugins/solid-ui/src/ui/components/shell/index.tsx
import type { PlaceSpec } from "@fcalell/ui-core/descriptors";
import { PLACE_ROW_SELECTED, place } from "@fcalell/ui-core/variants";
import { useLocation } from "@solidjs/router";
import { Ellipsis } from "lucide-solid";
import {
	createEffect,
	createMemo,
	createSignal,
	For,
	type JSX,
	onCleanup,
	onMount,
	Show,
} from "solid-js";
import { Dynamic } from "solid-js/web";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { FrameContext } from "#lib/frame.ts";
import { useIcon } from "#lib/icons.tsx";
import { RING, RING_INSET, WASH } from "#lib/interact.ts";
import { selectedRoute, tabsOf } from "#lib/places.ts";
import { placeToasts } from "#lib/toast.ts";
import { useWords } from "#lib/words.tsx";
import { Count } from "../count/index.tsx";
import { Sheet } from "../sheet/index.tsx";

// The frame at every width: the places as the system's tab bar under tablet
// and as the labelled sidebar from tablet, the app's banner under the top bar,
// the composed content, and where the toasts stand: the app root draws the
// queue and the `confirm()` decisions on every page, and the shell places the
// toasts over its column, above its tab bar and any pinned bar. A consumer
// with no places has no shell. `switcher` is what switches what the app is looking at (an
// organization, a project): the head of the sidebar from tablet and, under
// it, the start of each `Place`'s top bar, never a `Screen`'s. A `Screen` fixed over the column on the phone starts under the
// banner, so the app's state stays in sight, and the tab bar it covers goes
// inert; the toasts sit above a pinned bar. The tab bar's fill spans the
// screen and its tabs keep the column's side inset; it holds at most five
// tabs, so past five places the first four are tabs and the rest are rows of
// a sheet under a fifth, `more`, drawn selected while one of them is.
export type ShellProps = Closed & {
	places: PlaceSpec<string>[];
	banner?: JSX.Element;
	switcher?: JSX.Element;
	children?: JSX.Element;
};

function PlaceGlyph(props: { name: string; selected: boolean }) {
	return (
		<Dynamic
			component={useIcon(props.name)}
			class={cn(
				"size-6 shrink-0",
				place({ state: props.selected ? "selected" : "idle" }),
			)}
			aria-hidden="true"
		/>
	);
}

// A place in the sidebar, and under the phone's `more` tab.
function PlaceRow(props: {
	spec: PlaceSpec<string>;
	selected: boolean;
	onPick?: () => void;
}) {
	return (
		<a
			href={props.spec.route}
			aria-current={props.selected ? "page" : undefined}
			onClick={() => props.onPick?.()}
			class={cn(
				place({ state: props.selected ? "selected" : "idle" }),
				"flex min-h-floor items-center gap-row rounded-group px-stack",
				WASH,
				RING,
				props.selected && PLACE_ROW_SELECTED,
			)}
		>
			<PlaceGlyph name={props.spec.icon} selected={props.selected} />
			<span class="flex-1 text-body">{props.spec.label}</span>
			<Show when={props.spec.count}>
				{(count) => <Count value={count()} />}
			</Show>
		</a>
	);
}

const tab = (selected: boolean) =>
	cn(
		place({ state: selected ? "selected" : "idle" }),
		"relative flex min-h-11 min-w-0 flex-1 flex-col items-center justify-center gap-pair py-row",
		RING_INSET,
	);

export function Shell(props: ShellProps) {
	const words = useWords();
	const location = useLocation();
	const current = createMemo(() =>
		selectedRoute(
			props.places.map((s) => s.route),
			location.pathname,
		),
	);
	const selected = (spec: PlaceSpec<string>) => current() === spec.route;
	const tabs = createMemo(() => tabsOf(props.places));
	const moreSelected = () => tabs().more.some(selected);
	const [moreOpen, setMoreOpen] = createSignal(false);
	const [covers, setCovers] = createSignal(0);
	const [lift, setLift] = createSignal(0);
	const [bannerHeight, setBannerHeight] = createSignal(0);
	const covered = () => covers() > 0;
	let banner!: HTMLDivElement;
	onMount(() => {
		const observer = new ResizeObserver(() =>
			setBannerHeight(banner.offsetHeight),
		);
		observer.observe(banner);
		onCleanup(() => observer.disconnect());
	});
	// The toasts stand over the column, centred in it, above the tab bar the
	// column ends on and above a pinned bar's lift; a `Screen` covering the
	// column on the phone covers the tab bar too, so only the lift is left.
	let column!: HTMLDivElement;
	const [box, setBox] = createSignal({ left: 0, right: 0, below: 0 });
	onMount(() => {
		const measure = () => {
			const rect = column.getBoundingClientRect();
			setBox({
				left: rect.left,
				right: window.innerWidth - rect.right,
				below: window.innerHeight - rect.bottom,
			});
		};
		const observer = new ResizeObserver(measure);
		observer.observe(column);
		window.addEventListener("resize", measure);
		onCleanup(() => {
			observer.disconnect();
			window.removeEventListener("resize", measure);
			placeToasts(undefined);
		});
	});
	createEffect(() => {
		const { left, right, below } = box();
		placeToasts({
			left,
			right,
			bottom: (covered() ? 0 : below) + lift(),
		});
	});
	const frame = {
		cover: () => {
			setCovers((n) => n + 1);
			return () => setCovers((n) => n - 1);
		},
		lift: setLift,
		switcher: () => props.switcher,
	};
	return (
		<FrameContext.Provider value={frame}>
			<div
				class="flex h-dvh flex-col bg-canvas tablet:flex-row"
				style={{
					"--banner-height": `${bannerHeight()}px`,
				}}
			>
				{/* Plain anchors, whose clicks the router takes: its `A` sets
				    aria-current to its own exact match, which a place at a prefix
				    of the address is not, and adds a class of its own. */}
				<nav class="hidden w-rail shrink-0 flex-col gap-pair border-r p-stack tablet:flex">
					<Show when={props.switcher}>
						{(switcher) => <div class="pb-row">{switcher()}</div>}
					</Show>
					<For each={props.places}>
						{(spec) => <PlaceRow spec={spec} selected={selected(spec)} />}
					</For>
				</nav>
				{/* min-w-0: beside the rail the column takes the width left, never
			    its content's widest line. */}
				<div
					ref={column}
					class="relative flex min-h-0 min-w-0 flex-1 flex-col bg-surface"
				>
					<div ref={banner}>{props.banner}</div>
					<main class="flex min-h-0 flex-1 flex-col">{props.children}</main>
				</div>
				{/* The bar's fill spans the screen; its tabs keep the column's side
				    inset. */}
				<nav
					inert={covered() || undefined}
					class="flex border-t bg-canvas px-inset pb-[env(safe-area-inset-bottom)] tablet:hidden"
				>
					<For each={tabs().tabs}>
						{(spec) => (
							<a
								href={spec.route}
								aria-current={selected(spec) ? "page" : undefined}
								class={tab(selected(spec))}
							>
								<PlaceGlyph name={spec.icon} selected={selected(spec)} />
								<span>{spec.label}</span>
								<Show when={spec.count}>
									{(count) => (
										<span class="absolute top-pair right-1/4">
											<Count value={count()} />
										</span>
									)}
								</Show>
							</a>
						)}
					</For>
					<Show when={tabs().more.length > 0}>
						<button
							type="button"
							aria-haspopup="dialog"
							onClick={() => setMoreOpen(true)}
							class={cn(tab(moreSelected()), "cursor-pointer")}
						>
							<Ellipsis
								class={cn(
									"size-6 shrink-0",
									place({ state: moreSelected() ? "selected" : "idle" }),
								)}
								aria-hidden="true"
							/>
							<span>{words.more}</span>
						</button>
						<Sheet
							open={moreOpen()}
							onClose={() => setMoreOpen(false)}
							title={words.more}
						>
							<nav class="flex flex-col gap-pair">
								<For each={tabs().more}>
									{(spec) => (
										<PlaceRow
											spec={spec}
											selected={selected(spec)}
											onPick={() => setMoreOpen(false)}
										/>
									)}
								</For>
							</nav>
						</Sheet>
					</Show>
				</nav>
			</div>
		</FrameContext.Provider>
	);
}

// plugins/react-ui/src/ui/components/shell/index.tsx
import { Toast as ToastControl } from "@base-ui/react/toast";
import { cn } from "@fcalell/ui-core/cn";
import type {
	Option,
	OptionGroup,
	PlaceSpec,
	Switcher,
} from "@fcalell/ui-core/descriptors";
import {
	placeRow,
	placeRowGlyph,
	placeTab,
	placeTabLabel,
	SHELL_BANNER,
	SHELL_COLUMN,
	SHELL_PLACES,
	SHELL_SIDEBAR,
	SHELL_TAB_BAR,
	SWITCHER,
	SWITCHER_SLOT,
	TOASTS,
	text,
	textStrong,
} from "@fcalell/ui-core/variants";
import { type ReactNode, useState } from "react";
import type { Closed } from "../../lib/closed.ts";
import {
	ActFloats,
	CoverTabs,
	PlaceRoute,
	ShellSwitcher,
} from "../../lib/frame.ts";
import { useTouch } from "../../lib/media.ts";
import { isCurrent, usePathname } from "../../lib/navigate.ts";
import { toasts } from "../../lib/toast.ts";
import { useWords } from "../../lib/words.tsx";
import { Avatar } from "../avatar/index.tsx";
import { Count } from "../count/index.tsx";
import { Icon } from "../icon/index.tsx";
import { List } from "../list/index.tsx";
import { ListRow } from "../list-row/index.tsx";
import { PickerBase } from "../picker/base.tsx";
import { FloatingActRoom, Place } from "../place/index.tsx";
import { Confirmations } from "../sheet/confirm.tsx";
import { ToastList } from "../toast/layer.tsx";

// The shell fills the viewport; the page inside scrolls its own body.
const FRAME = "flex h-dvh overflow-hidden";
const SIDEBAR = "relative flex flex-col shrink-0";
const SLOT = "flex";
const PLACES = "flex flex-col";
const COLUMN = "relative flex flex-col min-w-0 grow";
const BANNER_SLOT = "flex flex-col";
// The page and the toasts standing over its foot: at the end on the
// desktop, centred on touch, above the tab bar and, while a Place's act
// floats, above the act. It is the main landmark, so a page's headers inside
// it are no banners.
const MAIN = "relative flex flex-col grow min-h-0";
const TOASTS_LAYER =
	"absolute inset-0 flex flex-col items-end justify-end pointer-events-none touch:items-center";
// A place row rings inset, inside the sidebar's inset.
const ROW_BOX = "flex items-center focus-visible:-outline-offset-2";
const ROW_PRESS = "hover:bg-wash-hover active:bg-wash-press";
const ROW_SELECTED_PRESS = "hover:bg-wash-selected-hover";
const GLYPH = "flex shrink-0";
const LABEL = "truncate grow";

const TRIGGER = "flex items-center w-full focus-visible:-outline-offset-2";
const TRIGGER_TOUCH = "flex items-center min-w-0";
const NAME = "truncate grow text-left";
const NAME_TOUCH = "truncate";

const TABS = "flex pb-safe";
const TAB =
	"flex flex-col-reverse items-center justify-center min-w-0 grow basis-0 focus-visible:-outline-offset-2";
const TAB_GLYPH = "relative flex";
const TAB_COUNT = "absolute top-0 left-full flex";
const TAB_LABEL = "max-w-full truncate";
// A tab bar holds five tabs at most: past five places, four and More.
const TAB_ROOM = 5;

/** The app's frame. */
export interface ShellProps extends Closed {
	/** The places, in order; the one at the current route is selected. */
	places: readonly PlaceSpec[];
	/** A `Banner` over the column, at the page inset. */
	banner?: ReactNode;
	/** What the app is looking at, and what it can switch to. */
	switcher?: Switcher;
	/** The current `Place` or `Screen`. */
	children?: ReactNode;
}

/** The frame: on the desktop the sidebar (the switcher, then the places) beside the column; on touch the column over the tab bar, the switcher at the head of each Place's top bar, and past five places four tabs and More, which opens a page of the rest; on both, the current place's route handed down for a Place's back act, a pushed Screen covering the tab bar, the `toast()` queue standing over the page's foot (at the end on the desktop, centred on touch over a floating act) and the first `confirm()` decision as a sheet. */
export function Shell({ places, banner, switcher, children }: ShellProps) {
	const touch = useTouch();
	const words = useWords();
	const pathname = usePathname();
	const [covered, cover] = useState(false);
	const [lifted, lift] = useState(false);
	// The More page stands at the route it opened on: going to a place closes it.
	const [moreAt, setMoreAt] = useState<string>();
	const more = moreAt === pathname;
	const trigger = switcher ? (
		<SwitcherPick switcher={switcher} touch={touch} />
	) : null;
	const route = places.find((spec) => isCurrent(spec.route, pathname))?.route;
	const rest = places.length > TAB_ROOM ? places.slice(TAB_ROOM - 1) : [];
	// The More page stands in the page's place while it is open on touch.
	const page = touch && more ? <MorePage places={rest} /> : children;
	// The sidebar and the tab bar differ by density; the column, and the page
	// in it, keep one tree position on both, so crossing the density line
	// keeps the page.
	const sidebar = touch ? null : (
		<nav aria-label={words.places} className={cn(SHELL_SIDEBAR, SIDEBAR)}>
			{trigger ? (
				<div className={cn(SWITCHER_SLOT, SLOT)}>{trigger}</div>
			) : null}
			<div className={cn(SHELL_PLACES, PLACES)}>
				{places.map((spec) => {
					const current = isCurrent(spec.route, pathname);
					const state = current ? "selected" : "rest";
					return (
						<a
							key={spec.route}
							href={spec.route}
							aria-current={current ? "page" : undefined}
							className={cn(
								placeRow({ state }),
								ROW_BOX,
								current ? ROW_SELECTED_PRESS : ROW_PRESS,
							)}
						>
							<span className={cn(placeRowGlyph({ state }), GLYPH)}>
								<Icon name={spec.icon} />
							</span>
							<span className={cn(text({ role: "body" }), LABEL)}>
								{spec.label}
							</span>
							{spec.count === undefined ? null : <Count value={spec.count} />}
						</a>
					);
				})}
			</div>
		</nav>
	);
	const tabs =
		touch && !covered ? (
			<TabBar
				places={places}
				pathname={pathname}
				more={more}
				onMore={() => setMoreAt(pathname)}
			/>
		) : null;
	// The toast queue and the confirm() decisions stand in every Shell.
	return (
		<ToastControl.Provider toastManager={toasts}>
			<div className={FRAME}>
				{sidebar}
				<div className={cn(SHELL_COLUMN, COLUMN)}>
					{banner ? (
						<div className={cn(SHELL_BANNER, BANNER_SLOT)}>{banner}</div>
					) : null}
					<main className={MAIN}>
						<ShellSwitcher value={trigger}>
							<PlaceRoute value={route}>
								<CoverTabs value={cover}>
									<ActFloats value={lift}>{page}</ActFloats>
								</CoverTabs>
							</PlaceRoute>
						</ShellSwitcher>
						<ToastControl.Viewport
							aria-label={words.notifications}
							className={cn(TOASTS, TOASTS_LAYER)}
						>
							<ToastList />
							{lifted ? <FloatingActRoom /> : null}
						</ToastControl.Viewport>
					</main>
					{tabs}
				</div>
			</div>
			<Confirmations />
		</ToastControl.Provider>
	);
}

function flatten(options: Switcher["options"]): readonly Option[] {
	const entries: readonly (Option | OptionGroup)[] = options;
	return entries.flatMap((entry) =>
		"options" in entry ? entry.options : [entry],
	);
}

// The switcher is a pick (its options with their avatars, the current one
// ticked, the act that makes a new one under a hairline), drawn as a place
// row in the sidebar and a compact trigger in a touch top bar.
function SwitcherPick(props: { switcher: Switcher; touch: boolean }) {
	const { switcher, touch } = props;
	const current = flatten(switcher.options).find(
		(option) => option.value === switcher.value,
	);
	const name = current?.label ?? switcher.label;
	return (
		<PickerBase
			label={switcher.label}
			options={switcher.options}
			value={switcher.value}
			onChange={switcher.onChange}
			act={switcher.act}
			drawn={(handed, open) => (
				<button
					{...handed}
					type="button"
					aria-label={`${switcher.label}, ${name}`}
					className={
						touch
							? cn(SWITCHER, TRIGGER_TOUCH)
							: cn(
									placeRow({ state: open ? "active" : "rest" }),
									TRIGGER,
									!open && ROW_PRESS,
								)
					}
				>
					<span aria-hidden className={GLYPH}>
						<Avatar name={name} src={current?.avatar?.src} />
					</span>
					<span
						className={cn(
							text({ role: "body" }),
							textStrong({ role: "body" }),
							touch ? NAME_TOUCH : NAME,
						)}
					>
						{name}
					</span>
					<span className={cn(placeRowGlyph({ state: "rest" }), GLYPH)}>
						<Icon name="ChevronsUpDown" />
					</span>
				</button>
			)}
		/>
	);
}

// The places past the tab bar, a page of rows: each place's glyph leading,
// its count trailing, its route where the row goes.
function MorePage(props: { places: readonly PlaceSpec[] }) {
	const words = useWords();
	return (
		<Place title={words.more}>
			<List>
				{props.places.map((spec) => (
					<ListRow
						key={spec.route}
						leading={{ icon: spec.icon }}
						title={spec.label}
						trailing={
							spec.count === undefined ? undefined : { count: spec.count }
						}
						href={spec.route}
					/>
				))}
			</List>
		</Place>
	);
}

// The touch shell's places: glyph over label, the count over the glyph's
// end; past five places, four and a More tab, which opens the page of the
// rest and is selected while it stands or the current place is among them.
// A tab holds its label ahead of its glyph and stacks them reversed, so its
// name reads the label then the count.
function TabBar(props: {
	places: readonly PlaceSpec[];
	pathname: string;
	more: boolean;
	onMore: () => void;
}) {
	const { places, pathname, more } = props;
	const words = useWords();
	const fits = places.length <= TAB_ROOM;
	const shown = fits ? places : places.slice(0, TAB_ROOM - 1);
	const rest = fits ? [] : places.slice(TAB_ROOM - 1);
	const inRest = rest.some((spec) => isCurrent(spec.route, pathname));
	const moreSelected = more || inRest;
	return (
		<nav aria-label={words.places} className={cn(SHELL_TAB_BAR, TABS)}>
			{shown.map((spec) => {
				const current = !more && isCurrent(spec.route, pathname);
				return (
					<a
						key={spec.route}
						href={spec.route}
						aria-current={current ? "page" : undefined}
						className={cn(
							placeTab({ state: current ? "selected" : "idle" }),
							TAB,
						)}
					>
						<Tab
							icon={
								<>
									<Icon name={spec.icon} fit="control" />
									{spec.count === undefined ? null : (
										<span className={TAB_COUNT}>
											<Count value={spec.count} />
										</span>
									)}
								</>
							}
							label={spec.label}
							selected={current}
						/>
					</a>
				);
			})}
			{rest.length > 0 ? (
				<button
					type="button"
					aria-current={moreSelected ? "page" : undefined}
					onClick={props.onMore}
					className={cn(
						placeTab({ state: moreSelected ? "selected" : "idle" }),
						TAB,
					)}
				>
					<Tab
						icon={<Icon name="Ellipsis" fit="control" />}
						label={words.more}
						selected={moreSelected}
					/>
				</button>
			) : null}
		</nav>
	);
}

function Tab(props: { icon: ReactNode; label: string; selected: boolean }) {
	return (
		<>
			<span
				className={cn(
					placeTabLabel({ state: props.selected ? "selected" : "idle" }),
					TAB_LABEL,
				)}
			>
				{props.label}
			</span>
			<span className={TAB_GLYPH}>{props.icon}</span>
		</>
	);
}
