// plugins/solid-ui/src/ui/components/form/index.tsx
import { rhythm } from "@fcalell/ui-core/variants";
import { createSignal, type JSX } from "solid-js";
import { BarContext } from "#lib/bar.ts";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { TouchedContext } from "#lib/touched.ts";

// Fields at `stack`; its `ActionBar` last and in flow, so it scrolls with the
// fields and the keyboard never covers it. A blocked act inside says its
// reason once a field has taken input.
export type FormProps = Closed & {
	onSubmit: () => void;
	children?: JSX.Element;
};

export function Form(props: FormProps) {
	const [touched, setTouched] = createSignal(false);
	return (
		<BarContext.Provider value="flow">
			<TouchedContext.Provider value={touched}>
				<form
					class={cn(rhythm({ unit: "stack" }), "flex flex-col")}
					onInput={() => setTouched(true)}
					onSubmit={(event) => {
						event.preventDefault();
						props.onSubmit();
					}}
				>
					{props.children}
				</form>
			</TouchedContext.Provider>
		</BarContext.Provider>
	);
}

// plugins/react-ui/src/ui/components/form/index.tsx
import { cn } from "@fcalell/ui-core/cn";
import { FORM_FOOT, form } from "@fcalell/ui-core/variants";
import {
	Children,
	isValidElement,
	type ReactNode,
	useMemo,
	useState,
} from "react";
import type { Closed } from "../../lib/closed.ts";
import { FormContext } from "../../lib/form.ts";
import { TouchedContext } from "../../lib/touched.ts";
import { ActionBar } from "../action-bar/index.tsx";
import { Section } from "../section/index.tsx";

const STACK = "flex flex-col";

/** Fields and the acts that submit them. */
export interface FormProps extends Closed {
	/** The fields, or the `Section`s that hold them, then its `ActionBar`, whose filled act submits the form. */
	children?: ReactNode;
}

/** Fields apart at the fields rhythm, or sections at the sections rhythm with the `ActionBar` under a hairline across the form. Its bar's filled act is the submit button, so Enter in a field runs that act's `onAct`; while its promise pends the act is pending, the others ignore the press and the form is busy. A blocked act says its reason once a field has taken input. */
export function Form({ children }: FormProps) {
	const [pending, setPending] = useState(false);
	const [touched, setTouched] = useState(false);
	const touch = useMemo(
		() => ({ touched, touch: () => setTouched(true) }),
		[touched],
	);
	const nodes = Children.toArray(children);
	const sectioned = nodes.some(
		(node) => isValidElement(node) && node.type === Section,
	);
	return (
		<FormContext value={setPending}>
			<TouchedContext value={touch}>
				{/* The submit act's click runs its `onAct`; the submit only stays on the page. */}
				<form
					onSubmit={(event) => event.preventDefault()}
					onChange={touch.touch}
					aria-busy={pending || undefined}
					className={cn(
						form({ holds: sectioned ? "sections" : "fields" }),
						STACK,
					)}
				>
					{sectioned
						? nodes.map((node) =>
								isValidElement(node) && node.type === ActionBar ? (
									<div key={node.key} className={FORM_FOOT}>
										{node}
									</div>
								) : (
									node
								),
							)
						: nodes}
				</form>
			</TouchedContext>
		</FormContext>
	);
}
