// plugins/solid-ui/src/ui/components/text/index.tsx
import { Polymorphic, type PolymorphicProps } from "@kobalte/core/polymorphic";
import {
	text,
	type TextTone,
	type TextVariant,
	textStrong,
} from "@fcalell/ui-core/variants";
import type { ValidComponent } from "solid-js";
import { splitProps } from "solid-js";
import { cn } from "#lib/cn";

type TextProps = {
	variant?: TextVariant;
	tone?: TextTone;
	strong?: boolean;
	mono?: boolean;
	class?: string;
};

function Text<T extends ValidComponent = "p">(
	props: PolymorphicProps<T, TextProps>,
) {
	const [local, rest] = splitProps(props as TextProps, [
		"variant",
		"tone",
		"strong",
		"mono",
		"class",
	]);
	const variant = () => local.variant ?? "body";
	return (
		<Polymorphic
			as="p"
			class={cn(
				text({ variant: variant(), tone: local.tone }),
				local.strong && textStrong({ variant: variant() }),
				// Font family is a platform overlay, so it never enters the matrix.
				local.mono && "font-mono",
				local.class,
			)}
			{...rest}
		/>
	);
}

export type { TextProps };
export { Text };

// plugins/native-ui/src/ui/components/text/index.tsx
import {
	type TextTone,
	type TextVariant,
	text,
	textStrong,
} from "@fcalell/ui-core/variants";
import { Text as RNText, type TextProps as RNTextProps } from "react-native";
import { cn } from "../../lib/cn";

export interface TextProps extends RNTextProps {
	variant?: TextVariant;
	tone?: TextTone;
	strong?: boolean;
	mono?: boolean;
}

export function Text({
	variant,
	tone,
	strong,
	mono,
	className,
	...rest
}: TextProps) {
	const role = variant ?? "body";
	return (
		<RNText
			className={cn(
				// Web inherits `ink-1` from its base layer; RN Text inherits nothing,
				// so the default tone is explicit here.
				text({ variant: role, tone: tone ?? "ink-1" }),
				strong && textStrong({ variant: role }),
				// Font family is a platform overlay, so it never enters the matrix.
				// Without a registered mono font this degrades to the system face.
				mono && "font-mono",
				className,
			)}
			{...rest}
		/>
	);
}
