// plugins/solid-ui/src/ui/lib/toast.ts
import type { Act } from "@fcalell/ui-core/descriptors";
import type { ToastState } from "@fcalell/ui-core/variants";
import { createSignal } from "solid-js";

// The toast queue, client-owned: `toast()` pushes, the app root draws, so a
// page with no shell (a sign-in) shows its toasts too. One toast at a time
// above the bar, each gone after its time or its act. `state` says how the
// act it reports ended (`failed` for a refused edit, `done` for a finished
// one); without it the toast is the plain dark pill.
export interface ToastOptions {
	state?: ToastState;
	act?: Act;
}

export interface ToastEntry extends ToastOptions {
	id: number;
	sentence: string;
}

const LIFETIME_MS = 4000;

const [entries, setEntries] = createSignal<ToastEntry[]>([]);
let next = 1;

export function toast(sentence: string, options: ToastOptions = {}): void {
	const id = next++;
	setEntries((queue) => [...queue, { id, sentence, ...options }]);
	setTimeout(() => dismissToast(id), LIFETIME_MS);
}

export function dismissToast(id: number): void {
	setEntries((queue) => queue.filter((entry) => entry.id !== id));
}

export const toasts = entries;

// Where the queue stands, in pixels from the viewport's edges: the box it
// centres in (`left`, `right`) and how far above the viewport's bottom it
// starts. With no shell it is the whole viewport; a `Shell` places it over
// its column, above its tab bar and any pinned bar.
export interface ToastPlacement {
	left: number;
	right: number;
	bottom: number;
}

const VIEWPORT: ToastPlacement = { left: 0, right: 0, bottom: 0 };

const [placement, setPlacement] = createSignal<ToastPlacement>(VIEWPORT);

export const toastPlacement = placement;

export function placeToasts(next: ToastPlacement | undefined): void {
	setPlacement(next ?? VIEWPORT);
}

// plugins/react-ui/src/ui/lib/toast.ts
import { Toast } from "@base-ui/react/toast";
import type { Act } from "@fcalell/ui-core/descriptors";
import type { ToastState } from "@fcalell/ui-core/variants";
import { createContext } from "react";

// How the act a toast reports ended (its glyph in the state's ink), and an
// act it offers (a route or a retry; client-owned, so never an undo).
export interface ToastOptions {
	state?: ToastState;
	act?: Act;
}

// The app's toast queue: `toast()` is called from anywhere, and the Shell
// stands the queue in its toasts' layer. A failed one is announced at once.
export interface ToastData extends ToastOptions {
	sentence: string;
}

export const toasts = Toast.createToastManager<ToastData>();

export function toast(sentence: string, options: ToastOptions = {}): void {
	toasts.add({
		description: sentence,
		data: { sentence, ...options },
		priority: options.state === "failed" ? "high" : "low",
	});
}

// The queued toast a `Toast` draws: the layer hands each its entry.
export const ToastEntry = createContext<
	Toast.Root.ToastObject<ToastData> | undefined
>(undefined);
