// plugins/solid-ui/src/ui/lib/words.tsx
import type { Words } from "@fcalell/ui-core/tokens";
import { ENGLISH } from "@fcalell/ui-core/tokens";
import { createContext, type JSX, useContext } from "solid-js";

// Every word a molecule draws on its own. The generated entry mounts the
// provider with the consumer's `words` option; without it the components
// speak English.
const WordsContext = createContext<Words>(ENGLISH);

export function WordsProvider(props: { words: Words; children: JSX.Element }) {
	return (
		<WordsContext.Provider value={props.words}>
			{props.children}
		</WordsContext.Provider>
	);
}

export function useWords(): Words {
	return useContext(WordsContext);
}

// plugins/react-ui/src/ui/lib/words.tsx
import type { Words } from "@fcalell/ui-core/tokens";
import { ENGLISH } from "@fcalell/ui-core/tokens";
import { createContext, type ReactNode, use } from "react";

// Every word a molecule draws on its own. The generated providers mount the
// context with the consumer's `words` option; without it the components
// speak English.
const WordsContext = createContext<Words>(ENGLISH);

export function WordsProvider(props: { words: Words; children: ReactNode }) {
	return <WordsContext value={props.words}>{props.children}</WordsContext>;
}

export function useWords(): Words {
	return use(WordsContext);
}
