// plugins/native-ui/src/ui/components/diff/index.tsx
import type { Hunk } from "@fcalell/ui-core/descriptors";
import { DIFF_GUTTER, diffLine, GROUP, text } from "@fcalell/ui-core/variants";
import { Text as RNText, ScrollView, View } from "react-native";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { lineHunks } from "../../lib/line-diff";
import { LoadingRows } from "../../lib/loading";

interface DiffBase extends Closed {
	loading?: boolean;
}

// The lines come as `hunks`, or as two texts a machine reads, `before` and
// `after`, diffed here by line.
export type DiffProps =
	| (DiffBase & { hunks: readonly Hunk[]; before?: never; after?: never })
	| (DiffBase & { hunks?: never; before: string; after: string });

// A hunk is keyed by its header and its first line numbers, which no two
// hunks of one diff share.
function hunkKey(hunk: Hunk): string {
	const first = hunk.lines[0];
	return `${hunk.header}:${first?.before ?? ""}:${first?.after ?? ""}`;
}

// Mono with a line-number gutter that scrolls with the lines; added lines on
// ok-soft, removed on danger-soft. The phone draws unified.
export function Diff({ hunks: given, before, after, loading }: DiffProps) {
	if (loading) return <LoadingRows />;
	const hunks = given ?? lineHunks(before ?? "", after ?? "");
	return (
		<ScrollView
			horizontal
			showsHorizontalScrollIndicator={false}
			className={cn(GROUP, "overflow-hidden")}
		>
			<View>
				{hunks.map((hunk) => (
					<View key={hunkKey(hunk)}>
						<RNText className={cn(diffLine({ kind: "header" }), "px-pair")}>
							{hunk.header}
						</RNText>
						{hunk.lines.map((line, index) => (
							<View
								// biome-ignore lint/suspicious/noArrayIndexKey: lines are positional
								key={index}
								className={cn(
									diffLine({ kind: line.kind }),
									"flex-row gap-inside px-pair",
								)}
							>
								<RNText
									className={cn(
										text({ role: "code" }),
										DIFF_GUTTER,
										"w-8 text-right",
									)}
								>
									{line.before ?? ""}
								</RNText>
								<RNText
									className={cn(
										text({ role: "code" }),
										DIFF_GUTTER,
										"w-8 text-right",
									)}
								>
									{line.after ?? ""}
								</RNText>
								<RNText className={text({ role: "code" })}>
									{line.kind === "added"
										? "+"
										: line.kind === "removed"
											? "−"
											: " "}
									{line.text}
								</RNText>
							</View>
						))}
					</View>
				))}
			</View>
		</ScrollView>
	);
}

// plugins/solid-ui/src/ui/components/diff/index.tsx
import type { DiffLine, Hunk } from "@fcalell/ui-core/descriptors";
import { CODE, DIFF_GUTTER, diffLine } from "@fcalell/ui-core/variants";
import { createMemo, For, Show } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { RING_INSET } from "#lib/interact.ts";
import { lineHunks } from "#lib/line-diff.ts";
import { LoadingRows } from "#lib/loading.tsx";

// Mono with a line-number gutter pinned left; added lines on the ok soft,
// removed on the danger soft, hunk headers on the group fill. One column at
// every width: a pane is never wide enough for two readable sides. The lines
// come as `hunks`, or as two texts a machine reads, `before` and `after` (a
// JSON document observed beside the one specified), diffed here by line.
export type DiffProps = Closed &
	(
		| { hunks: Hunk[]; before?: never; after?: never; loading?: boolean }
		| { hunks?: never; before: string; after: string; loading?: boolean }
	);

const GUTTER = cn(
	DIFF_GUTTER,
	"sticky left-0 w-12 shrink-0 select-none bg-inherit pr-row text-right tabular-nums",
);

function Line(props: { line: DiffLine }) {
	// `bg-inherit` first, so a context line keeps the block's fill under the
	// pinned gutter and an added or removed line's own fill wins the merge.
	return (
		<div
			class={cn("flex bg-inherit px-row", diffLine({ kind: props.line.kind }))}
		>
			<span class={GUTTER}>{props.line.after ?? props.line.before}</span>
			<span class="whitespace-pre">{props.line.text}</span>
		</div>
	);
}

export function Diff(props: DiffProps) {
	const hunks = createMemo(
		() => props.hunks ?? lineHunks(props.before ?? "", props.after ?? ""),
	);
	return (
		<Show when={!props.loading} fallback={<LoadingRows />}>
			{/* The surface keeps its corners; the scroller inside it takes focus
			    so a keyboard can scroll it. */}
			<div class={cn(CODE, "overflow-hidden p-0")}>
				<div tabindex="0" class={cn("overflow-x-auto", RING_INSET)}>
					<For each={hunks()}>
						{(hunk) => (
							<>
								<div class={cn(diffLine({ kind: "header" }), "px-row")}>
									{hunk.header}
								</div>
								<For each={hunk.lines}>{(line) => <Line line={line} />}</For>
							</>
						)}
					</For>
				</div>
			</div>
		</Show>
	);
}
