// plugins/react-ui/src/ui/components/definition-row/index.tsx
import { Button as BaseButton } from "@base-ui/react/button";
import { cn } from "@fcalell/ui-core/cn";
import type { IconAct, StatusState } from "@fcalell/ui-core/descriptors";
import {
	DEFINITION_ROW,
	DEFINITION_ROW_CHEVRON,
	ROW_TITLE_LINE,
	row,
	text,
	textStrong,
} from "@fcalell/ui-core/variants";
import { type ReactNode, useEffect, useState } from "react";
import type { Closed } from "../../lib/closed.ts";
import { useWords } from "../../lib/words.tsx";
import { Icon } from "../icon/index.tsx";
import { IconButton } from "../icon-button/index.tsx";
import { Status } from "../status/index.tsx";

const ROW = "relative flex items-center";
// A row that opens washes under the pointer and the press on its hit.
const ROW_PRESS = "hover:bg-wash-hover active:bg-wash-press";
// The label is the link: its after layer covers the row, so the whole row
// opens, and draws the ring inset at the row's edge.
const HIT =
	"after:absolute after:inset-0 focus-visible:outline-none focus-visible:after:outline-2 focus-visible:after:-outline-offset-2 focus-visible:after:outline-ring";
const TEXT_BLOCK = "flex flex-col grow min-w-0";
const LINE = "flex items-center min-w-0";
const LABEL = "truncate";
// The value gives way first: it takes the room the label leaves, ending at
// the line's end.
const VALUE = "basis-0 grow min-w-0 truncate text-end";
const VALUE_SLOT = "flex basis-0 grow min-w-0 justify-end";
const ACTS = "relative flex shrink-0";
// The chevron draws in the slot's ink (currentColor).
const CHEVRON = "flex shrink-0 items-center justify-center text-ink-meta";

const COPIED_MS = 2000;

/** What a definition shows: words, a status, or an in-place control. */
export type DefinitionValue =
	| string
	| { status: StatusState; label?: string }
	| ReactNode;

/** A labelled fact in a Group. */
export interface DefinitionRowProps extends Closed {
	/** What the fact is. */
	label: string;
	/** A sentence under the label and the value, at the row's width. */
	description?: string;
	/** The fact: words, a status, or a control that changes it in place. */
	value?: DefinitionValue;
	/** Words that are copied whole (an identifier): drawn in the code role with a copy act. */
	copyable?: boolean;
	/** The row's one icon act at its end. */
	act?: IconAct;
	/** Where the row goes when opened; a chevron stands at its end. */
	href?: string;
	/** Opens what the row names; a chevron stands at its end. */
	onOpen?: () => void;
}

function isStatus(
	value: DefinitionValue,
): value is { status: StatusState; label?: string } {
	return typeof value === "object" && value !== null && "status" in value;
}

/** The label at body 500 with the value at the line's end, the description under both; an icon act, or a link's chevron in the act's square, at the row's end, so values with either end at one x. */
export function DefinitionRow({
	label,
	description,
	value,
	copyable,
	act,
	href,
	onOpen,
}: DefinitionRowProps) {
	const opens = href !== undefined || onOpen !== undefined;
	const copied = copyable && typeof value === "string" ? value : undefined;
	let shown: ReactNode = null;
	if (typeof value === "string")
		shown = (
			<span className={cn(text({ role: copied ? "code" : "meta" }), VALUE)}>
				{value}
			</span>
		);
	else if (isStatus(value))
		shown = (
			<span className={VALUE_SLOT}>
				<Status state={value.status} label={value.label} />
			</span>
		);
	else if (value !== undefined && value !== null)
		shown = <span className={VALUE_SLOT}>{value}</span>;
	let end: ReactNode = null;
	if (copied !== undefined || act)
		end = (
			<span className={ACTS}>
				{copied === undefined ? null : <CopyAct label={label} value={copied} />}
				{act ? (
					<IconButton
						icon={act.icon}
						fit="bar"
						label={act.label}
						onAct={act.onAct}
					/>
				) : null}
			</span>
		);
	else if (opens)
		end = (
			<span className={cn(DEFINITION_ROW_CHEVRON, CHEVRON)}>
				<Icon name="ChevronRight" />
			</span>
		);
	const name = cn(
		text({ role: "body" }),
		textStrong({ role: "body" }),
		LABEL,
		opens && HIT,
	);
	let title: ReactNode = <span className={name}>{label}</span>;
	if (href !== undefined)
		title = (
			<a href={href} className={name}>
				{label}
			</a>
		);
	else if (onOpen)
		title = (
			<BaseButton onClick={onOpen} className={name}>
				{label}
			</BaseButton>
		);
	return (
		<div
			className={cn(
				row({
					lines: description ? "setting" : "one",
					state: "rest",
					ground: "group",
				}),
				DEFINITION_ROW,
				ROW,
				opens && ROW_PRESS,
			)}
		>
			<span className={TEXT_BLOCK}>
				<span className={cn(ROW_TITLE_LINE, LINE)}>
					{title}
					{shown}
				</span>
				{description ? (
					<span className={text({ role: "meta" })}>{description}</span>
				) : null}
			</span>
			{end}
		</div>
	);
}

// The copy act: a check and the word Copied for two seconds once copied.
function CopyAct({ label, value }: { label: string; value: string }) {
	const words = useWords();
	const [done, setDone] = useState(false);
	useEffect(() => {
		if (!done) return;
		const timer = setTimeout(() => setDone(false), COPIED_MS);
		return () => clearTimeout(timer);
	}, [done]);
	return (
		<IconButton
			icon={done ? "Check" : "Copy"}
			fit="bar"
			label={done ? words.copied : `${words.copy} ${label}`}
			onAct={() => {
				navigator.clipboard.writeText(value).then(() => setDone(true));
			}}
		/>
	);
}

// plugins/solid-ui/src/ui/components/definition-row/index.tsx
import type { Act } from "@fcalell/ui-core/descriptors";
import type { StatusState } from "@fcalell/ui-core/tokens";
import { row, text } from "@fcalell/ui-core/variants";
import { A } from "@solidjs/router";
import { createSignal, type JSX, Match, Show, Switch } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { useWords } from "#lib/words.tsx";
import { Status } from "../status/index.tsx";

export type DefinitionValue =
	| string
	| { status: StatusState; label?: string }
	| JSX.Element;

// A labelled fact in a group: the label left, the value or the in-place
// control right, and the description under both at the row's width.
// `copyable` puts a copy act beside a string value. The value takes its own
// width up to three fifths and wraps inside it past that, at any character,
// so a key or an address never runs under the label; the label takes the
// rest.
export type DefinitionRowProps = Closed & {
	label: string;
	description?: string;
	value?: DefinitionValue;
	copyable?: boolean;
	act?: Act;
	href?: string;
	onOpen?: () => void;
};

const COPIED_MS = 2000;

// The row's vertical padding is given to the act, so its 44 px hit area
// leaves the row as tall as one with no act.
const ACT =
	"-my-stack min-h-11 shrink-0 cursor-pointer px-row font-medium text-tint disabled:text-ink-faint";

function isStatus(
	value: DefinitionValue,
): value is { status: StatusState; label?: string } {
	return typeof value === "object" && value !== null && "status" in value;
}

export function DefinitionRow(props: DefinitionRowProps) {
	const words = useWords();
	const [copied, setCopied] = createSignal(false);
	const interactive = () =>
		props.href !== undefined || props.onOpen !== undefined;
	const shell = () =>
		cn(
			row({ state: "rest" }),
			"flex w-full flex-col justify-center gap-pair text-left",
			interactive() &&
				"cursor-pointer transition-colors duration-(--duration-fast) ease-ui hover:bg-edge active:bg-edge focus-visible:outline-2 focus-visible:-outline-offset-2 focus-visible:outline-tint",
		);
	const copy = async () => {
		if (typeof props.value !== "string") return;
		await navigator.clipboard.writeText(props.value);
		setCopied(true);
		setTimeout(() => setCopied(false), COPIED_MS);
	};
	const body = () => (
		<>
			<span class="flex w-full items-center gap-stack">
				<span class={cn(text({ role: "body" }), "min-w-0 flex-1")}>
					{props.label}
				</span>
				<Show when={props.value !== undefined}>
					<span class="flex max-w-3/5 shrink-0 items-center justify-end gap-row text-right wrap-anywhere">
						<Switch fallback={props.value as JSX.Element}>
							<Match when={typeof props.value === "string" && props.value}>
								{(value) => (
									<span class={cn(text({ role: "meta" }), "text-ink")}>
										{value()}
									</span>
								)}
							</Match>
							<Match when={isStatus(props.value) && props.value}>
								{(value) => (
									<Status state={value().status} label={value().label} />
								)}
							</Match>
						</Switch>
					</span>
				</Show>
				<Show when={props.copyable && typeof props.value === "string"}>
					<button
						type="button"
						class={cn(text({ role: "meta" }), ACT)}
						onClick={(event) => {
							event.stopPropagation();
							void copy();
						}}
					>
						{copied() ? words.copied : words.copy}
					</button>
				</Show>
				<Show when={props.act}>
					{(act) => (
						<button
							type="button"
							disabled={act().blocked !== undefined}
							class={cn(text({ role: "meta" }), ACT)}
							onClick={(event) => {
								event.stopPropagation();
								act().onAct();
							}}
						>
							{act().label}
						</button>
					)}
				</Show>
			</span>
			<Show when={props.description}>
				<span class={text({ role: "meta" })}>{props.description}</span>
			</Show>
		</>
	);
	return (
		<Switch fallback={<div class={shell()}>{body()}</div>}>
			<Match when={props.href}>
				{(href) => (
					<A href={href()} class={shell()}>
						{body()}
					</A>
				)}
			</Match>
			<Match when={props.onOpen}>
				{(onOpen) => (
					<button type="button" class={shell()} onClick={() => onOpen()()}>
						{body()}
					</button>
				)}
			</Match>
		</Switch>
	);
}
