// plugins/native-ui/src/ui/components/definition-row/index.tsx
import type { IconAct, StatusState } from "@fcalell/ui-core/descriptors";
import { row, text, textStrong } from "@fcalell/ui-core/variants";
import * as Clipboard from "expo-clipboard";
import { type ReactNode, useCallback, useEffect, useState } from "react";
import { Pressable, Text as RNText, View } from "react-native";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { navigate } from "../../lib/navigate";
import { RowContext } from "../../lib/row";
import { useWords } from "../../lib/words";
import { IconButton } from "../icon-button";
import { IconButtonBase } from "../icon-button/base";
import { Status } from "../status";

export type DefinitionValue =
	| string
	| { status: StatusState; label?: string }
	| ReactNode;

export interface DefinitionRowProps extends Closed {
	label: string;
	description?: string;
	value?: DefinitionValue;
	copyable?: boolean;
	act?: IconAct;
	href?: string;
	onOpen?: () => void;
}

const COPIED_MS = 2000;

function isStatus(
	value: DefinitionValue,
): value is { status: StatusState; label?: string } {
	return typeof value === "object" && value !== null && "status" in value;
}

// A labelled fact: the label left, the value or the in-place control right,
// and the description under both at the row's width. A control whose width
// is its words (a `Picker`) claims the row (`lib/row.ts`), and the row then
// stacks, as the web's does under tablet: the label and the description,
// then the control across the row with the act at its end.
export function DefinitionRow({
	label,
	description,
	value,
	copyable,
	act,
	href,
	onOpen,
}: DefinitionRowProps) {
	const [stacked, setStacked] = useState(false);
	const claim = useCallback((next: boolean) => setStacked(next), []);
	const open = href !== undefined ? () => navigate(href) : onOpen;
	const shown = (
		<RowContext.Provider value={claim}>
			{typeof value === "string" ? (
				<RNText className={cn(text({ role: "meta" }), "shrink text-right")}>
					{value}
				</RNText>
			) : isStatus(value) ? (
				<Status state={value.status} label={value.label} />
			) : (
				value
			)}
		</RowContext.Provider>
	);
	const acts = (
		<>
			{copyable && typeof value === "string" ? <CopyAct value={value} /> : null}
			{act ? <IconButton {...act} /> : null}
		</>
	);
	return (
		<Pressable
			accessibilityRole={open ? "button" : undefined}
			disabled={!open}
			onPress={open}
			className={cn(
				row({ state: "rest" }),
				"justify-center gap-pair",
				open && "active:bg-wash-press",
			)}
		>
			<View className="flex-row items-center gap-pair">
				<RNText
					className={cn(
						text({ role: "body" }),
						textStrong({ role: "body" }),
						"flex-1",
					)}
				>
					{label}
				</RNText>
				{stacked ? null : shown}
				{stacked ? null : acts}
			</View>
			{description ? (
				<RNText className={text({ role: "meta" })}>{description}</RNText>
			) : null}
			{stacked ? (
				<View className="flex-row items-center gap-pair">
					<View className="min-w-0 flex-1">{shown}</View>
					{acts}
				</View>
			) : null}
		</Pressable>
	);
}

function CopyAct({ value }: { value: string }) {
	const words = useWords();
	const [copied, setCopied] = useState(false);
	useEffect(() => {
		if (!copied) return;
		const timer = setTimeout(() => setCopied(false), COPIED_MS);
		return () => clearTimeout(timer);
	}, [copied]);
	return (
		<IconButtonBase
			icon={copied ? "Check" : "Copy"}
			label={copied ? words.copied : words.copy}
			onAct={() => {
				Clipboard.setStringAsync(value).then(() => setCopied(true));
			}}
		/>
	);
}

// plugins/solid-ui/src/ui/components/definition-row/index.tsx
import type { Act } from "@fcalell/ui-core/descriptors";
import type { StatusState } from "@fcalell/ui-core/tokens";
import { row, text } from "@fcalell/ui-core/variants";
import { A } from "@solidjs/router";
import { createSignal, type JSX, Match, Show, Switch } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { RING_INSET, TEXT_ACT, WASH } from "#lib/interact.ts";
import { useWords } from "#lib/words.tsx";
import { Status } from "../status/index.tsx";

export type DefinitionValue =
	| string
	| { status: StatusState; label?: string }
	| JSX.Element;

// A labelled fact in a group: the label left, the value or the in-place
// control right, and the description under both at the row's width.
// `copyable` puts a copy act beside a string value. The value takes its own
// width up to three fifths and wraps inside it past that, at any character,
// so a key or an address never runs under the label; the label takes the
// rest.
export type DefinitionRowProps = Closed & {
	label: string;
	description?: string;
	value?: DefinitionValue;
	copyable?: boolean;
	act?: Act;
	href?: string;
	onOpen?: () => void;
};

const COPIED_MS = 2000;

// The row's vertical padding is given to the act, so its 44 px hit area
// leaves the row as tall as one with no act.
const ACT = cn("-my-stack min-h-11 shrink-0 px-row", TEXT_ACT);

function isStatus(
	value: DefinitionValue,
): value is { status: StatusState; label?: string } {
	return typeof value === "object" && value !== null && "status" in value;
}

export function DefinitionRow(props: DefinitionRowProps) {
	const words = useWords();
	const [copied, setCopied] = createSignal(false);
	const interactive = () =>
		props.href !== undefined || props.onOpen !== undefined;
	const shell = () =>
		cn(
			row({ state: "rest" }),
			"flex w-full flex-col justify-center gap-pair text-left",
			interactive() &&
				cn(
					"cursor-pointer transition-colors duration-(--duration-fast) ease-ui",
					WASH,
					RING_INSET,
				),
		);
	const copy = async () => {
		if (typeof props.value !== "string") return;
		await navigator.clipboard.writeText(props.value);
		setCopied(true);
		setTimeout(() => setCopied(false), COPIED_MS);
	};
	const body = () => (
		<>
			<span class="flex w-full items-center gap-stack">
				<span class={cn(text({ role: "body" }), "min-w-0 flex-1")}>
					{props.label}
				</span>
				<Show when={props.value !== undefined}>
					<span class="flex max-w-3/5 shrink-0 items-center justify-end gap-row text-right wrap-anywhere">
						<Switch fallback={props.value as JSX.Element}>
							<Match when={typeof props.value === "string" && props.value}>
								{(value) => (
									<span class={cn(text({ role: "meta" }), "text-ink")}>
										{value()}
									</span>
								)}
							</Match>
							<Match when={isStatus(props.value) && props.value}>
								{(value) => (
									<Status state={value().status} label={value().label} />
								)}
							</Match>
						</Switch>
					</span>
				</Show>
				<Show when={props.copyable && typeof props.value === "string"}>
					<button
						type="button"
						class={cn(text({ role: "meta" }), ACT)}
						onClick={(event) => {
							event.stopPropagation();
							void copy();
						}}
					>
						{copied() ? words.copied : words.copy}
					</button>
				</Show>
				<Show when={props.act}>
					{(act) => (
						<button
							type="button"
							disabled={act().blocked !== undefined}
							class={cn(text({ role: "meta" }), ACT)}
							onClick={(event) => {
								event.stopPropagation();
								act().onAct();
							}}
						>
							{act().label}
						</button>
					)}
				</Show>
			</span>
			<Show when={props.description}>
				<span class={text({ role: "meta" })}>{props.description}</span>
			</Show>
		</>
	);
	return (
		<Switch fallback={<div class={shell()}>{body()}</div>}>
			<Match when={props.href}>
				{(href) => (
					<A href={href()} class={shell()}>
						{body()}
					</A>
				)}
			</Match>
			<Match when={props.onOpen}>
				{(onOpen) => (
					<button type="button" class={shell()} onClick={() => onOpen()()}>
						{body()}
					</button>
				)}
			</Match>
		</Switch>
	);
}
