// plugins/solid-ui/src/ui/components/pending-bar/index.tsx
import type { Act } from "@fcalell/ui-core/descriptors";
import { PENDING_BAR, PENDING_FILL, text } from "@fcalell/ui-core/variants";
import { createSignal, onCleanup, onMount, Show } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { TEXT_ACT } from "#lib/interact.ts";
import { Spinner } from "../spinner/index.tsx";

// One line with a spinner, or a countdown that fills the bar toward a server
// deadline, and one act. Placed in an `ActionBar`'s place, a `Sheet`'s foot,
// above a message input, or as a row of a thread.
export type PendingBarProps = Closed & {
	sentence: string;
	until?: Date;
	act?: Act;
};

const TICK_MS = 250;

export function PendingBar(props: PendingBarProps) {
	const started = Date.now();
	const [now, setNow] = createSignal(started);
	onMount(() => {
		const timer = setInterval(() => setNow(Date.now()), TICK_MS);
		onCleanup(() => clearInterval(timer));
	});
	const progress = () => {
		const until = props.until;
		if (!until) return 0;
		const total = until.getTime() - started;
		if (total <= 0) return 1;
		return Math.min(1, (now() - started) / total);
	};
	return (
		<div
			role="status"
			class={cn(PENDING_BAR, "relative flex items-center overflow-hidden")}
		>
			<Show when={props.until}>
				<div
					class={cn(PENDING_FILL, "absolute inset-y-0 left-0")}
					style={{ width: `${progress() * 100}%` }}
					aria-hidden="true"
				/>
			</Show>
			<span class="relative flex min-w-0 flex-1 items-center gap-row">
				<Show when={!props.until}>
					<Spinner />
				</Show>
				<span class={cn(text({ role: "meta" }), "truncate text-ink")}>
					{props.sentence}
				</span>
			</span>
			<Show when={props.act}>
				{(act) => (
					<button
						type="button"
						disabled={act().blocked !== undefined}
						onClick={() => act().onAct()}
						class={cn(
							text({ role: "meta" }),
							"relative -mr-inset min-h-11 shrink-0 self-stretch px-inset",
							TEXT_ACT,
						)}
					>
						{act().label}
					</button>
				)}
			</Show>
		</div>
	);
}

// plugins/react-ui/src/ui/components/pending-bar/index.tsx
import { cn } from "@fcalell/ui-core/cn";
import type { Act } from "@fcalell/ui-core/descriptors";
import {
	PENDING_BAR,
	PENDING_FILL,
	PENDING_LEFT,
	PENDING_ROW,
	PENDING_TRACK,
	text,
} from "@fcalell/ui-core/variants";
import { useEffect, useId, useMemo, useState } from "react";
import type { Closed } from "../../lib/closed.ts";
import { ReasonHostContext } from "../../lib/reason.ts";
import { useTouched } from "../../lib/touched.ts";
import { Button } from "../button/index.tsx";
import { Reason } from "../button/reason.tsx";
import { Spinner } from "../spinner/index.tsx";

// The bar over a blocked act's reason, at the end on the desktop; on touch
// the track stacks over the act as an ActionBar's acts do.
const BAR = "flex flex-col items-end touch:items-stretch";
const ROW = "flex items-center self-stretch touch:flex-col touch:items-stretch";
const TRACK = "relative flex items-center grow min-w-0 overflow-hidden";
// The elapsed share, its width the runtime fraction.
const FILL = "absolute bottom-0 left-0";
// The track's parts stand over the fill.
const SPINNER_SLOT = "relative flex shrink-0 text-ink-meta";
const SENTENCE = "relative min-w-0 grow truncate";
const LEFT = "relative shrink-0";

const TICK_MS = 1000;

// The time left, minutes then seconds padded to two.
function clock(ms: number): string {
	const seconds = Math.max(0, Math.ceil(ms / 1000));
	return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`;
}

/** Work the page waits on, in an ActionBar's place. */
export interface PendingBarProps extends Closed {
	/** What is happening, announced as it changes. */
	sentence: string;
	/** When the work ends: the track fills toward it and shows the time left; unset, a spinner turns. */
	until?: Date;
	/** The one act, a hairline Button beside the track; a blocked act's reason draws under the bar. */
	act?: Act;
}

/** One line on the group ground: the spinner, or a meta-ink line along the track's foot filling toward `until` with the time left beside the sentence, which alone is the live region; the act beside it on the desktop, under it on touch. */
export function PendingBar({ sentence, until, act }: PendingBarProps) {
	const [start] = useState(() => Date.now());
	const [now, setNow] = useState(start);
	const reasonId = useId();
	const { touched } = useTouched();
	const blocked = act?.blocked;
	const [pressed, setPressed] = useState(false);
	useEffect(() => {
		if (!until) return;
		const timer = setInterval(() => setNow(Date.now()), TICK_MS);
		return () => clearInterval(timer);
	}, [until]);
	useEffect(() => {
		if (blocked === undefined) setPressed(false);
	}, [blocked]);
	const host = useMemo(
		() =>
			blocked === undefined
				? undefined
				: { id: reasonId, press: () => setPressed(true) },
		[blocked, reasonId],
	);
	const end = until?.getTime();
	const share =
		end === undefined || end <= start
			? 1
			: Math.min(1, (now - start) / (end - start));
	return (
		<div className={cn(PENDING_BAR, BAR)}>
			<div className={cn(PENDING_ROW, ROW)}>
				<div className={cn(PENDING_TRACK, TRACK)}>
					{end === undefined ? (
						<span className={SPINNER_SLOT}>
							<Spinner />
						</span>
					) : (
						<span
							aria-hidden
							className={cn(PENDING_FILL, FILL)}
							style={{ width: `${share * 100}%` }}
						/>
					)}
					<span role="status" className={cn(text({ role: "body" }), SENTENCE)}>
						{sentence}
					</span>
					{end === undefined ? null : (
						<span className={cn(PENDING_LEFT, LEFT)}>{clock(end - now)}</span>
					)}
				</div>
				{act ? (
					<ReasonHostContext value={host}>
						<Button
							act="secondary"
							label={act.label}
							onAct={act.onAct}
							loading={act.loading}
							blocked={blocked}
						/>
					</ReasonHostContext>
				) : null}
			</div>
			{blocked === undefined ? null : (
				<Reason id={reasonId} shown={pressed || touched}>
					{blocked}
				</Reason>
			)}
		</div>
	);
}
