// plugins/react-ui/src/ui/components/menu/index.tsx
import { Dialog } from "@base-ui/react/dialog";
import { Menu as Control } from "@base-ui/react/menu";
import { cn } from "@fcalell/ui-core/cn";
import type { MenuItem } from "@fcalell/ui-core/descriptors";
import {
	menu,
	menuGroup,
	menuLabel,
	POPOVER,
	row,
	text,
} from "@fcalell/ui-core/variants";
import { type ReactNode, use, useState } from "react";
import { arrowsOver } from "../../lib/arrows.ts";
import type { Closed } from "../../lib/closed.ts";
import { spacing, useTouch } from "../../lib/media.ts";
import { PortalContainer } from "../../lib/portal.ts";
import { Icon } from "../icon/index.tsx";
import { IconButtonBase } from "../icon-button/base.tsx";
import { SheetBase } from "../sheet/base.tsx";

const POPUP = "flex flex-col";
// The popover drops in from a float above as it fades, and fades out; on
// transform and opacity alone, the rungs zeroed under reduced motion.
const POPUP_MOTION =
	"transition-[opacity,translate] duration-base ease-out data-starting-style:-translate-y-float data-starting-style:opacity-0 data-ending-style:opacity-0 data-ending-style:duration-fast data-ending-style:ease-in";
const GROUP = "flex flex-col";
// A row the keyboard reaches rings inset over its wash, which alone sits
// under the 3:1 a state needs; the pointer's highlight is the wash alone.
const ITEM = "flex items-center focus-visible:-outline-offset-2";
const PRESS = "active:bg-wash-press";
// A touch row is a button: the start of its line, and its focus the
// keyboard's highlight.
const BUTTON = "text-start focus-visible:bg-wash-hover";
const GLYPH = "flex shrink-0";
const GLYPH_INK = {
	act: "text-ink-meta",
	destructive: "text-danger",
	blocked: "text-ink-disabled",
} as const;
const LABEL = "min-w-0 grow truncate";
const LABEL_BLOCKED = "truncate text-ink-disabled";
const TEXT = "flex flex-col min-w-0 grow";

/** A menu of acts behind the more act. */
export interface MenuProps extends Closed {
	/** The trigger's accessible name, and the touch sheet's title. */
	label: string;
	/** The acts in order; the destructive ones stand last under a hairline. */
	items: readonly MenuItem[];
}

function groupsOf(items: readonly MenuItem[]) {
	return [
		{ kind: "acts" as const, items: items.filter((item) => !item.destructive) },
		{
			kind: "destructive" as const,
			items: items.filter((item) => item.destructive),
		},
	].filter((group) => group.items.length > 0);
}

// An item's glyph, its label and, blocked, its reason under the label.
function ItemLine(props: { item: MenuItem }) {
	const { item } = props;
	const blocked = item.blocked !== undefined;
	const kind = item.destructive ? "destructive" : "act";
	return (
		<>
			{item.icon ? (
				<span className={cn(GLYPH, GLYPH_INK[blocked ? "blocked" : kind])}>
					<Icon name={item.icon} />
				</span>
			) : null}
			{blocked ? (
				<span className={TEXT}>
					<span
						className={cn(
							text({ role: "body" }),
							menuLabel({ kind }),
							LABEL_BLOCKED,
						)}
					>
						{item.label}
					</span>
					<span className={text({ role: "meta" })}>{item.blocked}</span>
				</span>
			) : (
				<span
					className={cn(text({ role: "body" }), menuLabel({ kind }), LABEL)}
				>
					{item.label}
				</span>
			)}
		</>
	);
}

function rowOf(item: MenuItem, highlighted: boolean): string {
	const blocked = item.blocked !== undefined;
	return cn(
		row({
			lines: blocked ? "two" : "one",
			state: highlighted ? "highlighted" : "rest",
		}),
		ITEM,
		!blocked && PRESS,
	);
}

// The touch sheet's rows, a menu the arrow keys move through.
const moveFocus = arrowsOver("menuitem");

function Groups(props: {
	items: readonly MenuItem[];
	item: (item: MenuItem) => ReactNode;
}) {
	return groupsOf(props.items).map((group) => (
		<div
			key={group.kind}
			className={cn(menuGroup({ kind: group.kind }), GROUP)}
		>
			{group.items.map(props.item)}
		</div>
	));
}

/** The more act and its acts: on the desktop a popover under the trigger, the keyboard's row under the hover wash; on touch a bottom sheet titled `label` with its close act, taking an act closing it first. A destructive act draws in danger ink, a blocked one inert with its reason under its label. */
export function Menu({ label, items }: MenuProps) {
	const touch = useTouch();
	const container = use(PortalContainer);
	const [open, setOpen] = useState(false);
	const [sheet] = useState(() => Dialog.createHandle<unknown>());
	if (touch) {
		return (
			<>
				<Dialog.Trigger
					handle={sheet}
					render={<IconButtonBase icon="Ellipsis" fit="body" label={label} />}
				/>
				<SheetBase
					form="menu"
					handle={sheet}
					open={open}
					onOpen={() => setOpen(true)}
					onClose={() => setOpen(false)}
					title={label}
				>
					<div
						role="menu"
						aria-label={label}
						onKeyDown={moveFocus}
						className={cn(menu({ form: "sheet" }), POPUP)}
					>
						<Groups
							items={items}
							item={(item) => (
								<button
									key={item.label}
									type="button"
									role="menuitem"
									aria-disabled={item.blocked !== undefined || undefined}
									onClick={() => {
										if (item.blocked !== undefined) return;
										setOpen(false);
										item.onAct();
									}}
									className={cn(rowOf(item, false), BUTTON)}
								>
									<ItemLine item={item} />
								</button>
							)}
						/>
					</div>
				</SheetBase>
			</>
		);
	}
	return (
		<Control.Root modal={false}>
			<Control.Trigger
				render={<IconButtonBase icon="Ellipsis" fit="bar" label={label} />}
			/>
			<Control.Portal container={container}>
				<Control.Positioner align="end" sideOffset={() => spacing("pair")}>
					<Control.Popup
						className={cn(
							POPOVER,
							menu({ form: "popover" }),
							POPUP,
							POPUP_MOTION,
						)}
					>
						<Groups
							items={items}
							item={(item) => (
								<Control.Item
									key={item.label}
									label={item.label}
									onClick={item.onAct}
									disabled={item.blocked !== undefined}
									className={(state) => rowOf(item, state.highlighted)}
								>
									<ItemLine item={item} />
								</Control.Item>
							)}
						/>
					</Control.Popup>
				</Control.Positioner>
			</Control.Portal>
		</Control.Root>
	);
}

// plugins/solid-ui/src/ui/lib/menu.tsx
import type { Act, IconAct, MenuItem } from "@fcalell/ui-core/descriptors";
import { GROUP, HAIRLINE, row, text } from "@fcalell/ui-core/variants";
import * as DropdownMenuPrimitive from "@kobalte/core/dropdown-menu";
import { Ellipsis } from "lucide-solid";
import { createSignal, For, Show } from "solid-js";
import { Dynamic } from "solid-js/web";
import { circle, glyph } from "#lib/circle.tsx";
import { cn } from "#lib/cn.ts";
import { useFit } from "#lib/fit.ts";
import { useIcon } from "#lib/icons.tsx";
import { RING_INSET, WASH } from "#lib/interact.ts";
import { Sheet } from "../components/sheet/index.tsx";

export type MenuItems = MenuItem<string>[] | MenuItem<string>[][];

// A flat list is one group; a list of lists is groups under separators.
export function groupsOf(items: MenuItems): MenuItem<string>[][] {
	if (items.length === 0) return [];
	return Array.isArray(items[0])
		? (items as MenuItem<string>[][])
		: [items as MenuItem<string>[]];
}

// A top bar's more circle holds the actions past its circles, each with its
// glyph, then the labelled `more` acts under a separator.
export function barItems(
	actions: IconAct<string>[],
	more: Act[],
): MenuItem<string>[][] {
	return [
		actions.map((action) => ({
			label: action.label,
			icon: action.icon,
			onAct: action.onAct,
		})),
		more.map((act) => ({
			label: act.label,
			onAct: act.onAct,
			blocked: act.blocked,
		})),
	].filter((group) => group.length > 0);
}

// Whether the viewport is at `breakpoints.tablet` or wider, read off a probe
// the stylesheet hides under it, so the width is the theme's own.
function fromTablet(): boolean {
	const probe = document.createElement("div");
	probe.className = "hidden tablet:block";
	document.body.append(probe);
	const wide = getComputedStyle(probe).display !== "none";
	probe.remove();
	return wide;
}

const ITEM = cn(
	row({ state: "rest" }),
	"flex w-full cursor-pointer items-center text-left outline-none transition-colors duration-(--duration-fast) ease-ui data-[disabled]:cursor-not-allowed",
	WASH,
	RING_INSET,
);

function ItemBody(props: { item: MenuItem<string> }) {
	return (
		<>
			<Show when={props.item.icon}>
				{(icon) => (
					<Dynamic
						component={useIcon(icon())}
						class="size-5 shrink-0 text-ink-meta"
						aria-hidden="true"
					/>
				)}
			</Show>
			<span class="flex min-w-0 flex-1 flex-col">
				<span
					class={cn(
						text({ role: "body" }),
						"truncate",
						props.item.destructive && "text-danger",
						props.item.blocked !== undefined && "text-ink-faint",
					)}
				>
					{props.item.label}
				</span>
				<Show when={props.item.blocked}>
					<span class={text({ role: "meta" })}>{props.item.blocked}</span>
				</Show>
			</span>
		</>
	);
}

// A more circle, `label` read aloud, opening its acts: anchored under the
// circle from tablet, a sheet titled `title` under it. Groups sit under
// hairlines, a destructive act in `danger`, a blocked one disabled with its
// reason under its label. The arrows move through the anchored list, Enter
// takes an act, Escape closes it, and focus goes back to the circle; opening
// one menu closes whatever else is open.
export function MenuCircle(props: {
	label: string;
	title: string;
	items: MenuItems;
}) {
	const fit = useFit();
	const [open, setOpen] = createSignal(false);
	const [anchored, setAnchored] = createSignal(true);
	const groups = () => groupsOf(props.items);
	return (
		<>
			<DropdownMenuPrimitive.Root
				open={open() && anchored()}
				onOpenChange={(next) => {
					if (next) setAnchored(fromTablet());
					setOpen(next);
				}}
				placement="bottom-end"
			>
				<DropdownMenuPrimitive.Trigger
					aria-label={props.label}
					class={circle(fit)}
				>
					<Ellipsis class={glyph(fit)} aria-hidden="true" />
				</DropdownMenuPrimitive.Trigger>
				<DropdownMenuPrimitive.Portal>
					<DropdownMenuPrimitive.Content
						class={cn(
							GROUP,
							"z-50 flex min-w-48 flex-col overflow-hidden bg-surface shadow-float outline-none animate-content-hide data-[expanded]:animate-content-show",
						)}
					>
						<For each={groups()}>
							{(group, at) => (
								<>
									<Show when={at() > 0}>
										<DropdownMenuPrimitive.Separator
											class={cn(HAIRLINE, "border-t")}
										/>
									</Show>
									<DropdownMenuPrimitive.Group class="flex flex-col">
										<For each={group}>
											{(item) => (
												<DropdownMenuPrimitive.Item
													disabled={item.blocked !== undefined}
													onSelect={() => item.onAct()}
													class={ITEM}
												>
													<ItemBody item={item} />
												</DropdownMenuPrimitive.Item>
											)}
										</For>
									</DropdownMenuPrimitive.Group>
								</>
							)}
						</For>
					</DropdownMenuPrimitive.Content>
				</DropdownMenuPrimitive.Portal>
			</DropdownMenuPrimitive.Root>
			<Sheet
				open={open() && !anchored()}
				onClose={() => setOpen(false)}
				title={props.title}
			>
				<For each={groups()}>
					{(group, at) => (
						<ul
							class={cn(
								"-mx-inset flex flex-col",
								at() > 0 && cn(HAIRLINE, "border-t"),
							)}
						>
							<For each={group}>
								{(item) => (
									<li>
										<button
											type="button"
											disabled={item.blocked !== undefined}
											onClick={() => {
												setOpen(false);
												item.onAct();
											}}
											class={ITEM}
										>
											<ItemBody item={item} />
										</button>
									</li>
								)}
							</For>
						</ul>
					)}
				</For>
			</Sheet>
		</>
	);
}
