// plugins/solid-ui/src/ui/components/sheet/index.tsx
import { SCRIM, SHEET, text } from "@fcalell/ui-core/variants";
import * as DialogPrimitive from "@kobalte/core/dialog";
import { ChevronLeft, X } from "lucide-solid";
import type { JSX } from "solid-js";
import { createEffect, createSignal, createUniqueId, Show } from "solid-js";
import { BarContext } from "#lib/bar.ts";
import { Circle } from "#lib/circle.tsx";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { FitContext } from "#lib/fit.ts";
import { RING_INSET, TEXT_ACT } from "#lib/interact.ts";
import { Inline } from "#lib/parts.tsx";
import { reachable } from "#lib/reach.ts";
import { TouchedContext } from "#lib/touched.ts";
import { useWords } from "#lib/words.tsx";

export interface SheetSubmit {
	label: string;
	onAct: () => void;
	blocked?: string;
}

// A sheet: a close circle left (a back circle with `back`), the title, and
// `submit` top right where a keyboard would cover a bar; a decision sheet
// puts an `ActionBar` in its children instead, and the two exclude each
// other. Content-tall from the bottom on the phone; centered at the sheet
// width from tablet. It opens with focus on its first field, else on its
// close circle, and gives focus back to what held it when it opened; the
// title wraps to two lines. A blocked submit says its reason once tapped or
// once a field has taken input.
export type SheetProps = Closed & {
	open: boolean;
	onClose: () => void;
	title: string;
	description?: string;
	back?: () => void;
	submit?: SheetSubmit;
	foot?: JSX.Element;
	children?: JSX.Element;
};

const FIELD = "input:not([type=hidden]), textarea";

export function Sheet(props: SheetProps) {
	const words = useWords();
	const reason = createUniqueId();
	let content: HTMLElement | undefined;
	const [touched, setTouched] = createSignal(false);
	const [tapped, setTapped] = createSignal(false);
	const blocked = () => props.submit?.blocked !== undefined;
	const said = () => blocked() && (tapped() || touched());
	// What held focus when the sheet opened, given it back on close.
	let opener: HTMLElement | undefined;
	createEffect(() => {
		if (props.open) {
			const active = document.activeElement;
			opener =
				active instanceof HTMLElement && active !== document.body
					? active
					: undefined;
			return;
		}
		setTouched(false);
		setTapped(false);
	});
	createEffect(() => {
		if (!blocked()) setTapped(false);
	});
	return (
		<DialogPrimitive.Root
			open={props.open}
			onOpenChange={(open) => {
				if (!open) props.onClose();
			}}
		>
			<DialogPrimitive.Portal>
				<DialogPrimitive.Overlay
					class={cn(
						SCRIM,
						"fixed inset-0 z-50 data-[expanded]:animate-in data-[closed]:animate-out data-[closed]:fade-out-0 data-[expanded]:fade-in-0",
					)}
				/>
				<div class="fixed inset-0 z-50 flex items-end justify-center tablet:items-center tablet:p-section">
					<DialogPrimitive.Content
						onInput={() => setTouched(true)}
						ref={content}
						onCloseAutoFocus={(event) => {
							if (!opener?.isConnected) return;
							event.preventDefault();
							opener.focus();
						}}
						onOpenAutoFocus={(event) => {
							const field = content?.querySelector<HTMLElement>(FIELD);
							if (!field) return;
							event.preventDefault();
							field.focus();
						}}
						class={cn(
							SHEET,
							"flex max-h-[90dvh] w-full flex-col overflow-hidden outline-none tablet:max-w-sheet tablet:shadow-sheet",
							"tablet:rounded-sheet",
						)}
					>
						<BarContext.Provider value="flow">
							<TouchedContext.Provider value={touched}>
								<FitContext.Provider value="bar">
									<header class="flex min-h-14 items-center gap-row px-inset">
										<Show
											when={props.back}
											fallback={
												<Circle
													glyph={X}
													label={words.close}
													onAct={props.onClose}
												/>
											}
										>
											{(back) => (
												<Circle
													glyph={ChevronLeft}
													label={words.back}
													onAct={back()}
												/>
											)}
										</Show>
										<DialogPrimitive.Title
											class={cn(
												text({ role: "heading" }),
												"line-clamp-2 min-w-0 flex-1",
											)}
										>
											<Inline text={props.title} />
										</DialogPrimitive.Title>
										<Show when={props.submit}>
											{(submit) => (
												<button
													type="button"
													aria-disabled={blocked() || undefined}
													aria-describedby={said() ? reason : undefined}
													onClick={() => {
														if (blocked()) setTapped(true);
														else submit().onAct();
													}}
													class={cn(
														text({ role: "body" }),
														"min-h-11 shrink-0 px-row",
														TEXT_ACT,
													)}
												>
													{submit().label}
												</button>
											)}
										</Show>
									</header>
								</FitContext.Provider>
								<Show when={said()}>
									<p
										id={reason}
										class={cn(text({ role: "meta" }), "px-inset text-right")}
									>
										{props.submit?.blocked}
									</p>
								</Show>
								<Show when={props.description}>
									<DialogPrimitive.Description
										class={cn(text({ role: "meta" }), "px-inset pb-stack")}
									>
										{props.description}
									</DialogPrimitive.Description>
								</Show>
								<div
									ref={reachable}
									class={cn(
										"flex min-h-0 flex-1 flex-col gap-stack overflow-y-auto px-inset pb-[max(env(safe-area-inset-bottom),var(--spacing-inset))] *:shrink-0",
										RING_INSET,
									)}
								>
									{props.children}
								</div>
								<Show when={props.foot}>
									<div class="px-inset pb-[max(env(safe-area-inset-bottom),var(--spacing-inset))]">
										{props.foot}
									</div>
								</Show>
							</TouchedContext.Provider>
						</BarContext.Provider>
					</DialogPrimitive.Content>
				</div>
			</DialogPrimitive.Portal>
		</DialogPrimitive.Root>
	);
}

// plugins/native-ui/src/ui/components/sheet/index.tsx
import { SHEET, text } from "@fcalell/ui-core/variants";
import { BottomSheetModal, BottomSheetView } from "@gorhom/bottom-sheet";
import { ChevronLeft, X } from "lucide-react-native";
import {
	createContext,
	type ReactNode,
	useCallback,
	useContext,
	useEffect,
	useMemo,
	useRef,
	useState,
} from "react";
import { Pressable, Text as RNText, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Circle } from "../../lib/circle";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { TouchedContext } from "../../lib/touched";
import { useWords } from "../../lib/words";

export interface SheetSubmit {
	label: string;
	blocked?: string;
	onAct: () => void;
	loading?: boolean;
}

interface SheetBase extends Closed {
	open: boolean;
	onClose: () => void;
	title: string;
	description?: string;
	back?: () => void;
	foot?: ReactNode;
	children?: ReactNode;
}

// `submit` (top right, where a keyboard would cover a bar) and an ActionBar
// child exclude each other: a sheet with text entry submits from its top bar,
// a decision sheet takes the bar. The union names the two shapes; which
// children a sheet holds is the consumer's side of it.
export type SheetProps =
	| (SheetBase & { submit: SheetSubmit })
	| (SheetBase & { submit?: never });

// A TextArea inside asks the sheet for the full height.
const GrowContext = createContext<(() => void) | undefined>(undefined);

export function useSheetGrow(): (() => void) | undefined {
	return useContext(GrowContext);
}

const FULL = ["100%"];
const TRANSPARENT = { backgroundColor: "transparent" } as const;

// Content-tall, full height when it holds a TextArea, the sheet corners; a
// close circle left, the title, submit right, the foot under the children.
export function Sheet({
	open,
	onClose,
	title,
	description,
	back,
	foot,
	children,
	...rest
}: SheetProps) {
	const words = useWords();
	const insets = useSafeAreaInsets();
	const ref = useRef<BottomSheetModal>(null);
	const [tall, setTall] = useState(false);
	const [touched, setTouched] = useState(false);
	const grow = useCallback(() => setTall(true), []);
	const touch = useCallback(() => setTouched(true), []);
	const submit = "submit" in rest ? rest.submit : undefined;
	useEffect(() => {
		if (open) ref.current?.present();
		else {
			ref.current?.dismiss();
			setTouched(false);
		}
	}, [open]);
	const snapPoints = useMemo(() => (tall ? FULL : undefined), [tall]);
	return (
		<BottomSheetModal
			ref={ref}
			onDismiss={onClose}
			backgroundStyle={TRANSPARENT}
			handleComponent={null}
			enableDynamicSizing={!tall}
			snapPoints={snapPoints}
		>
			<BottomSheetView>
				<GrowContext.Provider value={grow}>
					<TouchedContext.Provider value={{ touched, touch }}>
						<View
							style={{ paddingBottom: insets.bottom + 8 }}
							className={cn(SHEET, "gap-stack px-inset pt-stack shadow-sheet")}
						>
							<View className="min-h-11 flex-row items-center gap-row">
								{back ? (
									<Circle icon={ChevronLeft} label={words.back} onAct={back} />
								) : (
									<Circle icon={X} label={words.close} onAct={onClose} />
								)}
								<RNText
									numberOfLines={1}
									className={cn(text({ role: "heading" }), "flex-1")}
								>
									{title}
								</RNText>
								{submit ? (
									<SubmitAct submit={submit} touched={touched} />
								) : null}
							</View>
							{description ? (
								<RNText className={text({ role: "meta" })}>
									{description}
								</RNText>
							) : null}
							{children}
							{foot}
						</View>
					</TouchedContext.Provider>
				</GrowContext.Provider>
			</BottomSheetView>
		</BottomSheetModal>
	);
}

// A blocked submit says its reason under it once pressed or once a field in
// the sheet has taken input.
function SubmitAct({
	submit,
	touched,
}: {
	submit: SheetSubmit;
	touched: boolean;
}) {
	const blocked = submit.blocked !== undefined;
	const muted = blocked || submit.loading;
	const [pressed, setPressed] = useState(false);
	useEffect(() => {
		if (!blocked) setPressed(false);
	}, [blocked]);
	const said = blocked && (pressed || touched);
	return (
		<View className="items-end gap-pair">
			<Pressable
				accessibilityRole="button"
				accessibilityState={{ disabled: muted }}
				accessibilityHint={said ? submit.blocked : undefined}
				disabled={submit.loading}
				onPress={() => (blocked ? setPressed(true) : submit.onAct())}
				className="min-h-11 justify-center"
			>
				<RNText
					className={cn(
						text({ role: "body" }),
						"font-medium text-tint",
						muted && "text-ink-faint",
					)}
				>
					{submit.label}
				</RNText>
			</Pressable>
			{said ? (
				<RNText className={text({ role: "meta" })}>{submit.blocked}</RNText>
			) : null}
		</View>
	);
}
