// plugins/solid-ui/src/ui/components/pending-bar/index.tsx
import type { Act } from "@fcalell/ui-core/descriptors";
import type { SpinnerKind } from "@fcalell/ui-core/tokens";
import { PENDING_BAR, PENDING_FILL, text } from "@fcalell/ui-core/variants";
import { createSignal, onCleanup, onMount, Show } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { TEXT_ACT } from "#lib/interact.ts";
import { Spinner } from "../spinner/index.tsx";

// One line with a spinner, or a countdown that fills the bar toward a server
// deadline, and one act. Placed in an `ActionBar`'s place, a `Sheet`'s foot,
// above a message input, or as a row of a thread.
export type PendingBarProps = Closed & {
	sentence: string;
	until?: Date;
	// The busy glyph drawn while no deadline is set.
	spinner?: SpinnerKind;
	act?: Act;
};

const TICK_MS = 250;

export function PendingBar(props: PendingBarProps) {
	const started = Date.now();
	const [now, setNow] = createSignal(started);
	onMount(() => {
		const timer = setInterval(() => setNow(Date.now()), TICK_MS);
		onCleanup(() => clearInterval(timer));
	});
	const progress = () => {
		const until = props.until;
		if (!until) return 0;
		const total = until.getTime() - started;
		if (total <= 0) return 1;
		return Math.min(1, (now() - started) / total);
	};
	return (
		<div
			role="status"
			class={cn(PENDING_BAR, "relative flex items-center overflow-hidden")}
		>
			<Show when={props.until}>
				<div
					class={cn(PENDING_FILL, "absolute inset-y-0 left-0")}
					style={{ width: `${progress() * 100}%` }}
					aria-hidden="true"
				/>
			</Show>
			<span class="relative flex min-w-0 flex-1 items-center gap-row">
				<Show when={!props.until}>
					<Spinner kind={props.spinner} />
				</Show>
				<span class={cn(text({ role: "meta" }), "truncate text-ink")}>
					{props.sentence}
				</span>
			</span>
			<Show when={props.act}>
				{(act) => (
					<button
						type="button"
						disabled={act().blocked !== undefined}
						onClick={() => act().onAct()}
						class={cn(
							text({ role: "meta" }),
							"relative -mr-inset min-h-11 shrink-0 self-stretch px-inset",
							TEXT_ACT,
						)}
					>
						{act().label}
					</button>
				)}
			</Show>
		</div>
	);
}

// plugins/native-ui/src/ui/components/pending-bar/index.tsx
import type { Act } from "@fcalell/ui-core/descriptors";
import type { SpinnerKind } from "@fcalell/ui-core/tokens";
import { PENDING_BAR, PENDING_FILL, text } from "@fcalell/ui-core/variants";
import { useEffect, useState } from "react";
import { Pressable, Text as RNText, View } from "react-native";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { Spinner } from "../spinner";

export interface PendingBarProps extends Closed {
	sentence: string;
	until?: Date;
	// The busy glyph drawn while no deadline is set.
	spinner?: SpinnerKind;
	act?: Act;
}

const TICK_MS = 250;

// One line with a spinner, or a countdown that fills the bar toward `until`,
// and one act.
export function PendingBar({ sentence, until, spinner, act }: PendingBarProps) {
	const [now, setNow] = useState(() => Date.now());
	const [width, setWidth] = useState(0);
	const [start] = useState(() => Date.now());
	useEffect(() => {
		if (!until) return;
		const timer = setInterval(() => setNow(Date.now()), TICK_MS);
		return () => clearInterval(timer);
	}, [until]);
	const total = until ? until.getTime() - start : 0;
	const ratio = until && total > 0 ? Math.min(1, (now - start) / total) : 0;
	return (
		<View
			accessibilityRole="progressbar"
			accessibilityValue={until ? { min: 0, max: 1, now: ratio } : undefined}
			onLayout={(event) => setWidth(event.nativeEvent.layout.width)}
			className={cn(PENDING_BAR, "flex-row items-center overflow-hidden")}
		>
			{until ? (
				<View
					className={cn(PENDING_FILL, "absolute inset-y-0 left-0")}
					style={{ width: ratio * width }}
				/>
			) : (
				<Spinner kind={spinner} />
			)}
			<RNText className={cn(text({ role: "meta" }), "flex-1 text-ink")}>
				{sentence}
			</RNText>
			{act ? (
				<Pressable
					accessibilityRole="button"
					disabled={act.blocked !== undefined}
					onPress={act.onAct}
					className="min-h-11 justify-center"
				>
					<RNText
						className={cn(text({ role: "body" }), "font-medium text-tint")}
					>
						{act.label}
					</RNText>
				</Pressable>
			) : null}
		</View>
	);
}
