// plugins/native-ui/src/ui/components/split/index.tsx
import type { ReactNode } from "react";
import type { Closed } from "../../lib/closed";

export interface SplitProps extends Closed {
	list?: ReactNode;
	main?: ReactNode;
	pane?: ReactNode;
	empty?: ReactNode;
}

// The desktop's columns; the phone sees one slot at a time, the deepest
// present, so a screen pushes over its list. `empty` is the desktop's, so
// the phone never draws it.
export function Split({ list, main, pane }: SplitProps) {
	return <>{pane ?? main ?? list ?? null}</>;
}

// plugins/solid-ui/src/ui/components/split/index.tsx
import type { JSX } from "solid-js";
import { Show } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";

// The desktop's columns, composed per place by the consumer: `list` at the
// list width, `main` filling, `pane` beside them from wide and pushing over
// `main` under it. Under desktop one slot at a time, the deepest present, so
// the phone sees a stack of screens. `empty` fills `main`'s column from
// desktop while neither `main` nor `pane` is present ("Pick an item."); under
// desktop the list is the place, so it never draws.
export type SplitProps = Closed & {
	list?: JSX.Element;
	main?: JSX.Element;
	pane?: JSX.Element;
	empty?: JSX.Element;
};

export function Split(props: SplitProps) {
	const hasMain = () => props.main !== undefined;
	const hasPane = () => props.pane !== undefined;
	return (
		<div class="flex min-h-0 flex-1">
			<Show when={props.list}>
				<div
					class={cn(
						"min-h-0 min-w-0 flex-col desktop:flex desktop:w-list desktop:shrink-0 desktop:border-r",
						hasMain() || hasPane() ? "hidden" : "flex flex-1",
					)}
				>
					{props.list}
				</div>
			</Show>
			<Show when={props.empty && !hasMain() && !hasPane()}>
				<div class="hidden min-h-0 min-w-0 flex-1 flex-col desktop:flex">
					{props.empty}
				</div>
			</Show>
			<Show when={props.main}>
				<div
					class={cn(
						"min-h-0 min-w-0 flex-1 flex-col",
						hasPane() ? "hidden wide:flex" : "flex",
					)}
				>
					{props.main}
				</div>
			</Show>
			<Show when={props.pane}>
				<div class="flex min-h-0 min-w-0 flex-1 flex-col wide:w-list wide:flex-none wide:border-l">
					{props.pane}
				</div>
			</Show>
		</div>
	);
}
