// plugins/solid-ui/src/ui/components/message/index.tsx
import { type MessageAuthor, message, text } from "@fcalell/ui-core/variants";
import { Show } from "solid-js";
import { ageOf, momentOf, useClock } from "#lib/age.ts";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { RING } from "#lib/interact.ts";
import { LoadingRows } from "#lib/loading.tsx";
import { Prose } from "../prose/index.tsx";

// One message of a thread: `you` in a soft bubble right, `other` as prose on
// the surface with the name above when given, `system` as one centered meta
// line. The body streams.
export type MessageProps = Closed & {
	author: MessageAuthor;
	name?: string;
	body: string;
	// An ISO moment, drawn as its age.
	at?: string;
	// A system line that opens something, such as a relay's provenance: the
	// line becomes the act.
	onOpen?: () => void;
	loading?: boolean;
};

export function Message(props: MessageProps) {
	const clock = useClock();
	return (
		<Show when={!props.loading} fallback={<LoadingRows />}>
			<article
				class={cn(
					"flex flex-col gap-pair",
					props.author === "you" && "items-end",
					props.author === "system" && "items-center",
				)}
			>
				<Show when={props.author === "other" && props.name}>
					<p class={text({ role: "label" })}>{props.name}</p>
				</Show>
				<div
					class={cn(
						message({ author: props.author }),
						props.author === "you" && "max-w-[85%]",
						props.author === "system" && "text-center",
					)}
				>
					<Show
						when={props.author === "other"}
						fallback={
							<Show when={props.onOpen} fallback={<span>{props.body}</span>}>
								<button
									type="button"
									onClick={() => props.onOpen?.()}
									class={cn("min-h-11 cursor-pointer rounded-group", RING)}
								>
									{props.body}
								</button>
							</Show>
						}
					>
						<Prose markdown={props.body} />
					</Show>
				</div>
				<Show when={props.at}>
					{(at) => (
						<time
							datetime={at()}
							title={momentOf(at())}
							class={cn(text({ role: "meta" }), "tabular-nums")}
						>
							{ageOf(at(), clock())}
						</time>
					)}
				</Show>
			</article>
		</Show>
	);
}

// plugins/native-ui/src/ui/components/message/index.tsx
import type { MessageAuthor } from "@fcalell/ui-core/variants";
import { message, text } from "@fcalell/ui-core/variants";
import { Pressable, Text as RNText, View } from "react-native";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { LoadingRows } from "../../lib/loading";
import { Prose } from "../prose";

export interface MessageProps extends Closed {
	author: MessageAuthor;
	name?: string;
	body: string;
	at?: string;
	// A system line that opens something, such as a relay's provenance: the
	// line becomes the act.
	onOpen?: () => void;
	loading?: boolean;
}

// `you` in a soft bubble right, `other` as prose on the surface with the name
// above, `system` as one centered meta line. The body streams.
export function Message({
	author,
	name,
	body,
	at,
	onOpen,
	loading,
}: MessageProps) {
	if (loading) return <LoadingRows />;
	if (author === "system") {
		const line = (
			<RNText className={cn(message({ author }), "text-center")}>{body}</RNText>
		);
		return onOpen ? (
			<Pressable
				accessibilityRole="button"
				onPress={onOpen}
				className="min-h-11 justify-center"
			>
				{line}
			</Pressable>
		) : (
			line
		);
	}
	return (
		<View
			className={cn(
				"gap-pair",
				author === "you" ? "items-end" : "items-stretch",
			)}
		>
			{author === "other" && name ? (
				<RNText className={text({ role: "label" })}>{name}</RNText>
			) : null}
			<View
				className={cn(message({ author }), author === "you" && "max-w-full")}
			>
				{author === "you" ? (
					<RNText className={text({ role: "body" })}>{body}</RNText>
				) : (
					<Prose markdown={body} />
				)}
			</View>
			{at ? <RNText className={text({ role: "meta" })}>{at}</RNText> : null}
		</View>
	);
}
