// plugins/native-ui/src/ui/components/stack/index.tsx
import { rhythm } from "@fcalell/ui-core/variants";
import type { ReactNode } from "react";
import { View } from "react-native";

export interface StackProps {
	children?: ReactNode;
	className?: never;
	style?: never;
}

// A column of stacked units, gapped at the stack rung. RN lays out as a
// column by default, so the shared RHYTHM cell is the whole look.
export function Stack({ children }: StackProps) {
	return <View className={rhythm({ unit: "stack" })}>{children}</View>;
}

// plugins/solid-ui/src/ui/components/stack/index.tsx
import { rhythm } from "@fcalell/ui-core/variants";
import type { JSX } from "solid-js";
import { cn } from "#lib/cn";

type StackProps = {
	children?: JSX.Element;
	class?: never;
	style?: never;
	classList?: never;
};

// A column of stacked units, gapped at the stack rung. Display and direction
// are the web overlay; the gap is the shared RHYTHM cell.
function Stack(props: StackProps) {
	return (
		<div class={cn(rhythm({ unit: "stack" }), "flex flex-col")}>
			{props.children}
		</div>
	);
}

export type { StackProps };
export { Stack };
