// plugins/native-ui/src/ui/components/table/index.tsx
import type {
	CellValue,
	Option,
	StatusCell,
	TableCell,
	TableColumn,
	TableRowSlots,
} from "@fcalell/ui-core/descriptors";
import {
	listState,
	retryOf,
	type TableRecord,
	tableRecords,
} from "@fcalell/ui-core/list-state";
import { BREAKPOINT_PX } from "@fcalell/ui-core/tokens";
import {
	FIGURES,
	skeleton,
	TABLE_CELL,
	TABLE_EMPTY,
	TABLE_FRAME,
	TABLE_FROZEN,
	type TableRowState,
	tableFrozenCell,
	tableHead,
	tableHeadLabel,
	tableRow,
	text,
	textStrong,
} from "@fcalell/ui-core/variants";
import {
	memo,
	type ReactNode,
	useContext,
	useMemo,
	useRef,
	useState,
	useSyncExternalStore,
} from "react";
import {
	Pressable,
	Text as RNText,
	ScrollView,
	useWindowDimensions,
	View,
} from "react-native";
import { age } from "../../lib/age";
import { useClock } from "../../lib/clock";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { CellField, LabelTarget } from "../../lib/field";
import { Ink } from "../../lib/ink";
import { LoadingContext } from "../../lib/loading";
import { navigate } from "../../lib/navigate";
import { SectionContext } from "../../lib/section";
import { useWords } from "../../lib/words";
import { Checkbox } from "../checkbox";
import { Chip } from "../chip";
import { EmptyStateBase } from "../empty-state/base";
import { Missing } from "../empty-state/missing";
import { Icon } from "../icon";
import { Input } from "../input";
import { List, type RowSlots } from "../list";
import { PickerBase } from "../picker/base";
import type { QueryLike } from "../query-boundary";
import { StatusBase } from "../status/base";

const ROOT = "grow";
// The frozen leading column stands outside the sideways scroll, on the
// surface, so the cells scroll beneath its hairline: React Native has no
// sticky cell, and the two halves of a row share its height because every
// cell holds one line at the row's height.
const FRAME = "flex-row";
const FROZEN_COLUMN = "shrink-0 w-measure-short";
const SCROLLS = "grow";
const ROW_LINE = "flex-row";
// On touch every column stands at one width.
const COLUMN = "w-measure-short";
// A sortable header washes under the press through the Pressable's own
// pressed state.
const SORT = "flex-row items-center w-full min-w-0 active:bg-wash-press";
const HEAD = "flex-row items-center min-w-0";
const LABEL = "shrink";
const GLYPH = "shrink-0";
const CELL = "flex-row items-center min-w-0";
const CELL_END = "justify-end";
const VALUE = "shrink";
const TICK = "shrink-0";
// A Chip hugs its top edge in a row, so it stands centred in a slot of its own.
const CHIP = "shrink min-w-0";
// An edit fills the cell it stands in.
const EDIT = "grow min-w-0";
// The empty slot spans the grid: a framed EmptyState stands across it, an
// unframed one centres in what the page's body leaves.
const EMPTY = "grow";
const SORT_BAR = "flex-row items-center justify-end";

// Five loading rows, each bar at a share of its cell: a number's at a
// quarter, the others by row and by their place among the bars.
const LOADING_BARS = [
	["w-2/3", "w-1/2", "w-1/3", "w-1/2", "w-1/2"],
	["w-1/2", "w-2/3", "w-1/2", "w-1/3", "w-2/3"],
	["w-3/4", "w-1/2", "w-1/3", "w-1/2", "w-1/3"],
	["w-1/2", "w-1/3", "w-1/2", "w-1/3", "w-1/2"],
	["w-2/3", "w-1/2", "w-1/3", "w-1/2", "w-2/3"],
] as const;
const NUMBER_BAR = "w-1/4";

type Direction = "descending" | "ascending";
interface Sort {
	key: string;
	direction: Direction;
}

// Where a table's records come from: a query, with what failed to load over
// the retry act, or items, `loading` while they are on their way.
type TableSource<T> =
	| {
			query: QueryLike<readonly T[]>;
			sentence: string;
			items?: never;
			loading?: never;
	  }
	| {
			items: readonly T[];
			loading?: boolean;
			query?: never;
			sentence?: never;
	  };

// The columns each read their cell from the item, and `row` the row's own
// slots.
interface TableBase<T> extends Closed {
	columns: readonly TableColumn<T>[];
	row: TableRowSlots<T>;
	selected?: string;
	empty?: ReactNode;
}

interface Reads {
	onOpen?: (id: string) => void;
	onEdit?: never;
}

interface Edits {
	onOpen: (id: string) => void;
	// One committed edit of a cell whose column edits; below `tablet` the
	// record `onOpen` shows edits it.
	onEdit?: (id: string, key: string, value: CellValue) => void;
}

export type TableProps<T = unknown> = TableBase<T> &
	TableSource<T> &
	(Reads | Edits);

function optionsOf(column: TableColumn): readonly Option<string | null>[] {
	if (column.edit?.control !== "picker") return [];
	return column.edit.options.flatMap((entry) =>
		"options" in entry ? entry.options : [entry],
	);
}

// What a cell reads as: a picked value its option's label, a status its word,
// an age its distance from now.
function shown(column: TableColumn, cell: TableCell | undefined): string {
	if (cell === null || cell === undefined || typeof cell === "boolean")
		return "";
	if (typeof cell === "object") return cell.label ?? "";
	if (column.kind === "age") return age(String(cell));
	const option = optionsOf(column).find((o) => o.value === cell);
	return option?.label ?? String(cell);
}

function order(
	column: TableColumn,
	cell: TableCell | undefined,
): number | string {
	if (cell === null || cell === undefined) return "";
	if (typeof cell === "boolean") return cell ? 1 : 0;
	if (typeof cell === "number") return cell;
	if (typeof cell === "object") return cell.label ?? cell.status;
	if (column.kind === "age") return Date.parse(cell);
	return shown(column, cell);
}

// Rows by the sorted column, an empty cell last either way.
function sorted(
	rows: readonly TableRecord[],
	columns: readonly TableColumn[],
	sort: Sort | undefined,
): readonly TableRecord[] {
	const column = columns.find((c) => c.key === sort?.key);
	if (!sort || !column) return rows;
	const sign = sort.direction === "ascending" ? 1 : -1;
	return [...rows].sort((a, b) => {
		const x = order(column, a.cells[column.key]);
		const y = order(column, b.cells[column.key]);
		if (x === "" || y === "") return x === y ? 0 : x === "" ? 1 : -1;
		if (typeof x === "number" && typeof y === "number") return (x - y) * sign;
		return (
			String(x).localeCompare(String(y), undefined, { numeric: true }) * sign
		);
	});
}

// A header pressed again turns its sort over, then off; another column sorts
// newest or largest first.
function next(sort: Sort | undefined, key: string): Sort | undefined {
	if (sort?.key !== key) return { key, direction: "descending" };
	return sort.direction === "descending"
		? { key, direction: "ascending" }
		: undefined;
}

const isEnd = (column: TableColumn) =>
	(column.align ?? (column.kind === "number" ? "end" : "start")) === "end";

// From `tablet` of the window a grid: a header of sort acts over one row per
// record, every column at the short measure, scrolling sideways under its
// frozen leading column; a press on a row opens it, a press on an editable
// value edits it in place (typed in an `Input`, picked in a `Picker`'s
// sheet, ticked in a `Checkbox`). Below `tablet` one `ListRow` per record
// under the sort's pick. The table sorts in its own state: newest or largest
// first, then turned over, then off. It draws its four states: while its
// query is pending, `loading` is set or a loading Section around it waits,
// the header over skeleton rows (below `tablet` the list's waiting rows; a
// Section around busy, its count waiting); a query that answers not found
// the rest EmptyState saying it no longer exists with Back, never Retry, and
// a failed query the failed EmptyState with `sentence` and Retry, each under
// the header on the grid and alone below `tablet`; no row `empty`; then one row per item, which a
// Section around counts.
export function Table<T>(props: TableProps<T>) {
	const { columns, selected, onOpen, onEdit, empty } = props;
	const words = useWords();
	const [sort, setSort] = useState<Sort>();
	const { width } = useWindowDimensions();
	const base = {
		query: props.query,
		items: props.items,
		loading: props.loading,
		sectionLoading: useContext(LoadingContext),
		inSection: false,
		hasEmpty: empty !== undefined,
	};
	const input = { ...base, inSection: useContext(SectionContext) };
	const state = listState(input);
	const waiting = state === "pending";
	const items = (props.query ? props.query.data : props.items) ?? [];
	const records = waiting
		? []
		: sorted(tableRecords(items, columns, props.row), columns, sort);
	let slot: ReactNode = null;
	if (state === "missing") slot = <Missing />;
	else if (state === "failed" && props.query)
		slot = (
			<EmptyStateBase
				tone="failed"
				sentence={props.sentence}
				act={{ label: words.retry, onAct: retryOf(props.query) }}
			/>
		);
	else if (state === "empty") slot = empty;
	if (width < BREAKPOINT_PX.tablet)
		return (
			<View className={ROOT}>
				{slot ?? (
					// The Table reports to the Section around it once; its List is
					// its own part, not a list of the Section.
					<SectionContext.Provider value={false}>
						<Phone
							columns={columns}
							rows={records}
							sort={sort}
							onSort={setSort}
							onOpen={onOpen}
							loading={waiting}
						/>
					</SectionContext.Provider>
				)}
			</View>
		);
	return (
		<View className={ROOT}>
			<Grid
				columns={columns}
				rows={records}
				sort={sort}
				onSort={(key) => setSort((current) => next(current, key))}
				selected={selected}
				onOpen={onOpen}
				onEdit={onEdit}
				loading={waiting}
			/>
			{slot === null ? null : (
				<View className={cn(TABLE_EMPTY, EMPTY)}>{slot}</View>
			)}
		</View>
	);
}

interface Editing {
	row: string;
	key: string;
}

// What a row calls back into the grid: one object for the grid's life,
// reading the grid's latest render, so a memoised row never re-renders for a
// new callback.
interface GridActions {
	open: (row: TableRecord) => void;
	start: (row: string, key: string) => void;
	done: () => void;
	edit: (row: string, key: string, value: CellValue) => void;
}

// The pressed row's id. A row's two halves (its frozen leading cell and the
// cells that scroll) wash together, so they read one store, each row only
// whether it is the pressed one: a touch re-renders the row it lands on.
interface PressStore {
	get: () => string | undefined;
	set: (id: string | undefined) => void;
	subscribe: (listener: () => void) => () => void;
}

function pressStore(): PressStore {
	let pressed: string | undefined;
	const listeners = new Set<() => void>();
	return {
		get: () => pressed,
		set: (id) => {
			pressed = id;
			for (const listener of listeners) listener();
		},
		subscribe: (listener) => {
			listeners.add(listener);
			return () => listeners.delete(listener);
		},
	};
}

// What a row's half draws as: pressed, the open record, or at rest.
function useRowState(
	store: PressStore,
	id: string,
	chosen: boolean,
): TableRowState {
	const pressed = useSyncExternalStore(
		store.subscribe,
		() => store.get() === id,
	);
	if (pressed) return "pressed";
	return chosen ? "selected" : "rest";
}

// A row that opens takes the press; one that does not is inert.
function pressOf(
	row: TableRecord,
	opens: boolean,
	store: PressStore,
	actions: GridActions,
) {
	return opens
		? {
				onPress: () => actions.open(row),
				onPressIn: () => store.set(row.id),
				onPressOut: () => store.set(undefined),
			}
		: { disabled: true };
}

// The frozen half of a row: its leading cell, the record's name.
const LeadRow = memo(function LeadRow(props: {
	row: TableRecord;
	lead: TableColumn;
	name: string;
	chosen: boolean;
	opens: boolean;
	link: boolean;
	store: PressStore;
	actions: GridActions;
}) {
	const { row, lead, name, chosen, opens, store, actions } = props;
	const state = useRowState(store, row.id, chosen);
	let role: "link" | "button" | undefined;
	if (opens) role = props.link ? "link" : "button";
	return (
		<Pressable
			accessibilityRole={role}
			accessibilityLabel={name}
			accessibilityState={{ selected: chosen }}
			{...pressOf(row, opens, store, actions)}
			className={cn(tableRow({ state: "rest" }), TABLE_FROZEN)}
		>
			<View
				className={cn(
					TABLE_CELL,
					CELL,
					isEnd(lead) && CELL_END,
					tableFrozenCell({ state }),
				)}
			>
				<RNText
					numberOfLines={1}
					className={cn(
						text({ role: "body" }),
						textStrong({ role: "body" }),
						VALUE,
					)}
				>
					{name}
				</RNText>
			</View>
		</Pressable>
	);
});

// The half of a row that scrolls: the cells past the leading one.
const RestRow = memo(function RestRow(props: {
	row: TableRecord;
	columns: readonly TableColumn[];
	name: string;
	chosen: boolean;
	opens: boolean;
	edits: boolean;
	// The key of the column this row edits, if any.
	editing: string | undefined;
	store: PressStore;
	actions: GridActions;
}) {
	const { row, columns, name, chosen, opens, store, actions } = props;
	const state = useRowState(store, row.id, chosen);
	return (
		<Pressable
			accessible={false}
			{...pressOf(row, opens, store, actions)}
			className={cn(tableRow({ state }), ROW_LINE)}
		>
			{columns.map((column) => (
				<View key={column.key} className={COLUMN}>
					<Cell
						row={row}
						column={column}
						name={name}
						edits={props.edits}
						editing={props.editing === column.key}
						actions={actions}
					/>
				</View>
			))}
		</Pressable>
	);
});

// A cell past the leading one, by whether and how its column edits (the
// leading column never edits, nor a column its row locks).
function Cell(props: {
	row: TableRecord;
	column: TableColumn;
	name: string;
	edits: boolean;
	editing: boolean;
	actions: GridActions;
}) {
	const { row, column, actions } = props;
	const value = row.cells[column.key];
	const control =
		props.edits && !row.locked?.includes(column.key)
			? column.edit?.control
			: undefined;
	const label = `${column.label}, ${props.name}`;
	const box = cn(TABLE_CELL, CELL, isEnd(column) && CELL_END);
	const edit = (next: CellValue) => actions.edit(row.id, column.key, next);
	if (control === "checkbox")
		return (
			<Pressable
				accessibilityRole="checkbox"
				accessibilityLabel={label}
				accessibilityState={{ checked: value === true }}
				onPress={() => edit(value !== true)}
				className={box}
			>
				<LabelTarget.Provider value>
					<Checkbox checked={value === true} onChange={edit} label={label} />
				</LabelTarget.Provider>
			</Pressable>
		);
	if (control && props.editing)
		return (
			<View className={box}>
				<View className={EDIT}>
					<CellField.Provider value={{ label, done: actions.done }}>
						<CellEdit column={column} cell={value} onEdit={edit} />
					</CellField.Provider>
				</View>
			</View>
		);
	if (control)
		return (
			<Pressable
				accessibilityRole="button"
				accessibilityLabel={label}
				accessibilityValue={{ text: shown(column, value) }}
				onPress={() => actions.start(row.id, column.key)}
				className={box}
			>
				<CellValueView column={column} cell={value} />
			</Pressable>
		);
	return (
		<View className={box}>
			<CellValueView column={column} cell={value} />
		</View>
	);
}

function Grid(props: {
	columns: readonly TableColumn[];
	rows: readonly TableRecord[];
	sort: Sort | undefined;
	onSort: (key: string) => void;
	selected: string | undefined;
	onOpen: ((id: string) => void) | undefined;
	onEdit: ((id: string, key: string, value: CellValue) => void) | undefined;
	loading: boolean | undefined;
}) {
	const { columns, rows, sort } = props;
	const lead = columns[0];
	const rest = useMemo(() => columns.slice(1), [columns]);
	const [store] = useState(pressStore);
	const [editing, setEditing] = useState<Editing>();
	const edits = props.onEdit !== undefined;
	const opens = (row: TableRecord) =>
		props.onOpen !== undefined || row.href !== undefined;
	const name = (row: TableRecord) =>
		lead ? shown(lead, row.cells[lead.key]) : row.id;
	const latest = useRef(props);
	latest.current = props;
	const [actions] = useState<GridActions>(() => ({
		open: (row) => {
			const { onOpen } = latest.current;
			if (onOpen) onOpen(row.id);
			else if (row.href !== undefined) navigate(row.href);
		},
		start: (row, key) => setEditing({ row, key }),
		done: () => setEditing(undefined),
		edit: (row, key, value) => latest.current.onEdit?.(row, key, value),
	}));

	return (
		<View
			accessibilityState={{ busy: props.loading === true }}
			className={cn(TABLE_FRAME, FRAME)}
		>
			{lead ? (
				<View className={FROZEN_COLUMN}>
					<View className={cn(tableRow({ state: "rest" }), TABLE_FROZEN)}>
						<HeadCell
							column={lead}
							sort={sort}
							frozen
							onSort={() => props.onSort(lead.key)}
						/>
					</View>
					{props.loading
						? LOADING_BARS.map((bars, index) => (
								<View
									key={bars.join(" ") + String(index)}
									className={cn(tableRow({ state: "rest" }), TABLE_FROZEN)}
								>
									<View
										className={cn(
											TABLE_CELL,
											CELL,
											isEnd(lead) && CELL_END,
											tableFrozenCell({ state: "rest" }),
										)}
									>
										{waits(columns, bars, index % 2 === 1)[0]}
									</View>
								</View>
							))
						: rows.map((row) => (
								<LeadRow
									key={row.id}
									row={row}
									lead={lead}
									name={name(row)}
									chosen={row.id === props.selected}
									opens={opens(row)}
									link={props.onOpen === undefined}
									store={store}
									actions={actions}
								/>
							))}
				</View>
			) : null}
			<ScrollView
				horizontal
				showsHorizontalScrollIndicator={false}
				className={SCROLLS}
			>
				<View>
					<View className={cn(tableRow({ state: "rest" }), ROW_LINE)}>
						{rest.map((column) => (
							<View key={column.key} className={COLUMN}>
								<HeadCell
									column={column}
									sort={sort}
									frozen={false}
									onSort={() => props.onSort(column.key)}
								/>
							</View>
						))}
					</View>
					{props.loading
						? LOADING_BARS.map((bars, index) => (
								<View
									key={bars.join(" ") + String(index)}
									className={cn(tableRow({ state: "rest" }), ROW_LINE)}
								>
									{waits(columns, bars, index % 2 === 1)
										.slice(1)
										.map((wait, place) => {
											const column = rest[place];
											return column ? (
												<View
													key={column.key}
													className={cn(
														COLUMN,
														TABLE_CELL,
														CELL,
														isEnd(column) && CELL_END,
													)}
												>
													{wait}
												</View>
											) : null;
										})}
								</View>
							))
						: rows.map((row) => (
								<RestRow
									key={row.id}
									row={row}
									columns={rest}
									name={name(row)}
									chosen={row.id === props.selected}
									opens={opens(row)}
									edits={edits}
									editing={editing?.row === row.id ? editing.key : undefined}
									store={store}
									actions={actions}
								/>
							))}
				</View>
			</ScrollView>
		</View>
	);
}

function HeadCell(props: {
	column: TableColumn;
	sort: Sort | undefined;
	frozen: boolean;
	onSort: () => void;
}) {
	const { column, sort, frozen } = props;
	const words = useWords();
	const end = isEnd(column);
	const direction = sort?.key === column.key ? sort.direction : undefined;
	const edge = frozen && tableFrozenCell({ state: "rest" });
	const label = (
		<RNText
			numberOfLines={1}
			className={cn(
				tableHeadLabel({ sort: direction ? "sorted" : "none" }),
				LABEL,
			)}
		>
			{column.label}
		</RNText>
	);
	if (!column.sortable)
		return (
			<View className={cn(TABLE_CELL, edge, HEAD, end && CELL_END)}>
				{label}
			</View>
		);
	// A sorted column's arrow takes the label's ink; an unsorted column shows
	// no hint, which the web keeps for the pointer and the keyboard.
	const glyph = direction ? (
		<View className={GLYPH}>
			<Ink.Provider value="ink-body">
				<Icon
					name={direction === "descending" ? "ArrowDown" : "ArrowUp"}
					fit="meta"
				/>
			</Ink.Provider>
		</View>
	) : null;
	return (
		<Pressable
			accessibilityRole="button"
			accessibilityLabel={column.label}
			accessibilityValue={{ text: direction ? words[direction] : undefined }}
			onPress={props.onSort}
			className={cn(tableHead({ state: "rest" }), edge, SORT, end && CELL_END)}
		>
			{end ? glyph : null}
			{label}
			{end ? null : glyph}
		</Pressable>
	);
}

// An age cell's words, read off the shared clock: the cell draws again only
// when they change.
function Age(props: { moment: string }) {
	return useClock((now) => age(props.moment, now));
}

// A cell at rest past the leading one, by its column's kind.
function CellValueView(props: {
	column: TableColumn;
	cell: TableCell | undefined;
}) {
	const { column, cell } = props;
	if (cell === null || cell === undefined) return null;
	switch (column.kind) {
		case "check":
			// A ticked read-only check says its column's label.
			return cell === true ? (
				<View
					accessible
					accessibilityRole="image"
					accessibilityLabel={column.label}
					className={TICK}
				>
					<Ink.Provider value="ink-body">
						<Icon name="Check" fit="body" />
					</Ink.Provider>
				</View>
			) : null;
		case "status": {
			const status = cell as StatusCell;
			return <StatusBase state={status.status} label={status.label} />;
		}
		case "chip":
			return (
				<View className={CHIP}>
					<Chip family={column.family} label={shown(column, cell)} />
				</View>
			);
		case "source":
			return (
				<RNText numberOfLines={1} className={cn(text({ role: "code" }), VALUE)}>
					{shown(column, cell)}
				</RNText>
			);
		case "number":
			return (
				<RNText
					numberOfLines={1}
					className={cn(text({ role: "body" }), FIGURES, VALUE)}
				>
					{shown(column, cell)}
				</RNText>
			);
		case "age":
			return (
				<RNText
					numberOfLines={1}
					className={cn(text({ role: "meta" }), FIGURES, VALUE)}
				>
					<Age moment={String(cell)} />
				</RNText>
			);
		default:
			return (
				<RNText numberOfLines={1} className={cn(text({ role: "body" }), VALUE)}>
					{shown(column, cell)}
				</RNText>
			);
	}
}

// A cell's edit in place: the Input of its column's kind, or its Picker. The
// cell context sets its fit and its name, focuses it or opens its sheet.
function CellEdit(props: {
	column: TableColumn;
	cell: TableCell | undefined;
	onEdit: (value: CellValue) => void;
}) {
	const { column, cell } = props;
	const [draft, setDraft] = useState(
		cell === null || cell === undefined ? "" : String(cell),
	);
	if (column.edit?.control === "picker")
		return (
			<PickerBase<string | null>
				label={column.label}
				options={column.edit.options}
				value={typeof cell === "string" || cell === null ? cell : undefined}
				onChange={props.onEdit}
				chip={column.kind === "chip" ? column.family : undefined}
			/>
		);
	const number = column.kind === "number";
	return (
		<Input
			kind={number ? "number" : column.kind === "source" ? "source" : "text"}
			value={draft}
			onChange={setDraft}
			onCommit={(value) =>
				props.onEdit(
					number ? (value.trim() === "" ? null : Number(value)) : value,
				)
			}
		/>
	);
}

// A loading row's waits, one per column: a check's box, a number's quarter
// bar, a status's dot and word, the other bars by their place among the bars.
function waits(
	columns: readonly TableColumn[],
	bars: readonly string[],
	odd: boolean,
): ReactNode[] {
	let bar = 0;
	return columns.map((column) => {
		if (column.kind === "check")
			return <View key={column.key} className={skeleton({ kind: "check" })} />;
		if (column.kind === "number")
			return (
				<View
					key={column.key}
					className={cn(skeleton({ kind: "line" }), NUMBER_BAR)}
				/>
			);
		if (column.kind === "status")
			return <StatusBase key={column.key} waiting={odd ? "third" : "half"} />;
		const width = bars[bar++ % bars.length];
		return (
			<View
				key={column.key}
				className={cn(skeleton({ kind: "line" }), width)}
			/>
		);
	});
}

// Below `tablet`: the sort's pick over one ListRow per record.
function Phone(props: {
	columns: readonly TableColumn[];
	rows: readonly TableRecord[];
	sort: Sort | undefined;
	onSort: (sort: Sort) => void;
	onOpen: ((id: string) => void) | undefined;
	loading: boolean | undefined;
}) {
	const words = useWords();
	const { columns, sort } = props;
	const [leading, ...rest] = columns;
	const status = rest.find((column) => column.kind === "status");
	const chip = rest.find((column) => column.kind === "chip");
	const ageColumn = rest.find((column) => column.kind === "age");
	const meta = rest.filter(
		(column) => column !== status && column !== chip && column !== ageColumn,
	);
	const sortable = columns.filter((column) => column.sortable);
	const sortedBy = sortable.find((column) => column.key === sort?.key);
	const arrow = sort?.direction === "ascending" ? "ArrowUp" : "ArrowDown";
	const pick = sortable.length ? (
		<View className={SORT_BAR}>
			<PickerBase<string>
				label={words.sort}
				name={
					sortedBy && sort
						? `${words.sort}, ${sortedBy.label}, ${words[sort.direction]}`
						: undefined
				}
				options={sortable.map((column) => ({
					value: column.key,
					label: column.label,
					icon: column === sortedBy ? arrow : undefined,
				}))}
				value={sortedBy?.key}
				onChange={(key) =>
					props.onSort(
						sort?.key === key && sort.direction === "descending"
							? { key, direction: "ascending" }
							: { key, direction: "descending" },
					)
				}
				fit="row"
			/>
		</View>
	) : null;
	const cell = (record: TableRecord, column: TableColumn | undefined) =>
		column ? record.cells[column.key] : undefined;
	const { onOpen } = props;
	// The rows' ages from the shared clock, one line each: the list draws
	// again only when one of their words changes.
	const ages = useClock(
		(now) =>
			props.rows
				.map((record) => {
					const when = cell(record, ageColumn);
					return typeof when === "string" ? age(when, now) : "";
				})
				.join("\n"),
		ageColumn ? undefined : 0,
	).split("\n");
	const ageOf = new Map(props.rows.map((record, at) => [record.id, ages[at]]));
	// A slot is declared only when a column fills it, so the waiting rows
	// stand in the slots the loaded ones draw.
	const row: RowSlots<TableRecord> = {
		key: (record) => record.id,
		title: (record) =>
			leading ? shown(leading, cell(record, leading)) : record.id,
		meta: meta.length
			? (record) => {
					const parts = meta
						.map((column) => {
							const at = cell(record, column);
							if (column.kind === "check")
								return at === true ? column.label : "";
							if (column.kind === "number" && at !== null && at !== undefined)
								return `${column.label} ${at}`;
							return shown(column, at);
						})
						.filter((part) => part !== "");
					return parts.length ? parts : undefined;
				}
			: undefined,
		trailing: ageColumn
			? (record) => {
					const words = ageOf.get(record.id);
					return words ? { age: words } : undefined;
				}
			: undefined,
		status: status
			? (record) => {
					const state = cell(record, status);
					// A status cell is the one object a cell holds.
					return typeof state === "object" && state !== null
						? {
								state: state.status,
								label: state.label ?? words[state.status],
							}
						: undefined;
				}
			: undefined,
		chip:
			chip?.kind === "chip"
				? (record) => {
						const value = cell(record, chip);
						return typeof value === "string"
							? { family: chip.family, label: shown(chip, value) }
							: undefined;
					}
				: undefined,
		href: (record) => record.href,
		// A row with `href` goes there; the others open through `onOpen`.
		onOpen: onOpen ? (record) => onOpen(record.id) : undefined,
	};
	return (
		<>
			{pick}
			<List items={props.rows} loading={props.loading} row={row} />
		</>
	);
}

// plugins/solid-ui/src/ui/components/table/index.tsx
import type {
	CellPick,
	CellValue,
	ColumnWidth,
	Option,
	TableCell,
	TableColumn,
	TableRow,
} from "@fcalell/ui-core/descriptors";
import {
	CHECKBOX_MARK,
	checkbox,
	TABLE_CELL,
	tableRow,
	text,
} from "@fcalell/ui-core/variants";
import { ArrowDown, ArrowUp, Check } from "lucide-solid";
import {
	createMemo,
	createSignal,
	For,
	type JSX,
	Match,
	onCleanup,
	onMount,
	Show,
	Switch,
} from "solid-js";
import { Dynamic } from "solid-js/web";
import { ageOf, momentOf, useClock } from "#lib/age.ts";
import { CellContext } from "#lib/cell.ts";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { RING, RING_INSET, WASH } from "#lib/interact.ts";
import { LoadingRows } from "#lib/loading.tsx";
import { useWholeWidth } from "#lib/measure.ts";
import { listedRow } from "#lib/table-list.ts";
import { Chip } from "../chip/index.tsx";
import { Input } from "../input/index.tsx";
import { List } from "../list/index.tsx";
import { ListRow } from "../list-row/index.tsx";
import { Picker } from "../picker/index.tsx";
import { Status } from "../status/index.tsx";

// A data grid: a header row, one row per item keyed by its id, every cell
// drawn by its column's kind. The row whose id is `selected` is the open
// one, on `accent-soft` as a `Split` list's open item is. A click on a cell
// opens its row through `onOpen`, unless the column edits: then the cell
// becomes its control in place (an `Input` of the column's kind, a `Picker`
// whose `null` option clears the cell, a tick), commits on Enter or blur,
// cancels on Escape, and calls `onEdit` once per commit that changed the
// value, `null` for a cleared cell. The grid is one tab stop: the
// arrows move the focused cell, Tab and Shift+Tab step across it, Enter
// edits or opens. A `sortable` column sorts on its header, ascending,
// descending, then back to the rows' order. With no rows the header stands
// over `empty`. Inside a `Place` the table takes the whole column. Under
// tablet a grid has no room: the rows are a list of `ListRow`s drawn from the
// same columns (`lib/table-list.ts`), as on native, a tap opening the row.
export type TableProps = Closed & {
	columns: TableColumn[];
	rows: TableRow[];
	selected?: string;
	onOpen?: (id: string) => void;
	onEdit?: (id: string, key: string, value: CellValue) => void;
	empty?: JSX.Element;
	loading?: boolean;
};

const WIDTH: Record<ColumnWidth, string> = {
	rail: "w-rail",
	list: "w-list",
	column: "w-column",
	sheet: "w-sheet",
	reading: "w-reading",
	"1/4": "w-1/4",
	"1/3": "w-1/3",
	"1/2": "w-1/2",
	"2/3": "w-2/3",
	"3/4": "w-3/4",
};

const width = (column: TableColumn) =>
	column.width ? cn(WIDTH[column.width], "shrink-0") : "min-w-0 flex-1";

// A number reads from its end; everything else from its start.
const atEnd = (column: TableColumn) =>
	(column.align ?? (column.kind === "number" ? "end" : "start")) === "end";

// The options a picked column draws its values' labels from.
function optionsOf(column: TableColumn): readonly Option<string | null>[] {
	if (column.edit?.control !== "picker") return [];
	const first = column.edit.options[0];
	if (first === undefined || !("options" in first))
		return column.edit.options as Option<string | null>[];
	return column.edit.options.flatMap((group) =>
		"options" in group ? group.options : [],
	);
}

// The words a cell draws, which are also what it sorts by.
function shown(column: TableColumn, cell: TableCell): string | number {
	if (cell === null || cell === undefined) return "";
	if (typeof cell === "object") return cell.label ?? cell.status;
	if (typeof cell === "boolean") return cell ? 1 : 0;
	if (column.edit?.control === "picker") {
		return (
			optionsOf(column).find((option) => option.value === cell)?.label ?? cell
		);
	}
	return cell;
}

// Empty cells sort last in either direction.
function compare(column: TableColumn, a: TableCell, b: TableCell): number {
	const x = shown(column, a);
	const y = shown(column, b);
	if (x === "" || y === "") return x === y ? 0 : x === "" ? 1 : -1;
	if (typeof x === "number" && typeof y === "number") return x - y;
	return String(x).localeCompare(String(y), undefined, { numeric: true });
}

type Sort = { key: string; descending: boolean };
type Spot = { id: string; key: string };

function CheckMark(props: { checked: boolean }) {
	return (
		<span
			class={cn(
				checkbox({ state: props.checked ? "checked" : "unchecked" }),
				CHECKBOX_MARK,
				"inline-flex size-6 shrink-0 items-center justify-center",
			)}
		>
			<Show when={props.checked}>
				<Check class="size-4" aria-hidden="true" />
			</Show>
		</span>
	);
}

function CellView(props: { column: TableColumn; cell: TableCell }) {
	const clock = useClock();
	const column = () => props.column;
	return (
		<Switch
			fallback={
				<span
					class={cn(
						text({ role: column().kind === "source" ? "mono" : "body" }),
						"min-w-0 truncate",
						column().kind === "number" && "tabular-nums",
					)}
				>
					{shown(column(), props.cell)}
				</span>
			}
		>
			<Match when={props.cell === null || props.cell === undefined}>
				{null}
			</Match>
			<Match when={column().kind === "chip" && column()}>
				{(chip) => (
					<Chip
						label={String(shown(chip(), props.cell))}
						family={(chip() as Extract<TableColumn, { kind: "chip" }>).family}
					/>
				)}
			</Match>
			<Match
				when={
					column().kind === "status" &&
					typeof props.cell === "object" &&
					props.cell
				}
			>
				{(cell) => <Status state={cell().status} label={cell().label} />}
			</Match>
			<Match when={column().kind === "age" && typeof props.cell === "string"}>
				<time
					datetime={props.cell as string}
					title={momentOf(props.cell as string)}
					class={cn(text({ role: "meta" }), "shrink-0 tabular-nums")}
				>
					{ageOf(props.cell as string, clock())}
				</time>
			</Match>
			<Match when={column().kind === "check"}>
				<CheckMark checked={props.cell === true} />
			</Match>
		</Switch>
	);
}

// The `Input` that edits a typed cell, focused with its text selected as it
// mounts. Its keys and its blur are the cell's to read.
function TypedEditor(props: {
	column: TableColumn;
	value: string;
	onChange: (value: string) => void;
}) {
	let box!: HTMLDivElement;
	onMount(() => {
		const input = box.querySelector("input");
		input?.focus();
		input?.select();
	});
	const kind = () =>
		props.column.kind === "source"
			? "source"
			: props.column.kind === "number"
				? "number"
				: "text";
	return (
		// The field's border overhangs the cell by a pixel above and below,
		// so the row keeps its height while the cell edits.
		<div ref={box} class="-my-px w-full">
			<Input kind={kind()} value={props.value} onChange={props.onChange} />
		</div>
	);
}

export function Table(props: TableProps) {
	useWholeWidth();
	const [sort, setSort] = createSignal<Sort>();
	const [focus, setFocus] = createSignal<Spot>();
	const [editing, setEditing] = createSignal<Spot>();
	const [draft, setDraft] = createSignal("");
	const cells = new Map<string, HTMLElement>();
	const spotKey = (spot: Spot) => `${spot.id}\u0000${spot.key}`;
	const same = (a: Spot | undefined, b: Spot) =>
		a !== undefined && spotKey(a) === spotKey(b);

	const rows = createMemo(() => {
		const by = sort();
		if (!by) return props.rows;
		const column = props.columns.find((each) => each.key === by.key);
		if (!column) return props.rows;
		const sign = by.descending ? -1 : 1;
		return [...props.rows].sort((a, b) => {
			const x = a.cells[by.key] ?? null;
			const y = b.cells[by.key] ?? null;
			// Empty cells stay last whichever way the column sorts.
			const flip = shown(column, x) === "" || shown(column, y) === "";
			return compare(column, x, y) * (flip ? 1 : sign);
		});
	});

	// The cell that holds the grid's one tab stop: the focused one while its
	// row is shown, else the first.
	const stop = createMemo<Spot | undefined>(() => {
		const spot = focus();
		const list = rows();
		if (
			spot &&
			list.some((row) => row.id === spot.id) &&
			props.columns.some((column) => column.key === spot.key)
		)
			return spot;
		const first = list[0];
		const column = props.columns[0];
		return first && column ? { id: first.id, key: column.key } : undefined;
	});

	const place = (spot: Spot) => {
		setFocus(spot);
		cells.get(spotKey(spot))?.focus();
	};

	const indexOf = (spot: Spot) => ({
		row: rows().findIndex((row) => row.id === spot.id),
		column: props.columns.findIndex((each) => each.key === spot.key),
	});

	const move = (rowAt: number, columnAt: number) => {
		const list = rows();
		const row = list[Math.max(0, Math.min(list.length - 1, rowAt))];
		const column =
			props.columns[Math.max(0, Math.min(props.columns.length - 1, columnAt))];
		if (row && column) place({ id: row.id, key: column.key });
	};

	// One step across the grid, row by row; false past either end, where Tab
	// leaves the grid.
	const step = (spot: Spot, back: boolean): boolean => {
		const span = props.columns.length;
		const at = indexOf(spot);
		const next = at.row * span + at.column + (back ? -1 : 1);
		if (next < 0 || next >= rows().length * span) return false;
		move(Math.floor(next / span), next % span);
		return true;
	};

	const commit = (spot: Spot, value: CellValue, refocus: boolean) => {
		if (!same(editing(), spot)) return;
		setEditing(undefined);
		const row = props.rows.find((each) => each.id === spot.id);
		if (row && (row.cells[spot.key] ?? null) !== value)
			props.onEdit?.(spot.id, spot.key, value);
		if (refocus) place(spot);
	};

	const cancel = (spot: Spot, refocus: boolean) => {
		if (!same(editing(), spot)) return;
		setEditing(undefined);
		if (refocus) place(spot);
	};

	// A typed commit: a number that does not parse is no commit, and the cell
	// keeps its value.
	const settle = (column: TableColumn, spot: Spot, refocus: boolean) => {
		const raw = draft();
		if (column.kind !== "number") return commit(spot, raw, refocus);
		const value = Number(raw.trim());
		if (raw.trim() === "" || !Number.isFinite(value))
			return cancel(spot, refocus);
		commit(spot, value, refocus);
	};

	const activate = (row: TableRow, column: TableColumn) => {
		const spot = { id: row.id, key: column.key };
		setFocus(spot);
		const cell = row.cells[column.key] ?? null;
		if (column.edit?.control === "checkbox") {
			props.onEdit?.(row.id, column.key, cell !== true);
		} else if (column.edit) {
			setDraft(cell === null ? "" : String(cell));
			setEditing(spot);
		} else {
			props.onOpen?.(row.id);
		}
	};

	// The keys of a cell editing its value.
	const editKeys = (event: KeyboardEvent, column: TableColumn, spot: Spot) => {
		// A picker's own list reads its keys.
		if (column.edit?.control === "picker") return;
		if (event.key === "Enter") settle(column, spot, true);
		else if (event.key === "Escape") cancel(spot, true);
		else if (event.key === "Tab") {
			settle(column, spot, true);
			step(spot, event.shiftKey);
		} else return;
		event.preventDefault();
		event.stopPropagation();
	};

	// The keys of a focused cell at rest.
	const moveKeys = (
		event: KeyboardEvent,
		row: TableRow,
		column: TableColumn,
	) => {
		const spot = { id: row.id, key: column.key };
		const at = indexOf(spot);
		switch (event.key) {
			case "ArrowDown":
				move(at.row + 1, at.column);
				break;
			case "ArrowUp":
				move(at.row - 1, at.column);
				break;
			case "ArrowRight":
				move(at.row, at.column + 1);
				break;
			case "ArrowLeft":
				move(at.row, at.column - 1);
				break;
			case "Home":
				move(at.row, 0);
				break;
			case "End":
				move(at.row, props.columns.length - 1);
				break;
			case "Tab":
				if (!step(spot, event.shiftKey)) return;
				break;
			case "Enter":
				activate(row, column);
				break;
			case " ":
				if (column.edit?.control !== "checkbox") return;
				activate(row, column);
				break;
			default:
				return;
		}
		event.preventDefault();
	};

	const toggle = (key: string) => {
		const by = sort();
		if (by?.key !== key) setSort({ key, descending: false });
		else if (!by.descending) setSort({ key, descending: true });
		else setSort(undefined);
	};

	const header = () => (
		<tr class={cn(tableRow({ state: "rest" }), "flex w-full")}>
			<For each={props.columns}>
				{(column) => {
					const sorted = () =>
						sort()?.key === column.key ? sort() : undefined;
					return (
						<th
							scope="col"
							aria-sort={
								column.sortable
									? sorted()
										? sorted()?.descending
											? "descending"
											: "ascending"
										: "none"
									: undefined
							}
							class={cn(
								TABLE_CELL,
								text({ role: "label" }),
								width(column),
								"flex items-center",
								atEnd(column) ? "justify-end text-right" : "text-left",
							)}
						>
							<Show
								when={column.sortable}
								fallback={<span class="truncate">{column.label}</span>}
							>
								<button
									type="button"
									onClick={() => toggle(column.key)}
									class={cn(
										"inline-flex min-w-0 cursor-pointer items-center gap-pair rounded-group hover:text-ink",
										RING,
									)}
								>
									<span class="truncate">{column.label}</span>
									<Show when={sorted()}>
										{(by) => (
											<Dynamic
												component={by().descending ? ArrowDown : ArrowUp}
												class="size-4 shrink-0"
												aria-hidden="true"
											/>
										)}
									</Show>
								</button>
							</Show>
						</th>
					);
				}}
			</For>
		</tr>
	);

	const cellOf = (row: TableRow, column: TableColumn) => {
		const spot = { id: row.id, key: column.key };
		onCleanup(() => cells.delete(spotKey(spot)));
		const cell = () => row.cells[column.key] ?? null;
		const isEditing = () => same(editing(), spot);
		const isStop = () => same(stop(), spot);
		return (
			<td
				ref={(element) => cells.set(spotKey(spot), element)}
				tabindex={isStop() ? 0 : -1}
				onFocus={() => setFocus(spot)}
				onClick={() => {
					if (!isEditing()) activate(row, column);
				}}
				onKeyDown={(event) => {
					if (isEditing()) editKeys(event, column, spot);
					else if (event.target === event.currentTarget)
						moveKeys(event, row, column);
				}}
				onFocusOut={(event) => {
					// Leaving a typed edit commits it; a picker's list lives
					// outside the cell and reports its own close.
					if (!isEditing() || column.edit?.control === "picker") return;
					const next = event.relatedTarget;
					if (next instanceof Node && event.currentTarget.contains(next))
						return;
					settle(column, spot, false);
				}}
				class={cn(
					width(column),
					"flex min-h-floor items-center",
					!isEditing() && TABLE_CELL,
					!isEditing() && (column.edit || props.onOpen) && "cursor-pointer",
					atEnd(column) && "justify-end text-right",
					RING_INSET,
				)}
			>
				<Switch fallback={<CellView column={column} cell={cell()} />}>
					<Match
						when={
							isEditing() && column.edit?.control === "picker" && column.edit
						}
					>
						{(edit) => (
							<CellContext.Provider value={{ close: () => cancel(spot, true) }}>
								<Picker
									label={column.label}
									options={(edit() as CellPick).options}
									value={typeof cell() === "string" ? String(cell()) : null}
									onChange={(value) => commit(spot, value, true)}
								/>
							</CellContext.Provider>
						)}
					</Match>
					<Match when={isEditing()}>
						<TypedEditor column={column} value={draft()} onChange={setDraft} />
					</Match>
				</Switch>
			</td>
		);
	};

	return (
		<div class="flex flex-col">
			{/* From tablet the grid; under it the rows as a list, where a grid
			    has no room. */}
			<div class="hidden flex-col overflow-x-auto tablet:flex">
				{/* biome-ignore lint/a11y/noNoninteractiveElementToInteractiveRole: the grid pattern, a table whose cells take focus, move by the arrows and edit in place */}
				<table role="grid" class="flex w-full flex-col">
					<thead class="flex flex-col">{header()}</thead>
					<Show when={!props.loading && rows().length > 0}>
						<tbody class="flex flex-col">
							<For each={rows()}>
								{(row) => (
									<tr
										aria-selected={row.id === props.selected}
										class={cn(
											tableRow({
												state: row.id === props.selected ? "selected" : "rest",
											}),
											"flex w-full transition-colors duration-(--duration-fast) ease-ui",
											props.onOpen && WASH,
										)}
									>
										<For each={props.columns}>
											{(column) => cellOf(row, column)}
										</For>
									</tr>
								)}
							</For>
						</tbody>
					</Show>
				</table>
			</div>
			<Show when={!props.loading && rows().length > 0}>
				<div class="flex flex-col tablet:hidden">
					<List>
						<For each={rows()}>
							{(row) => {
								const listed = () => listedRow(props.columns, row);
								return (
									<ListRow
										title={listed().title}
										leading={listed().leading}
										meta={listed().meta}
										trailing={listed().trailing}
										onOpen={
											props.onOpen ? () => props.onOpen?.(row.id) : undefined
										}
									/>
								);
							}}
						</For>
					</List>
				</div>
			</Show>
			<Show when={props.loading}>
				<LoadingRows />
			</Show>
			<Show when={!props.loading && rows().length === 0}>
				<div class="flex flex-col pt-stack">{props.empty}</div>
			</Show>
		</div>
	);
}
