// plugins/solid-ui/src/ui/components/row/index.tsx
import { rhythm } from "@fcalell/ui-core/variants";
import type { JSX } from "solid-js";
import { cn } from "#lib/cn";

type RowProps = {
	children?: JSX.Element;
	class?: never;
	style?: never;
	classList?: never;
};

// Items in a group, laid inline and gapped at the row rung. A left/right
// split is justify-between geometry, not a Row.
function Row(props: RowProps) {
	return (
		<div class={cn(rhythm({ unit: "row" }), "flex flex-row items-center")}>
			{props.children}
		</div>
	);
}

export type { RowProps };
export { Row };

// plugins/native-ui/src/ui/components/row/index.tsx
import { rhythm } from "@fcalell/ui-core/variants";
import type { ReactNode } from "react";
import { View } from "react-native";
import { cn } from "../../lib/cn";

export interface RowProps {
	children?: ReactNode;
	className?: never;
	style?: never;
}

// Items in a group, laid inline and gapped at the row rung. A left/right
// split is justify-between geometry, not a Row. The direction classes are
// the native overlay; the gap is the shared RHYTHM cell.
export function Row({ children }: RowProps) {
	return (
		<View className={cn(rhythm({ unit: "row" }), "flex-row items-center")}>
			{children}
		</View>
	);
}
