// plugins/solid-ui/src/ui/components/form/index.tsx
import { rhythm } from "@fcalell/ui-core/variants";
import type { JSX } from "solid-js";
import { BarContext } from "#lib/bar";
import type { Closed } from "#lib/closed";
import { cn } from "#lib/cn";

// Fields at `stack`; its `ActionBar` last and in flow, so it scrolls with the
// fields and the keyboard never covers it.
export type FormProps = Closed & {
	onSubmit: () => void;
	children?: JSX.Element;
};

export function Form(props: FormProps) {
	return (
		<BarContext.Provider value="flow">
			<form
				class={cn(rhythm({ unit: "stack" }), "flex flex-col")}
				onSubmit={(event) => {
					event.preventDefault();
					props.onSubmit();
				}}
			>
				{props.children}
			</form>
		</BarContext.Provider>
	);
}

// plugins/native-ui/src/ui/components/form/index.tsx
import { createContext, type ReactNode, useContext } from "react";
import { View } from "react-native";
import type { Closed } from "../../lib/closed";

export interface FormProps extends Closed {
	onSubmit: () => void;
	children?: ReactNode;
}

const FormContext = createContext<(() => void) | undefined>(undefined);

// Fields at `stack`; its ActionBar last and in flow, so it scrolls with the
// fields and the keyboard never covers it.
export function Form({ onSubmit, children }: FormProps) {
	return (
		<FormContext.Provider value={onSubmit}>
			<View className="gap-stack">{children}</View>
		</FormContext.Provider>
	);
}

export function useFormSubmit(): (() => void) | undefined {
	return useContext(FormContext);
}
