// plugins/native-ui/src/ui/components/section/index.tsx
import type { Act, Part } from "@fcalell/ui-core/descriptors";
import { text } from "@fcalell/ui-core/variants";
import { ChevronDown, ChevronRight } from "lucide-react-native";
import { type ReactNode, useEffect, useState } from "react";
import { Pressable, Text as RNText, View } from "react-native";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { Glyph } from "../../lib/glyph";
import { LoadingRows } from "../../lib/loading";
import { partText } from "../../lib/parts";
import { useTouched } from "../../lib/touched";
import { Count } from "../count";

export interface SectionProps extends Closed {
	title: Part;
	count?: number;
	description?: string;
	folded?: boolean;
	// Called as a foldable section opens or closes, with its new state: what
	// the consumer does with what it showed, such as marking it read once it
	// folds again.
	onToggle?: (open: boolean) => void;
	act?: Act;
	loading?: boolean;
	children?: ReactNode;
}

// A labelled region of a screen: the label header with its count and act,
// the loading form. Setting `folded` makes it foldable: the label becomes a
// button with a chevron, starting folded or open as `folded` says. A blocked
// act says its reason under it once pressed or once its form or sheet is
// touched, as a `Button` does.
export function Section({
	title,
	count,
	description,
	folded,
	onToggle,
	act,
	loading,
	children,
}: SectionProps) {
	const foldable = folded !== undefined;
	const [open, setOpen] = useState(!folded);
	const { touched } = useTouched();
	const blocked = act?.blocked !== undefined;
	const [pressed, setPressed] = useState(false);
	useEffect(() => {
		if (!blocked) setPressed(false);
	}, [blocked]);
	const said = blocked && (pressed || touched);
	const label = (
		<>
			<RNText className={cn(text({ role: "label" }), "uppercase")}>
				{partText(title)}
			</RNText>
			{count !== undefined ? <Count value={count} /> : null}
		</>
	);
	return (
		<View className="gap-stack">
			<View className="min-h-11 flex-row items-center gap-row">
				{foldable ? (
					<Pressable
						accessibilityRole="button"
						accessibilityState={{ expanded: open }}
						onPress={() => {
							const next = !open;
							setOpen(next);
							onToggle?.(next);
						}}
						className="min-h-11 flex-row items-center gap-pair"
					>
						{label}
						<Glyph
							icon={open ? ChevronDown : ChevronRight}
							tone="ink-faint"
							size={16}
						/>
					</Pressable>
				) : (
					<View
						accessibilityRole="header"
						className="flex-row items-center gap-pair"
					>
						{label}
					</View>
				)}
				<View className="flex-1" />
				{act ? (
					<View className="items-end gap-pair">
						<Pressable
							accessibilityRole="button"
							accessibilityState={{ disabled: blocked || act.loading }}
							accessibilityHint={said ? act.blocked : undefined}
							disabled={act.loading}
							onPress={() => (blocked ? setPressed(true) : act.onAct())}
							className="min-h-11 justify-center"
						>
							<RNText
								className={cn(
									text({ role: "meta" }),
									"font-medium text-tint",
									blocked && "text-ink-faint",
								)}
							>
								{act.label}
							</RNText>
						</Pressable>
						{said ? (
							<RNText className={text({ role: "meta" })}>{act.blocked}</RNText>
						) : null}
					</View>
				) : null}
			</View>
			{description ? (
				<RNText className={text({ role: "meta" })}>{description}</RNText>
			) : null}
			{open ? loading ? <LoadingRows /> : children : null}
		</View>
	);
}

// plugins/solid-ui/src/ui/components/section/index.tsx
import type { Act, Part } from "@fcalell/ui-core/descriptors";
import { text } from "@fcalell/ui-core/variants";
import { ChevronDown } from "lucide-solid";
import {
	createContext,
	createEffect,
	createSignal,
	createUniqueId,
	type JSX,
	Show,
	useContext,
} from "solid-js";
import { BarContext } from "#lib/bar.ts";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { RING, TEXT_ACT } from "#lib/interact.ts";
import { LoadingRows } from "#lib/loading.tsx";
import { Parts } from "#lib/parts.tsx";
import { useTouched } from "#lib/touched.ts";
import { Count } from "../count/index.tsx";

// A titled region of a screen: the label header with its count and act.
// `folded` makes it fold, starting folded when true and open when false;
// without it the header is a plain label. The space above it is its
// container's gap; a nested section, which sits in its parent's tight
// rhythm, takes `stack` above it. An `ActionBar` inside is the section's
// own, in flow at its end, never pinned to the screen. A blocked act stays
// focusable and says its reason under the header once tapped, or once the
// form or sheet around it is touched, as a `Button` does.
export type SectionProps = Closed & {
	title: Part;
	count?: number;
	description?: string;
	folded?: boolean;
	// Called as a foldable section opens or closes, with its new state: what
	// the consumer does with what it showed, such as marking it read once
	// it folds again.
	onToggle?: (open: boolean) => void;
	act?: Act;
	loading?: boolean;
	children?: JSX.Element;
};

const Nested = createContext(false);

export function Section(props: SectionProps) {
	const nested = useContext(Nested);
	const [open, setOpen] = createSignal(!props.folded);
	const foldable = () => props.folded !== undefined;
	const id = createUniqueId();
	const touched = useTouched();
	const reason = createUniqueId();
	const [tapped, setTapped] = createSignal(false);
	const blocked = () => props.act?.blocked !== undefined;
	const said = () => blocked() && (tapped() || touched());
	createEffect(() => {
		if (!blocked()) setTapped(false);
	});
	const label = () => (
		<>
			<h2 id={id} class={cn(text({ role: "label" }), "truncate")}>
				<Parts parts={[props.title]} />
			</h2>
			<Show when={props.count !== undefined}>
				<Count value={props.count ?? 0} />
			</Show>
		</>
	);
	return (
		<Nested.Provider value={true}>
			{/* A foldable section is a disclosure group, not a landmark: a screen
			    may fold several under one name ("Did 2 things"), and landmarks
			    must be unique. */}
			<section
				aria-labelledby={id}
				role={foldable() ? "group" : undefined}
				class={cn("flex flex-col gap-row", nested && "pt-stack")}
			>
				{/* The description is the label's own line, a pair below it, so it
				    never reads as the section's content; a blocked act's reason is
				    the header's last line, at its end under the act. */}
				<div class="flex flex-col">
					<div class="flex min-h-floor items-center justify-between gap-row">
						<div class="flex min-w-0 flex-col gap-pair">
							<Show
								when={foldable()}
								fallback={
									<div class="flex min-w-0 items-center gap-pair">
										{label()}
									</div>
								}
							>
								<button
									type="button"
									aria-expanded={open()}
									onClick={() => {
										const next = !open();
										setOpen(next);
										props.onToggle?.(next);
									}}
									class={cn(
										"flex min-h-floor min-w-0 cursor-pointer items-center gap-pair self-start text-left",
										RING,
									)}
								>
									{label()}
									<ChevronDown
										class={cn(
											"size-4 shrink-0 text-ink-faint transition-transform duration-(--duration-base) ease-ui",
											open() || "-rotate-90",
										)}
										aria-hidden="true"
									/>
								</button>
							</Show>
							<Show when={props.description}>
								<p class={text({ role: "meta" })}>{props.description}</p>
							</Show>
						</div>
						<Show when={props.act}>
							{(act) => (
								<button
									type="button"
									aria-disabled={blocked() || undefined}
									aria-describedby={said() ? reason : undefined}
									onClick={() => {
										if (blocked()) setTapped(true);
										else act().onAct();
									}}
									class={cn(
										text({ role: "meta" }),
										"min-h-floor shrink-0",
										TEXT_ACT,
									)}
								>
									{act().label}
								</button>
							)}
						</Show>
					</div>
					<Show when={said()}>
						<p id={reason} class={cn(text({ role: "meta" }), "text-right")}>
							{props.act?.blocked}
						</p>
					</Show>
				</div>
				<Show when={open()}>
					<Show when={!props.loading} fallback={<LoadingRows />}>
						<BarContext.Provider value="flow">
							{props.children}
						</BarContext.Provider>
					</Show>
				</Show>
			</section>
		</Nested.Provider>
	);
}
