// plugins/solid-ui/src/ui/components/bar-chart/index.tsx
import type { BarSeries } from "@fcalell/ui-core/descriptors";
import { METER_TRACK, text } from "@fcalell/ui-core/variants";
import { createMemo, For, Show } from "solid-js";
import type { Closed } from "#lib/closed";
import { cn } from "#lib/cn";
import { LoadingRows } from "#lib/loading";

// One labelled bar per series item, stacked by its parts, the value beside it
// with the unit, the time under it.
export type BarChartProps = Closed & {
	series: BarSeries[];
	unit: string;
	loading?: boolean;
};

const PART_FILLS = ["bg-tint", "bg-accent-soft", "bg-edge"];

export function BarChart(props: BarChartProps) {
	const max = createMemo(() =>
		props.series.reduce((top, item) => Math.max(top, item.value), 0),
	);
	return (
		<Show when={!props.loading} fallback={<LoadingRows />}>
			<div class="flex flex-col gap-stack">
				<For each={props.series}>
					{(item) => (
						<div class="flex flex-col gap-pair">
							<div class="flex items-center justify-between gap-row">
								<span class={text({ role: "body" })}>{item.label}</span>
								<span class={cn(text({ role: "meta" }), "tabular-nums")}>
									{item.value} {props.unit}
								</span>
							</div>
							<div
								role="img"
								aria-label={`${item.label} ${item.value} ${props.unit}`}
								class={cn(METER_TRACK, "flex h-3 w-full overflow-hidden")}
							>
								<For
									each={
										item.parts ?? [{ label: item.label, value: item.value }]
									}
								>
									{(part, index) => (
										<div
											title={part.label}
											class={cn(
												"h-full",
												PART_FILLS[index() % PART_FILLS.length],
											)}
											style={{
												width: `${max() > 0 ? (part.value / max()) * 100 : 0}%`,
											}}
										/>
									)}
								</For>
							</div>
							<Show when={item.at}>
								<span class={cn(text({ role: "meta" }), "tabular-nums")}>
									{item.at}
								</span>
							</Show>
						</div>
					)}
				</For>
			</div>
		</Show>
	);
}

// plugins/native-ui/src/ui/components/bar-chart/index.tsx
import type { BarSeries } from "@fcalell/ui-core/descriptors";
import { text } from "@fcalell/ui-core/variants";
import { useState } from "react";
import { Text as RNText, View } from "react-native";
import Svg, { Rect } from "react-native-svg";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { LoadingRows } from "../../lib/loading";
import { useTokenColor } from "../../lib/theme";

export interface BarChartProps extends Closed {
	series: readonly BarSeries[];
	unit?: string;
	loading?: boolean;
}

const BAR = 12;

// One labelled bar per series item, stacked by its parts, the value beside
// it, the time under it.
export function BarChart({ series, unit, loading }: BarChartProps) {
	const [width, setWidth] = useState(0);
	const fills = [
		useTokenColor("--color-accent-ink"),
		useTokenColor("--color-accent-soft"),
		useTokenColor("--color-ink-faint"),
		useTokenColor("--color-edge"),
	];
	if (loading) return <LoadingRows />;
	const peak = Math.max(1, ...series.map((item) => item.value));
	return (
		<View
			accessibilityLabel={unit}
			onLayout={(event) => setWidth(event.nativeEvent.layout.width)}
			className="gap-fields"
		>
			{series.map((item) => {
				const parts =
					item.parts && item.parts.length > 0
						? item.parts
						: [{ label: item.label, value: item.value }];
				let x = 0;
				return (
					<View key={`${item.label}:${item.at ?? ""}`} className="gap-pair">
						<View className="flex-row items-center justify-between gap-inside">
							<RNText className={text({ role: "body" })}>{item.label}</RNText>
							<RNText className={text({ role: "meta" })}>
								{item.value}
								{unit ? ` ${unit}` : ""}
							</RNText>
						</View>
						<Svg width={width} height={BAR}>
							{parts.map((part, index) => {
								const w = (part.value / peak) * width;
								const rect = (
									<Rect
										key={part.label}
										x={x}
										y={0}
										width={w}
										height={BAR}
										rx={BAR / 2}
										fill={fills[index % fills.length]}
									/>
								);
								x += w;
								return rect;
							})}
						</Svg>
						{item.at ? (
							<RNText className={cn(text({ role: "meta" }))}>{item.at}</RNText>
						) : null}
					</View>
				);
			})}
		</View>
	);
}
