// plugins/native-ui/src/ui/components/link/index.tsx
import { text } from "@fcalell/ui-core/variants";
import type { ReactNode } from "react";
import { Linking, Text as RNText } from "react-native";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";

export interface LinkProps extends Closed {
	href: string;
	children?: ReactNode;
}

// Inline, inside body or meta; never a screen's only act.
export function Link({ href, children }: LinkProps) {
	return (
		<RNText
			accessibilityRole="link"
			className={cn(text({ role: "body" }), "text-tint underline")}
			onPress={() => {
				Linking.openURL(href);
			}}
		>
			{children}
		</RNText>
	);
}

// plugins/solid-ui/src/ui/components/link/index.tsx
import { A } from "@solidjs/router";
import type { JSX } from "solid-js";
import type { Closed } from "#lib/closed.ts";

// Inline, inside `body` or `meta`; never a screen's only act.
export type LinkProps = Closed & {
	href: string;
	children?: JSX.Element;
};

export function Link(props: LinkProps) {
	return (
		<A
			href={props.href}
			class="text-tint underline underline-offset-4 hover:text-ink focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tint"
		>
			{props.children}
		</A>
	);
}
