// plugins/solid-ui/src/ui/components/file-row/index.tsx
import { row, text } from "@fcalell/ui-core/variants";
import { A } from "@solidjs/router";
import { Check } from "lucide-solid";
import { Match, Show, Switch } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { RING_INSET, WASH } from "#lib/interact.ts";
import { LoadingRows } from "#lib/loading.tsx";

// A row for a group: a ring that becomes a tick when seen, the path in mono,
// the counts trailing.
export type FileRowProps = Closed & {
	path: string;
	added?: number;
	removed?: number;
	seen?: boolean;
	href?: string;
	onOpen?: () => void;
	loading?: boolean;
};

export function FileRow(props: FileRowProps) {
	const shell = cn(
		row({ state: "rest" }),
		"flex w-full cursor-pointer items-center text-left transition-colors duration-(--duration-fast) ease-ui",
		WASH,
		RING_INSET,
	);
	const body = () => (
		<>
			<span
				class={cn(
					"inline-flex size-5 shrink-0 items-center justify-center rounded-full",
					props.seen ? "bg-ok-soft text-ok" : "border border-ink-meta",
				)}
				aria-hidden="true"
			>
				<Show when={props.seen}>
					<Check class="size-3.5" />
				</Show>
			</span>
			<span class={cn(text({ role: "mono" }), "min-w-0 flex-1 truncate")}>
				{props.path}
			</span>
			<span
				class={cn(text({ role: "meta" }), "flex shrink-0 gap-row tabular-nums")}
			>
				<Show when={props.added !== undefined}>
					<span class="text-ok">+{props.added}</span>
				</Show>
				<Show when={props.removed !== undefined}>
					<span class="text-danger">−{props.removed}</span>
				</Show>
			</span>
		</>
	);
	return (
		<Show when={!props.loading} fallback={<LoadingRows inGroup />}>
			<Switch fallback={<div class={shell}>{body()}</div>}>
				<Match when={props.href}>
					{(href) => (
						<A href={href()} class={shell}>
							{body()}
						</A>
					)}
				</Match>
				<Match when={props.onOpen}>
					{(onOpen) => (
						<button type="button" class={shell} onClick={() => onOpen()()}>
							{body()}
						</button>
					)}
				</Match>
			</Switch>
		</Show>
	);
}

// plugins/native-ui/src/ui/components/file-row/index.tsx
import { row, text } from "@fcalell/ui-core/variants";
import { CircleCheck, Circle as Ring } from "lucide-react-native";
import { Pressable, Text as RNText, View } from "react-native";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { Glyph } from "../../lib/glyph";
import { LoadingRows } from "../../lib/loading";
import { navigate } from "../../lib/navigate";

export interface FileRowProps extends Closed {
	path: string;
	added: number;
	removed: number;
	seen?: boolean;
	href?: string;
	onOpen?: () => void;
	loading?: boolean;
}

// A row for a Group: a ring that becomes a tick when seen, the path in mono,
// the counts trailing.
export function FileRow({
	path,
	added,
	removed,
	seen,
	href,
	onOpen,
	loading,
}: FileRowProps) {
	if (loading) return <LoadingRows />;
	const open = href !== undefined ? () => navigate(href) : onOpen;
	return (
		<Pressable
			accessibilityRole={open ? "button" : undefined}
			accessibilityState={{ checked: seen }}
			disabled={!open}
			onPress={open}
			className={cn(
				row({ state: "rest" }),
				"flex-row items-center",
				open && "active:bg-wash-press",
			)}
		>
			<Glyph icon={seen ? CircleCheck : Ring} tone={seen ? "ok" : "ink-meta"} />
			<RNText
				numberOfLines={1}
				className={cn(text({ role: "code" }), "min-w-0 flex-1")}
			>
				{path}
			</RNText>
			<View className="flex-row gap-inside">
				<RNText className={cn(text({ role: "meta" }), "text-ok")}>
					+{added}
				</RNText>
				<RNText className={cn(text({ role: "meta" }), "text-danger")}>
					−{removed}
				</RNText>
			</View>
		</Pressable>
	);
}
