// plugins/solid-ui/src/ui/components/toolbar/index.tsx
import { rhythm } from "@fcalell/ui-core/variants";
import type { JSX } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";

// One row of controls over a list: a picker, a segmented control, a search
// field, a switch.
export type ToolbarProps = Closed & { children?: JSX.Element };

export function Toolbar(props: ToolbarProps) {
	return (
		<div class={cn(rhythm({ unit: "row" }), "flex flex-wrap items-center")}>
			{props.children}
		</div>
	);
}

// plugins/native-ui/src/ui/components/toolbar/index.tsx
import type { ReactNode } from "react";
import { View } from "react-native";
import type { Closed } from "../../lib/closed";

export interface ToolbarProps extends Closed {
	children?: ReactNode;
}

// One row of controls over a list: a picker, a segmented control, a search
// field, a switch.
export function Toolbar({ children }: ToolbarProps) {
	return (
		<View className="flex-row flex-wrap items-center gap-row">{children}</View>
	);
}
