// plugins/solid-ui/src/ui/components/shell/index.tsx
import type { PlaceSpec } from "@fcalell/ui-core/descriptors";
import { PLACE_ROW_SELECTED, place } from "@fcalell/ui-core/variants";
import { A, useLocation } from "@solidjs/router";
import { For, type JSX, Show } from "solid-js";
import { Dynamic } from "solid-js/web";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { useIcon } from "#lib/icons.tsx";
import { dismissToast, toasts } from "#lib/toast.ts";
import { Count } from "../count/index.tsx";
import { Toast } from "../toast/index.tsx";

// The frame at every width: the places as the system's tab bar under tablet
// and as the labelled sidebar from tablet, the app's banner under the top bar,
// the composed content, and the toast queue. A consumer with no places has no
// shell.
export type ShellProps = Closed & {
	places: PlaceSpec<string>[];
	banner?: JSX.Element;
	children?: JSX.Element;
};

function PlaceGlyph(props: { name: string; selected: boolean }) {
	return (
		<Dynamic
			component={useIcon(props.name)}
			class={cn(
				"size-6 shrink-0",
				place({ state: props.selected ? "selected" : "idle" }),
			)}
			aria-hidden="true"
		/>
	);
}

export function Shell(props: ShellProps) {
	const location = useLocation();
	const selected = (spec: PlaceSpec<string>) =>
		location.pathname === spec.route ||
		location.pathname.startsWith(`${spec.route}/`);
	return (
		<div class="flex h-dvh flex-col bg-canvas tablet:flex-row">
			<nav class="hidden w-rail shrink-0 flex-col gap-pair border-r p-stack tablet:flex">
				<For each={props.places}>
					{(spec) => (
						<A
							href={spec.route}
							aria-current={selected(spec) ? "page" : undefined}
							class={cn(
								place({ state: selected(spec) ? "selected" : "idle" }),
								"flex min-h-11 items-center gap-row rounded-group px-stack hover:bg-edge focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tint",
								selected(spec) && PLACE_ROW_SELECTED,
							)}
						>
							<PlaceGlyph name={spec.icon} selected={selected(spec)} />
							<span class="flex-1 text-body">{spec.label}</span>
							<Show when={spec.count}>
								{(count) => <Count value={count()} />}
							</Show>
						</A>
					)}
				</For>
			</nav>
			<div class="relative flex min-h-0 flex-1 flex-col bg-surface">
				{props.banner}
				<main class="flex min-h-0 flex-1 flex-col">{props.children}</main>
				<div class="pointer-events-none absolute inset-x-0 bottom-inset z-50 flex flex-col items-center gap-row">
					<For each={toasts()}>
						{(entry) => (
							<div class="pointer-events-auto">
								<Toast
									sentence={entry.sentence}
									act={
										entry.act
											? {
													...entry.act,
													onAct: () => {
														dismissToast(entry.id);
														entry.act?.onAct();
													},
												}
											: undefined
									}
								/>
							</div>
						)}
					</For>
				</div>
			</div>
			<nav class="flex border-t bg-canvas pb-[env(safe-area-inset-bottom)] tablet:hidden">
				<For each={props.places}>
					{(spec) => (
						<A
							href={spec.route}
							aria-current={selected(spec) ? "page" : undefined}
							class={cn(
								place({ state: selected(spec) ? "selected" : "idle" }),
								"relative flex min-h-11 flex-1 flex-col items-center justify-center gap-pair py-row",
							)}
						>
							<PlaceGlyph name={spec.icon} selected={selected(spec)} />
							<span>{spec.label}</span>
							<Show when={spec.count}>
								{(count) => (
									<span class="absolute top-pair right-1/4">
										<Count value={count()} />
									</span>
								)}
							</Show>
						</A>
					)}
				</For>
			</nav>
		</div>
	);
}

// plugins/native-ui/src/ui/components/shell/index.tsx
import type { PlaceSpec } from "@fcalell/ui-core/descriptors";
import { HAIRLINE, place } from "@fcalell/ui-core/variants";
import type { ReactNode } from "react";
import { Pressable, Text as RNText, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { Glyph } from "../../lib/glyph";
import { useIcon } from "../../lib/icons";
import { navigate, usePathname } from "../../lib/navigate";
import { SwitcherContext } from "../../lib/switcher";
import { dismissToast, useToasts } from "../../lib/toast";
import { Count } from "../count";
import { Toast } from "../toast";
import { Confirmations } from "./confirmation";

export interface ShellProps extends Closed {
	places: readonly PlaceSpec<string>[];
	banner?: ReactNode;
	switcher?: ReactNode;
	children?: ReactNode;
}

// The frame: the banner under the top, the content, the toast queue above
// the bar, the `confirm()` decisions as a sheet, and the system-style tab bar with a hairline, icon over label and
// a count where a place has one. `switcher` (what switches what the app is
// looking at) starts each `Place`'s top bar, never a `Screen`'s: the tab
// bar holds places only.
export function Shell({ places, banner, switcher, children }: ShellProps) {
	const insets = useSafeAreaInsets();
	const pathname = usePathname();
	const toasts = useToasts();
	return (
		<View className="flex-1 bg-canvas">
			{banner ? <View style={{ paddingTop: insets.top }}>{banner}</View> : null}
			<View className="flex-1">
				<SwitcherContext.Provider value={switcher}>
					{children}
				</SwitcherContext.Provider>
			</View>
			{toasts.length > 0 ? (
				<View
					pointerEvents="box-none"
					className="absolute inset-x-0 bottom-0 items-center gap-inside p-card"
				>
					{toasts.map((entry) => (
						<Pressable key={entry.id} onPress={() => dismissToast(entry.id)}>
							<Toast
								sentence={entry.sentence}
								state={entry.state}
								act={entry.act}
							/>
						</Pressable>
					))}
				</View>
			) : null}
			<View
				accessibilityRole="tablist"
				style={{ paddingBottom: insets.bottom }}
				className={cn("flex-row border-t bg-canvas", HAIRLINE)}
			>
				{places.map((spec) => (
					<PlaceTab
						key={spec.route}
						spec={spec}
						selected={
							pathname === spec.route || pathname.startsWith(`${spec.route}/`)
						}
					/>
				))}
			</View>
			<Confirmations />
		</View>
	);
}

function PlaceTab({
	spec,
	selected,
}: {
	spec: PlaceSpec<string>;
	selected: boolean;
}) {
	const state = selected ? "selected" : "idle";
	return (
		<Pressable
			accessibilityRole="tab"
			accessibilityState={{ selected }}
			accessibilityLabel={spec.label}
			onPress={() => navigate(spec.route)}
			className="min-h-11 flex-1 items-center gap-pair py-inside"
		>
			<View className="flex-row items-start">
				<Glyph
					icon={useIcon(spec.icon)}
					tone={selected ? "accent" : "ink-meta"}
					size={24}
				/>
				{spec.count !== undefined && spec.count > 0 ? (
					<Count value={spec.count} />
				) : null}
			</View>
			<RNText className={place({ state })}>{spec.label}</RNText>
		</Pressable>
	);
}
