// plugins/react-ui/src/ui/components/message/index.tsx
import { Button as BaseButton } from "@base-ui/react/button";
import { cn } from "@fcalell/ui-core/cn";
import {
	lineBox,
	MESSAGE_BUBBLE,
	MESSAGE_HEAD,
	MESSAGE_LINE,
	MESSAGE_OPEN,
	message,
	skeleton,
	text,
	textStrong,
} from "@fcalell/ui-core/variants";
import type { Closed } from "../../lib/closed.ts";
import { moment } from "../../lib/moment.ts";
import { Icon } from "../icon/index.tsx";
import { Prose } from "../prose/index.tsx";

const STACK = "flex flex-col";
const YOURS = "flex flex-col items-end";
const SYSTEM = "flex items-center justify-center text-center";
const LINE_TEXT = "inline-flex flex-wrap justify-center min-w-0";
const OPEN =
	"inline-flex items-center min-w-0 hover:bg-wash-hover active:bg-wash-press";
const HEAD = "flex items-baseline";
// Read before the body, never drawn: the speaker `other` shows.
const HIDDEN_HEAD = "sr-only";
const BUBBLE = "max-w-4/5";
// A token too long for the line (a link, a hash) breaks anywhere.
const BODY = "whitespace-pre-wrap wrap-anywhere";
const WORDS = "min-w-0 wrap-anywhere";
const LINE = "flex items-center h-lh";
const BAR = "w-full";
// A time reads as one unit: it never shrinks or breaks beside a long line.
const TIME = "shrink-0 whitespace-nowrap";
// A loading reply: one paragraph of three lines, each bar at its line's length.
const REPLY_BARS = ["w-full", "w-full", "w-2/3"] as const;

interface MessageBase extends Closed {
	/** What was said: plain text for `you` and `system`, markdown for `other`. */
	body: string;
	/** When it was said, an ISO moment: drawn as the time today, else the date and time. */
	at?: string;
	/** The message waits: its author's form as bars in their line boxes. */
	loading?: boolean;
}

/** One turn of a thread, by its author. */
export type MessageProps =
	| (MessageBase & {
			/** `you`, a bubble at the column's end; `other`, a reply read as Prose under its name. */
			author: "you" | "other";
			/** Who said it: drawn over `other`'s reply, read aloud before yours. */
			name?: string;
			onOpen?: never;
	  })
	| (MessageBase & {
			/** `system`, one meta line centred in the thread. */
			author: "system";
			/** Opens what the line names: the line becomes the act, a chevron after it. */
			onOpen?: () => void;
			name?: never;
	  });

/** Yours a bubble on the group ground at the column's end, the time under it; another's the name at body 500 beside the time over the reply as Prose; a system line one meta line centred in a row at the target height, its time beside it. */
export function Message(props: MessageProps) {
	const { author, body, at, loading } = props;
	const time = at ? (
		<time dateTime={at} className={cn(text({ role: "meta" }), TIME)}>
			{moment(at)}
		</time>
	) : null;
	if (author === "system") {
		if (loading)
			return (
				<div aria-busy className={cn(message({ author }), SYSTEM)}>
					<span className={cn(lineBox({ role: "meta" }), LINE, "w-1/3")}>
						<span className={cn(skeleton({ kind: "line" }), BAR)} />
					</span>
				</div>
			);
		const words = (
			<span className={cn(text({ role: "meta" }), WORDS)}>{body}</span>
		);
		return (
			<div className={cn(message({ author }), SYSTEM)}>
				{props.onOpen ? (
					<BaseButton onClick={props.onOpen} className={cn(MESSAGE_OPEN, OPEN)}>
						{words}
						{time}
						<Icon name="ChevronRight" fit="meta" />
					</BaseButton>
				) : (
					<p className={cn(MESSAGE_LINE, LINE_TEXT)}>
						{words}
						{time}
					</p>
				)}
			</div>
		);
	}
	const { name } = props;
	if (author === "you") {
		if (loading)
			return (
				<article aria-busy className={cn(message({ author }), YOURS)}>
					<div className={cn(MESSAGE_BUBBLE, "w-1/2")}>
						<span className={cn(lineBox({ role: "body" }), LINE)}>
							<span className={cn(skeleton({ kind: "line" }), BAR)} />
						</span>
					</div>
				</article>
			);
		return (
			<article className={cn(message({ author }), YOURS)}>
				{name ? <p className={HIDDEN_HEAD}>{name}</p> : null}
				<div className={cn(MESSAGE_BUBBLE, BUBBLE)}>
					<p className={cn(text({ role: "body" }), BODY)}>{body}</p>
				</div>
				{time}
			</article>
		);
	}
	if (loading)
		return (
			<article aria-busy className={cn(message({ author }), STACK)}>
				<span className={cn(lineBox({ role: "body" }), LINE)}>
					<span className={cn(skeleton({ kind: "line" }), "w-1/5")} />
				</span>
				<div className={STACK}>
					{REPLY_BARS.map((width, line) => (
						<span
							// biome-ignore lint/suspicious/noArrayIndexKey: the lines are fixed stand-ins
							key={line}
							className={cn(lineBox({ role: "body" }), LINE)}
						>
							<span className={cn(skeleton({ kind: "line" }), width)} />
						</span>
					))}
				</div>
			</article>
		);
	return (
		<article className={cn(message({ author }), STACK)}>
			{name || time ? (
				<p className={cn(MESSAGE_HEAD, HEAD)}>
					{name ? (
						<span
							className={cn(
								text({ role: "body" }),
								textStrong({ role: "body" }),
							)}
						>
							{name}
						</span>
					) : null}
					{time}
				</p>
			) : null}
			<Prose markdown={body} />
		</article>
	);
}

// plugins/solid-ui/src/ui/components/message/index.tsx
import { type MessageAuthor, message, text } from "@fcalell/ui-core/variants";
import { Show } from "solid-js";
import { ageOf, momentOf, useClock } from "#lib/age.ts";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { RING } from "#lib/interact.ts";
import { LoadingRows } from "#lib/loading.tsx";
import { Prose } from "../prose/index.tsx";

// One message of a thread: `you` in a soft bubble right, `other` as prose on
// the surface with the name above when given, `system` as one centered meta
// line. The body streams.
export type MessageProps = Closed & {
	author: MessageAuthor;
	name?: string;
	body: string;
	// An ISO moment, drawn as its age.
	at?: string;
	// A system line that opens something, such as a relay's provenance: the
	// line becomes the act.
	onOpen?: () => void;
	loading?: boolean;
};

export function Message(props: MessageProps) {
	const clock = useClock();
	return (
		<Show when={!props.loading} fallback={<LoadingRows />}>
			<article
				class={cn(
					"flex flex-col gap-pair",
					props.author === "you" && "items-end",
					props.author === "system" && "items-center",
				)}
			>
				<Show when={props.author === "other" && props.name}>
					<p class={text({ role: "label" })}>{props.name}</p>
				</Show>
				<div
					class={cn(
						message({ author: props.author }),
						props.author === "you" && "max-w-[85%]",
						props.author === "system" && "text-center",
					)}
				>
					<Show
						when={props.author === "other"}
						fallback={
							<Show when={props.onOpen} fallback={<span>{props.body}</span>}>
								<button
									type="button"
									onClick={() => props.onOpen?.()}
									class={cn("min-h-11 cursor-pointer rounded-group", RING)}
								>
									{props.body}
								</button>
							</Show>
						}
					>
						<Prose markdown={props.body} />
					</Show>
				</div>
				<Show when={props.at}>
					{(at) => (
						<time
							datetime={at()}
							title={momentOf(at())}
							class={cn(text({ role: "meta" }), "tabular-nums")}
						>
							{ageOf(at(), clock())}
						</time>
					)}
				</Show>
			</article>
		</Show>
	);
}
