// plugins/solid-ui/src/ui/components/text-area/index.tsx
import { commitMoment } from "@fcalell/ui-core/commit";
import { field, text } from "@fcalell/ui-core/variants";
import { Show } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { useField, useFieldName } from "#lib/field.ts";

// Multi-line typing. `source` is mono and keeps indentation; `budget` is a
// word budget and draws a counter under the field. Inside a `FormField` its
// label names it; bare in a `Sheet`, the sheet's title does. `onCommit` hears
// the value once the viewer leaves the field having changed it since focus
// (Enter is a new line here); with it, Escape puts back the value at focus.
export type TextAreaProps = Closed & {
	kind?: "prose" | "source";
	value: string;
	onChange: (value: string) => void;
	onCommit?: (value: string) => void;
	placeholder?: string;
	budget?: number;
};

function wordCount(value: string): number {
	return value.split(/\s+/).filter(Boolean).length;
}

export function TextArea(props: TextAreaProps) {
	const ctx = useField();
	const name = useFieldName();
	const moment = commitMoment<string>();
	const commit = (value: string) => props.onCommit?.(value);
	const source = () => props.kind === "source";
	const count = () => wordCount(props.value);
	const over = () => props.budget !== undefined && count() > props.budget;
	return (
		<div class="flex flex-col gap-pair">
			<textarea
				id={ctx?.id}
				aria-labelledby={name}
				rows={4}
				value={props.value}
				placeholder={props.placeholder}
				spellcheck={!source()}
				aria-invalid={ctx?.invalid() || over() ? "true" : undefined}
				onInput={(event) => props.onChange(event.currentTarget.value)}
				onFocus={(event) => moment.focus(event.currentTarget.value)}
				onBlur={(event) => moment.leave(event.currentTarget.value, commit)}
				onKeyDown={(event) => {
					if (props.onCommit && event.key === "Escape")
						moment.cancel(event.currentTarget.value, props.onChange);
				}}
				class={cn(
					field({ kind: source() ? "code" : "text", state: "default" }),
					"min-h-28 w-full resize-y outline-none focus-visible:border-tint aria-invalid:border-danger",
					"placeholder:text-ink-faint",
					source() && "whitespace-pre",
				)}
			/>
			<Show when={props.budget}>
				{(budget) => (
					<p
						class={cn(
							text({ role: "meta" }),
							"text-right tabular-nums",
							over() && "text-danger",
						)}
					>
						{count()} / {budget()}
					</p>
				)}
			</Show>
		</div>
	);
}

// plugins/react-ui/src/ui/components/text-area/index.tsx
import { Input as Control } from "@base-ui/react/input";
import { cn } from "@fcalell/ui-core/cn";
import {
	fieldValue,
	TEXT_AREA_VALUE,
	textArea,
	textAreaBudget,
} from "@fcalell/ui-core/variants";
import type { Closed } from "../../lib/closed.ts";
import { useCommit } from "../../lib/commit.ts";

// The box draws the field's states, as `Input`'s does.
const BOX = "flex flex-col";
const BOX_HOVER = "hover:border-edge-hover";
const BOX_FOCUS =
	"has-focus-visible:outline-2 has-focus-visible:outline-offset-2 has-focus-visible:outline-ring";
const BOX_DISABLED = "bg-fill-disabled";
const VALUE =
	"block w-full resize-none field-sizing-content outline-none placeholder:text-ink-meta disabled:text-ink-disabled";
const BUDGET_LINE = "flex justify-end";
const BUDGET_DISABLED = "text-ink-disabled";

function wordCount(value: string): number {
	return value.split(/\s+/).filter(Boolean).length;
}

/** Many lines of typing, the control a `FormField` labels, describes and marks in error. */
export interface TextAreaProps extends Closed {
	/** What is typed: `prose` (the default) or `source` (mono, a machine reads it). */
	kind?: "prose" | "source";
	/** The value. */
	value: string;
	/** Hears every keystroke's value. */
	onChange: (value: string) => void;
	/** Hears the value once the viewer leaves the field having changed it since focus (Enter is a new line); Escape then puts back the value at focus. */
	onCommit?: (value: string) => void;
	/** The hint drawn while the value is empty; never the field's name. */
	placeholder?: string;
	/** A word budget: draws the count against it, in the error ink once over. */
	budget?: number;
}

/** A field box that grows with its value, the budget's count under the value. */
export function TextArea({
	kind,
	value,
	onChange,
	onCommit,
	placeholder,
	budget,
}: TextAreaProps) {
	const source = kind === "source";
	const commit = useCommit(value, onChange, onCommit, false);
	const count = budget === undefined ? undefined : wordCount(value);
	return (
		<Control
			value={value}
			onValueChange={(next) => onChange(next)}
			{...commit}
			autoCapitalize={source ? "off" : undefined}
			spellCheck={source ? false : undefined}
			placeholder={placeholder}
			// Base UI's Field wires the control; the render function hands over its
			// props and state so the box around the value draws that state.
			render={(control, state) => (
				<div
					className={cn(
						textArea({ state: state.valid === false ? "error" : "rest" }),
						BOX,
						BOX_FOCUS,
						state.disabled ? BOX_DISABLED : state.valid !== false && BOX_HOVER,
					)}
				>
					<textarea
						{...control}
						className={cn(
							fieldValue({ kind: source ? "code" : "text" }),
							TEXT_AREA_VALUE,
							VALUE,
						)}
					/>
					{count !== undefined && budget !== undefined ? (
						<div className={BUDGET_LINE}>
							<span
								className={cn(
									textAreaBudget({ state: count > budget ? "error" : "rest" }),
									state.disabled && BUDGET_DISABLED,
								)}
							>
								{count} / {budget}
							</span>
						</div>
					) : null}
				</div>
			)}
		/>
	);
}
