// plugins/solid-ui/src/ui/components/prose-diff/index.tsx
import { text } from "@fcalell/ui-core/variants";
import { diffWords } from "diff";
import { createMemo, For, Show } from "solid-js";
import type { Closed } from "#lib/closed";
import { cn } from "#lib/cn";
import { LoadingRows } from "#lib/loading";

// Prose with an added run on the ok soft and a removed one on the danger
// soft, struck through.
export type ProseDiffProps = Closed & {
	before: string;
	after: string;
	loading?: boolean;
};

export function ProseDiff(props: ProseDiffProps) {
	const changes = createMemo(() => diffWords(props.before, props.after));
	return (
		<Show when={!props.loading} fallback={<LoadingRows />}>
			<p
				class={cn(
					text({ role: "body" }),
					"max-w-reading whitespace-pre-wrap break-words",
				)}
			>
				<For each={changes()}>
					{(change) => (
						<Show
							when={change.added || change.removed}
							fallback={<span>{change.value}</span>}
						>
							<Show
								when={change.added}
								fallback={
									<del class="bg-danger-soft line-through">{change.value}</del>
								}
							>
								<ins class="bg-ok-soft no-underline">{change.value}</ins>
							</Show>
						</Show>
					)}
				</For>
			</p>
		</Show>
	);
}

// plugins/native-ui/src/ui/components/prose-diff/index.tsx
import { text } from "@fcalell/ui-core/variants";
import { diffWords } from "diff";
import { Text as RNText } from "react-native";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { LoadingRows } from "../../lib/loading";

export interface ProseDiffProps extends Closed {
	before: string;
	after: string;
	loading?: boolean;
}

// Prose with an added run on ok-soft and a removed one on danger-soft,
// struck through.
export function ProseDiff({ before, after, loading }: ProseDiffProps) {
	if (loading) return <LoadingRows />;
	const parts = diffWords(before, after);
	return (
		<RNText className={text({ role: "body" })}>
			{parts.map((part, index) => (
				<RNText
					// biome-ignore lint/suspicious/noArrayIndexKey: runs are positional
					key={index}
					className={cn(
						part.added && "bg-ok-soft",
						part.removed && "bg-danger-soft line-through",
					)}
				>
					{part.value}
				</RNText>
			))}
		</RNText>
	);
}
