// plugins/react-ui/src/ui/components/item-header/index.tsx
import { cn } from "@fcalell/ui-core/cn";
import type {
	OptionPick,
	Part,
	StatusState,
} from "@fcalell/ui-core/descriptors";
import {
	ITEM_FACT,
	ITEM_FACTS,
	ITEM_HEADER,
	lineBox,
	SKELETON_LINES,
	skeleton,
	skeletonRow,
	text,
} from "@fcalell/ui-core/variants";
import { use } from "react";
import type { Closed } from "../../lib/closed.ts";
import { OverThread } from "../../lib/frame.ts";
import { HeadingContext } from "../../lib/heading.ts";
import { useTouch } from "../../lib/media.ts";
import { joinParts, META_CUT, partText } from "../../lib/parts.ts";
import { Count } from "../count/index.tsx";
import { Picker } from "../picker/index.tsx";
import { Status } from "../status/index.tsx";
import { COLUMN_FILLED } from "../thread/fill.ts";

const HEAD = "flex flex-col";
const OVERLINE = "truncate";
const FACTS = "flex flex-wrap items-center";
const FACT = "inline-flex items-center";
// A pick in the facts line pulls back at its start as well as its end, so its
// dot and word sit where a plain fact's would.
const PICK = "inline-flex -ms-inside";
// A loading line stands in its text's line box, so the loading head keeps
// the loaded head's height.
const LINE_WAIT = "flex items-center h-lh";
// On touch the facts wrap to a second line, which the loading head reserves.
const WRAP_WAIT = "hidden touch:flex items-center h-lh";
const FACTS_WAIT = "flex flex-col";
const FACTS_LINE_WAIT = "flex items-center";
const COUNT_WAIT = "inline-flex shrink-0";

/** One fact under the title: words, a status, a status that moves (a pick whose options carry states), or a count beside its word. */
export type Fact<V extends string | null = string> =
	| Part
	| { status: StatusState; label?: string }
	| { pick: OptionPick<V> }
	| { count: number; label: string };

/** A record's head. */
export interface ItemHeaderProps<V extends string | null = string>
	extends Closed {
	/** The parts that place the record (its project, key, cycle), joined by a middle dot over the title. */
	overline?: readonly Part[];
	/** The record's name, wrapping in full. */
	title: Part;
	/** The facts in a wrapping line under the title. */
	facts?: readonly Fact<V>[];
	/** Bars in each line's box stand in for the head, at its height. */
	loading?: boolean;
}

function factKey<V extends string | null>(fact: Fact<V>): string {
	if (typeof fact === "object" && "pick" in fact) return fact.pick.label;
	if (typeof fact === "object" && "status" in fact)
		return `${fact.status} ${fact.label ?? ""}`;
	if (typeof fact === "object" && "count" in fact)
		return `${fact.count} ${fact.label}`;
	return partText(fact);
}

function FactPart<V extends string | null>({ fact }: { fact: Fact<V> }) {
	if (typeof fact === "object" && "pick" in fact)
		return (
			<span className={PICK}>
				<Picker {...fact.pick} fit="row" />
			</span>
		);
	if (typeof fact === "object" && "status" in fact)
		return <Status state={fact.status} label={fact.label} />;
	if (typeof fact === "object" && "count" in fact)
		return (
			<span className={cn(ITEM_FACT, FACT)}>
				<span className={text({ role: "meta" })}>{fact.label}</span>
				<Count value={fact.count} />
			</span>
		);
	return (
		<span className={text({ role: "meta" })}>{partText(fact, META_CUT)}</span>
	);
}

/** The overline, the title at the heading role and the facts, a pair apart whether the title wraps or not. The title is a heading at the level where the header stands. Over a Thread filling a Split's main it stands in the Thread's column on the desktop. */
export function ItemHeader<V extends string | null = string>({
	overline,
	title,
	facts,
	loading,
}: ItemHeaderProps<V>) {
	const level = use(HeadingContext);
	const Heading = `h${level}` as const;
	// The column is a structure that follows density, as the Thread's is.
	const overThread = use(OverThread);
	const touch = useTouch();
	const column = overThread && !touch && COLUMN_FILLED;
	if (loading)
		return (
			<div aria-busy className={cn(ITEM_HEADER, HEAD, column)}>
				<span className={cn(lineBox({ role: "meta" }), LINE_WAIT)}>
					<span className={cn(skeleton({ kind: "line" }), "w-1/4")} />
				</span>
				<span className={cn(lineBox({ role: "heading" }), LINE_WAIT)}>
					<span className={cn(skeleton({ kind: "line" }), "w-1/2")} />
				</span>
				<span className={cn(SKELETON_LINES, FACTS_WAIT)}>
					<span className={cn(skeletonRow({ kind: "facts" }), FACTS_LINE_WAIT)}>
						<span className={cn(skeleton({ kind: "line" }), "w-1/3")} />
						<span className={cn(skeleton({ kind: "count" }), COUNT_WAIT)} />
					</span>
					<span className={cn(lineBox({ role: "meta" }), WRAP_WAIT)}>
						<span className={cn(skeleton({ kind: "line" }), "w-1/2")} />
					</span>
				</span>
			</div>
		);
	return (
		<header className={cn(ITEM_HEADER, HEAD, column)}>
			{overline && overline.length > 0 ? (
				<p className={cn(text({ role: "meta" }), OVERLINE)}>
					{joinParts(overline, META_CUT)}
				</p>
			) : null}
			<Heading className={text({ role: "heading" })}>{partText(title)}</Heading>
			{facts && facts.length > 0 ? (
				<div className={cn(ITEM_FACTS, FACTS)}>
					{facts.map((fact) => (
						<FactPart key={factKey(fact)} fact={fact} />
					))}
				</div>
			) : null}
		</header>
	);
}

// plugins/solid-ui/src/ui/components/item-header/index.tsx
import type { Part } from "@fcalell/ui-core/descriptors";
import type { StatusState } from "@fcalell/ui-core/tokens";
import { GROUP, text } from "@fcalell/ui-core/variants";
import { For, Show } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { Parts } from "#lib/parts.tsx";
import { Status } from "../status/index.tsx";

export type Fact = Part | { status: StatusState; label?: string };

// An id over a bold title, properties below: the overline's parts joined by a
// middle dot, the title wrapping to two lines, a row of statuses and meta.
export type ItemHeaderProps = Closed & {
	overline?: Part[];
	title: Part;
	facts?: Fact[];
	loading?: boolean;
};

function isStatus(fact: Fact): fact is { status: StatusState; label?: string } {
	return typeof fact === "object" && "status" in fact;
}

export function ItemHeader(props: ItemHeaderProps) {
	return (
		<Show
			when={!props.loading}
			fallback={
				<div class="flex flex-col gap-row">
					<div class={cn(GROUP, "h-4 w-1/3")} />
					<div class={cn(GROUP, "h-8 w-4/5")} />
					<div class={cn(GROUP, "h-4 w-1/2")} />
				</div>
			}
		>
			<header class="flex flex-col gap-pair">
				<Show when={props.overline?.length}>
					<p class={text({ role: "meta" })}>
						<Parts parts={props.overline ?? []} cut />
					</p>
				</Show>
				<h1 class={cn(text({ role: "title" }), "line-clamp-2")}>
					<Parts parts={[props.title]} />
				</h1>
				<Show when={props.facts?.length}>
					<div
						class={cn(
							text({ role: "meta" }),
							"flex flex-wrap items-center gap-row",
						)}
					>
						<For each={props.facts}>
							{(fact, index) => (
								<>
									<Show when={index() > 0}>
										<span aria-hidden="true">·</span>
									</Show>
									<Show
										when={isStatus(fact) && fact}
										fallback={<Parts parts={[fact as Part]} cut />}
									>
										{(status) => (
											<Status state={status().status} label={status().label} />
										)}
									</Show>
								</>
							)}
						</For>
					</div>
				</Show>
			</header>
		</Show>
	);
}
