// plugins/native-ui/src/ui/components/item-header/index.tsx
import type { Part, StatusState } from "@fcalell/ui-core/descriptors";
import { text } from "@fcalell/ui-core/variants";
import { useEffect } from "react";
import { Text as RNText, View } from "react-native";
import type { Closed } from "../../lib/closed";
import { useHeadingClaim } from "../../lib/heading";
import { LoadingRows } from "../../lib/loading";
import { joinParts, META_CUT, partText } from "../../lib/parts";
import { Status } from "../status";

// A status fact with `onOpen` is a chip that opens what it means.
export type Fact =
	| Part
	| { status: StatusState; label?: string; onOpen?: () => void };

export interface ItemHeaderProps extends Closed {
	overline?: readonly Part[];
	title: Part;
	facts?: readonly Fact[];
	loading?: boolean;
}

function factKey(fact: Fact): string {
	return typeof fact === "object" && "status" in fact
		? `${fact.status}:${fact.label ?? ""}`
		: partText(fact);
}

// An item's head: an overline over a bold title wrapping in full, the facts
// in a row below. Inside a `Screen` the title is the page's heading: the
// header claims it, loading included, so the title never draws twice.
export function ItemHeader({
	overline,
	title,
	facts,
	loading,
}: ItemHeaderProps) {
	const claim = useHeadingClaim();
	useEffect(() => {
		claim?.(true);
		return () => claim?.(false);
	}, [claim]);
	if (loading) return <LoadingRows />;
	return (
		<View className="gap-pair">
			{overline && overline.length > 0 ? (
				<RNText numberOfLines={1} className={text({ role: "meta" })}>
					{joinParts(overline, META_CUT)}
				</RNText>
			) : null}
			<RNText accessibilityRole="header" className={text({ role: "title" })}>
				{partText(title)}
			</RNText>
			{facts && facts.length > 0 ? (
				<View className="flex-row flex-wrap items-center gap-row">
					{facts.map((fact) =>
						typeof fact === "object" && "status" in fact ? (
							<Status
								key={factKey(fact)}
								state={fact.status}
								label={fact.label}
								onOpen={fact.onOpen}
							/>
						) : (
							<RNText key={factKey(fact)} className={text({ role: "meta" })}>
								{partText(fact, META_CUT)}
							</RNText>
						),
					)}
				</View>
			) : null}
		</View>
	);
}

// plugins/solid-ui/src/ui/components/item-header/index.tsx
import type { Part } from "@fcalell/ui-core/descriptors";
import type { StatusState } from "@fcalell/ui-core/tokens";
import { GROUP, text } from "@fcalell/ui-core/variants";
import { createEffect, createSignal, For, onCleanup, Show } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { useHeadingClaim } from "#lib/heading.ts";
import { Parts } from "#lib/parts.tsx";
import { Status } from "../status/index.tsx";

// A status fact with `onOpen` is a chip that opens what it means.
export type Fact =
	| Part
	| { status: StatusState; label?: string; onOpen?: () => void };

// An id over a bold title, properties below: the overline's parts joined by a
// middle dot, the title wrapping in full, a row of statuses and meta.
// Inside a `Screen` the title is the page's one heading: the header claims
// it from the screen, loading included, so the title never draws twice.
export type ItemHeaderProps = Closed & {
	overline?: Part[];
	title: Part;
	facts?: Fact[];
	loading?: boolean;
};

function isStatus(
	fact: Fact,
): fact is { status: StatusState; label?: string; onOpen?: () => void } {
	return typeof fact === "object" && "status" in fact;
}

export function ItemHeader(props: ItemHeaderProps) {
	const claim = useHeadingClaim();
	const [heading, setHeading] = createSignal<HTMLHeadingElement>();
	claim?.(null);
	createEffect(() => claim?.(heading() ?? null));
	onCleanup(() => claim?.(undefined));
	return (
		<Show
			when={!props.loading}
			fallback={
				<div class="flex flex-col gap-row">
					<div class={cn(GROUP, "h-4 w-1/3")} />
					<div class={cn(GROUP, "h-8 w-4/5")} />
					<div class={cn(GROUP, "h-4 w-1/2")} />
				</div>
			}
		>
			<header class="flex flex-col gap-pair">
				<Show when={props.overline?.length}>
					<p class={text({ role: "meta" })}>
						<Parts parts={props.overline ?? []} cut />
					</p>
				</Show>
				<h1 ref={setHeading} class={text({ role: "title" })}>
					<Parts parts={[props.title]} />
				</h1>
				<Show when={props.facts?.length}>
					<div
						class={cn(
							text({ role: "meta" }),
							"flex flex-wrap items-center gap-row",
						)}
					>
						<For each={props.facts}>
							{(fact, index) => (
								<>
									<Show when={index() > 0}>
										<span aria-hidden="true">·</span>
									</Show>
									<Show
										when={isStatus(fact) && fact}
										fallback={<Parts parts={[fact as Part]} cut />}
									>
										{(status) => (
											<Status
												state={status().status}
												label={status().label}
												onOpen={status().onOpen}
											/>
										)}
									</Show>
								</>
							)}
						</For>
					</div>
				</Show>
			</header>
		</Show>
	);
}
