// plugins/solid-ui/src/ui/components/text-area/index.tsx
import { commitMoment } from "@fcalell/ui-core/commit";
import { field, text } from "@fcalell/ui-core/variants";
import { Show } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { useField, useFieldName } from "#lib/field.ts";

// Multi-line typing. `source` is mono and keeps indentation; `budget` is a
// word budget and draws a counter under the field. Inside a `FormField` its
// label names it; bare in a `Sheet`, the sheet's title does. `onCommit` hears
// the value once the viewer leaves the field having changed it since focus
// (Enter is a new line here); with it, Escape puts back the value at focus.
export type TextAreaProps = Closed & {
	kind?: "prose" | "source";
	value: string;
	onChange: (value: string) => void;
	onCommit?: (value: string) => void;
	placeholder?: string;
	budget?: number;
};

function wordCount(value: string): number {
	return value.split(/\s+/).filter(Boolean).length;
}

export function TextArea(props: TextAreaProps) {
	const ctx = useField();
	const name = useFieldName();
	const moment = commitMoment<string>();
	const commit = (value: string) => props.onCommit?.(value);
	const source = () => props.kind === "source";
	const count = () => wordCount(props.value);
	const over = () => props.budget !== undefined && count() > props.budget;
	return (
		<div class="flex flex-col gap-pair">
			<textarea
				id={ctx?.id}
				aria-labelledby={name}
				rows={4}
				value={props.value}
				placeholder={props.placeholder}
				spellcheck={!source()}
				aria-invalid={ctx?.invalid() || over() ? "true" : undefined}
				onInput={(event) => props.onChange(event.currentTarget.value)}
				onFocus={(event) => moment.focus(event.currentTarget.value)}
				onBlur={(event) => moment.leave(event.currentTarget.value, commit)}
				onKeyDown={(event) => {
					if (props.onCommit && event.key === "Escape")
						moment.cancel(event.currentTarget.value, props.onChange);
				}}
				class={cn(
					field({ kind: source() ? "code" : "text", state: "default" }),
					"min-h-28 w-full resize-y outline-none focus-visible:border-tint aria-invalid:border-danger",
					"placeholder:text-ink-faint",
					source() && "whitespace-pre",
				)}
			/>
			<Show when={props.budget}>
				{(budget) => (
					<p
						class={cn(
							text({ role: "meta" }),
							"text-right tabular-nums",
							over() && "text-danger",
						)}
					>
						{count()} / {budget()}
					</p>
				)}
			</Show>
		</div>
	);
}

// plugins/native-ui/src/ui/components/text-area/index.tsx
import { commitMoment } from "@fcalell/ui-core/commit";
import { FIELD_PLACEHOLDER, field, text } from "@fcalell/ui-core/variants";
import { useEffect, useState } from "react";
import { Text as RNText, TextInput, View } from "react-native";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { useFieldName } from "../../lib/field";
import { useTouched } from "../../lib/touched";
import { useSheetGrow } from "../sheet";

export interface TextAreaProps extends Closed {
	kind?: "prose" | "source";
	value: string;
	onChange: (value: string) => void;
	onCommit?: (value: string) => void;
	placeholder?: string;
	budget?: number;
}

function wordCount(value: string): number {
	return value.split(/\s+/).filter(Boolean).length;
}

// Many lines of typing. `source` is mono and keeps indentation; a `budget` in
// words draws a counter. Inside a sheet it asks for the full height.
// `onCommit` hears the value once the viewer leaves the field having changed
// it since focus (return is a new line here); with it, a hardware Escape
// puts back the value at focus.
export function TextArea({
	kind,
	value,
	onChange,
	onCommit,
	placeholder,
	budget,
}: TextAreaProps) {
	const [focused, setFocused] = useState(false);
	const [moment] = useState(() => commitMoment<string>());
	const commit = (next: string) => onCommit?.(next);
	const { touch } = useTouched();
	const name = useFieldName();
	const source = kind === "source";
	const grow = useSheetGrow();
	useEffect(() => grow?.(), [grow]);
	const count = budget === undefined ? undefined : wordCount(value);
	return (
		<View className="gap-pair">
			<TextInput
				accessibilityLabel={name}
				multiline
				textAlignVertical="top"
				className={cn(
					field({
						kind: source ? "code" : "text",
						state: focused ? "focused" : "default",
					}),
					text({ role: source ? "mono" : "body" }),
					"min-h-20",
				)}
				placeholderTextColorClassName={FIELD_PLACEHOLDER}
				value={value}
				onChangeText={(next) => {
					touch();
					onChange(next);
				}}
				placeholder={placeholder}
				autoCapitalize={source ? "none" : "sentences"}
				autoCorrect={!source}
				onFocus={() => {
					setFocused(true);
					moment.focus(value);
				}}
				onBlur={() => {
					setFocused(false);
					moment.leave(value, commit);
				}}
				onKeyPress={(event) => {
					if (onCommit && event.nativeEvent.key === "Escape")
						moment.cancel(value, onChange);
				}}
			/>
			{count !== undefined ? (
				<RNText
					className={cn(
						text({ role: "meta" }),
						"text-right",
						budget !== undefined && count > budget && "text-danger",
					)}
				>
					{count} / {budget}
				</RNText>
			) : null}
		</View>
	);
}
