// plugins/react-ui/src/ui/components/screen/index.tsx
import type { Dialog } from "@base-ui/react/dialog";
import { cn } from "@fcalell/ui-core/cn";
import type { IconAct, MenuItem } from "@fcalell/ui-core/descriptors";
import {
	PAGE_BODY,
	PAGE_HEAD,
	PAGE_STRIP,
	PAGE_TOP_BAR,
	text,
} from "@fcalell/ui-core/variants";
import { type ReactNode, use, useEffect, useId, useState } from "react";
import type { Closed } from "../../lib/closed.ts";
import { CoverTabs, LendAct, PageTitle } from "../../lib/frame.ts";
import { HeadingContext } from "../../lib/heading.ts";
import { useTouch } from "../../lib/media.ts";
import { navigate } from "../../lib/navigate.ts";
import { useWords } from "../../lib/words.tsx";
import { IconButton } from "../icon-button/index.tsx";
import { Menu } from "../menu/index.tsx";
import { backGlyph, Details } from "../place/index.tsx";

// A screen is the size container a Split inside decides its regions by.
const SCREEN = "@container/page flex flex-col grow min-h-0";
const HEAD = "flex flex-col";
const ROW = "flex items-center";
const SPACER = "grow";
const TITLE = "min-w-0 grow truncate";
// The body fills the screen, so an EmptyState alone in it centres, and
// scrolls under the fixed head.
const BODY = "flex flex-col grow overflow-y-auto";

/** A pushed page. */
export interface ScreenProps extends Closed {
	/** The page's title, its one `h1`. */
	title: string;
	/** The route the back act returns to; none draws no back act. */
	back?: string;
	/** Icon acts after the title, in order. */
	actions?: IconAct[];
	/** The acts past the actions, in a menu under the more act. */
	more?: MenuItem[];
	/** The page's sections. */
	children?: ReactNode;
}

/** A page pushed over a place: the back act first and no filled act. On the desktop it stands in the shell's column under one strip; on touch the top bar (back, actions, more) stands over the title and the screen covers the tab bar. A Split inside decides its regions by the screen's width and lends it a Details act, drawn below `wide` of it. */
export function Screen({ title, back, actions, more, children }: ScreenProps) {
	const touch = useTouch();
	const words = useWords();
	const cover = use(CoverTabs);
	const [sheet, lend] = useState<Dialog.Handle<unknown>>();
	const titleId = useId();
	useEffect(() => {
		if (!cover) return;
		cover(true);
		return () => cover(false);
	}, [cover]);
	const fit = touch ? "body" : "bar";
	const backAct =
		back === undefined ? null : (
			<IconButton
				icon={backGlyph(touch)}
				fit={fit}
				label={words.back}
				onAct={() => navigate(back)}
			/>
		);
	const acts = (actions ?? []).map((action) => (
		<IconButton key={action.label} {...action} fit={fit} />
	));
	const details = sheet ? <Details sheet={sheet} fit={fit} /> : null;
	const overflow = more?.length ? (
		<Menu label={words.more} items={more} />
	) : null;
	const heading = (
		<h1 id={titleId} className={cn(text({ role: "title" }), TITLE)}>
			{title}
		</h1>
	);
	// The head is one tree on both densities, so crossing the density line
	// keeps its acts, their focus and an open sheet's trigger. Only the
	// title's place and the spacer differ, each a slot that holds `null` where
	// it does not draw, so the acts after it never shift.
	const head = (
		<header className={cn(touch && PAGE_HEAD, HEAD)}>
			<div className={cn(touch ? PAGE_TOP_BAR : PAGE_STRIP, ROW)}>
				{backAct}
				{touch ? null : heading}
				{touch ? <span className={SPACER} /> : null}
				{acts}
				{details}
				{overflow}
			</div>
			{touch ? heading : null}
		</header>
	);
	return (
		<LendAct value={lend}>
			<PageTitle value={titleId}>
				<HeadingContext value={2}>
					<div className={SCREEN}>
						{head}
						<div className={cn(PAGE_BODY, BODY)}>{children}</div>
					</div>
				</HeadingContext>
			</PageTitle>
		</LendAct>
	);
}

// plugins/solid-ui/src/ui/components/screen/index.tsx
import type { Act, IconAct } from "@fcalell/ui-core/descriptors";
import { text } from "@fcalell/ui-core/variants";
import { A } from "@solidjs/router";
import { ChevronLeft, Ellipsis } from "lucide-solid";
import {
	createEffect,
	createSignal,
	For,
	type JSX,
	onCleanup,
	Show,
} from "solid-js";
import { BarContext } from "#lib/bar.ts";
import { Circle, circle, glyph } from "#lib/circle.tsx";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { FitContext } from "#lib/fit.ts";
import { HeadingContext } from "#lib/heading.ts";
import { MeasureContext, measured } from "#lib/measure.ts";
import { useWords } from "#lib/words.tsx";
import { IconButton } from "../icon-button/index.tsx";
import { ListRow } from "../list-row/index.tsx";
import { Sheet } from "../sheet/index.tsx";

// A screen pushed over a place: a back circle, the compact title once the
// large one scrolls away, its actions; no tab bar. An `ItemHeader` inside
// claims the large title, so an item has one heading. The body is measured
// at the reading width, centred. On the phone it covers the
// shell; from tablet it sits in its slot. A pinned `ActionBar` child sits
// above the home indicator. `more` acts are labelled rows under the more
// circle, never circles of their own.
export type ScreenProps = Closed & {
	title: string;
	back?: string;
	actions?: IconAct<string>[];
	// Labelled acts under the more circle, after the actions past two: the
	// place for an act that is not a move, such as ending or removing.
	more?: Act[];
	children?: JSX.Element;
};

const SHOWN = 2;

export function Screen(props: ScreenProps) {
	const words = useWords();
	const [compact, setCompact] = createSignal(false);
	const [more, setMore] = createSignal(false);
	const [whole, setWhole] = createSignal(false);
	const [own, setOwn] = createSignal<HTMLHeadingElement>();
	const [claimed, setClaimed] = createSignal<HTMLElement | null | undefined>();
	// The compact title follows whichever heading is the page's: the screen's
	// own, or the one an item header claimed.
	createEffect(() => {
		const target = claimed() === undefined ? own() : claimed();
		if (!target) return;
		const observer = new IntersectionObserver(([entry]) => {
			setCompact(entry ? !entry.isIntersecting : false);
		});
		observer.observe(target);
		onCleanup(() => observer.disconnect());
	});
	const shown = () => (props.actions ?? []).slice(0, SHOWN);
	const rest = () => (props.actions ?? []).slice(SHOWN);
	return (
		<BarContext.Provider value="pinned">
			<HeadingContext.Provider value={setClaimed}>
				<MeasureContext.Provider value={setWhole}>
					<div class="fixed inset-0 z-40 flex flex-col bg-surface tablet:static tablet:z-auto tablet:min-h-0 tablet:flex-1">
						<FitContext.Provider value="bar">
							<header class="flex min-h-14 items-center gap-row px-inset tablet:px-section">
								<Show when={props.back}>
									{(back) => (
										<A
											href={back()}
											aria-label={words.back}
											class={circle("bar")}
										>
											<ChevronLeft class={glyph("bar")} aria-hidden="true" />
										</A>
									)}
								</Show>
								{/* The compact title repeats the h1 for the eye once it has
					    scrolled away; the h1 stays the accessible title. */}
								<span
									aria-hidden="true"
									class={cn(
										text({ role: "heading" }),
										"min-w-0 flex-1 truncate transition-opacity duration-(--duration-base) ease-ui",
										compact() ? "opacity-100" : "opacity-0",
									)}
								>
									{props.title}
								</span>
								<For each={shown()}>
									{(action) => (
										<IconButton
											icon={action.icon}
											label={action.label}
											onAct={action.onAct}
										/>
									)}
								</For>
								<Show when={rest().length + (props.more?.length ?? 0) > 0}>
									<Circle
										glyph={Ellipsis}
										label={words.more}
										onAct={() => setMore(true)}
									/>
								</Show>
							</header>
						</FitContext.Provider>
						<div class="flex min-h-0 flex-1 flex-col overflow-y-auto px-inset pb-section tablet:px-section">
							<div
								class={cn(
									"flex flex-1 shrink-0 flex-col gap-section *:shrink-0",
									measured(whole()),
								)}
							>
								<Show when={claimed() === undefined}>
									<h1 ref={setOwn} class={text({ role: "title" })}>
										{props.title}
									</h1>
								</Show>
								{props.children}
							</div>
						</div>
						<Sheet
							open={more()}
							onClose={() => setMore(false)}
							title={props.title}
						>
							<For each={rest()}>
								{(action) => (
									<ListRow
										leading={{ icon: action.icon }}
										title={action.label}
										onOpen={() => {
											setMore(false);
											action.onAct();
										}}
									/>
								)}
							</For>
							<For each={props.more ?? []}>
								{(act) => (
									<ListRow
										title={act.label}
										meta={act.blocked ? [act.blocked] : undefined}
										onOpen={
											act.blocked === undefined
												? () => {
														setMore(false);
														act.onAct();
													}
												: undefined
										}
									/>
								)}
							</For>
						</Sheet>
					</div>
				</MeasureContext.Provider>
			</HeadingContext.Provider>
		</BarContext.Provider>
	);
}
