// plugins/native-ui/src/ui/components/screen/index.tsx
import type { Act, IconAct } from "@fcalell/ui-core/descriptors";
import { HAIRLINE, text } from "@fcalell/ui-core/variants";
import { ChevronLeft, Ellipsis } from "lucide-react-native";
import {
	Children,
	isValidElement,
	type ReactNode,
	useCallback,
	useState,
} from "react";
import { Text as RNText, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Circle } from "../../lib/circle";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { HeadingContext } from "../../lib/heading";
import { Scroll } from "../../lib/hosts";
import { MoreSheet } from "../../lib/more";
import { navigate } from "../../lib/navigate";
import { useWords } from "../../lib/words";
import { ActionBar } from "../action-bar";
import { IconButton } from "../icon-button";
import { MessageInput } from "../message-input";

export interface ScreenProps extends Closed {
	title: string;
	back?: string;
	actions?: IconAct<string>[];
	// Labelled acts under the more circle, after the actions past two.
	more?: Act[];
	children?: ReactNode;
}

// At most two circles in the top bar; the rest open under a more circle.
const BAR_ACTIONS = 2;

// An item's large title scrolls away and the top bar takes it compact.
const COMPACT_AT = 48;

// A pushed screen: the top bar with the back circle and the title compact
// and centred, the side inset, the scroll. An `ItemHeader` inside claims the
// heading, and the top bar's title then shows once it scrolls away. A pinned
// ActionBar or MessageInput child sits above the home indicator; the screen
// lifts it out of the scroll itself.
export function Screen({
	title,
	back,
	actions,
	more: moreActs,
	children,
}: ScreenProps) {
	const insets = useSafeAreaInsets();
	const words = useWords();
	const [compact, setCompact] = useState(false);
	const [claimed, setClaimed] = useState(false);
	const claim = useCallback((next: boolean) => setClaimed(next), []);
	const [more, setMore] = useState(false);
	const acts = actions ?? [];
	const extra = moreActs ?? [];
	const shown =
		acts.length > BAR_ACTIONS || extra.length > 0
			? acts.slice(0, BAR_ACTIONS - 1)
			: acts;
	const rest = acts.slice(shown.length);
	const all = Children.toArray(children);
	const bar = all.find(
		(child) =>
			isValidElement(child) &&
			(child.type === ActionBar || child.type === MessageInput),
	);
	const body = all.filter((child) => child !== bar);
	return (
		<HeadingContext.Provider value={claim}>
			<View className="flex-1 bg-canvas">
				{/* The sides share the row's width equally, so the title stays
			    centred whatever each holds. */}
				<View
					style={{ paddingTop: insets.top }}
					className="min-h-11 flex-row items-center gap-row px-inset"
				>
					<View className="flex-1 flex-row items-center">
						{back !== undefined ? (
							<Circle
								icon={ChevronLeft}
								label={words.back}
								onAct={() => navigate(back)}
							/>
						) : null}
					</View>
					<RNText
						accessibilityRole={claimed ? undefined : "header"}
						importantForAccessibility={claimed ? "no" : "auto"}
						numberOfLines={1}
						className={cn(
							text({ role: "heading" }),
							"shrink text-center",
							claimed && !compact && "opacity-0",
						)}
					>
						{title}
					</RNText>
					<View className="flex-1 flex-row items-center justify-end gap-row">
						{shown.map((action) => (
							<IconButton key={action.label} {...action} />
						))}
						{rest.length + extra.length > 0 ? (
							<Circle
								icon={Ellipsis}
								label={words.more}
								onAct={() => setMore(true)}
							/>
						) : null}
					</View>
				</View>
				<Scroll
					className="flex-1"
					contentContainerClassName="grow gap-section px-inset pb-section"
					scrollEventThrottle={32}
					onScroll={(event) =>
						setCompact(event.nativeEvent.contentOffset.y > COMPACT_AT)
					}
				>
					{body}
				</Scroll>
				{bar ? (
					<View
						style={{ paddingBottom: insets.bottom + 8 }}
						className={cn("border-t bg-canvas px-inset pt-stack", HAIRLINE)}
					>
						{bar}
					</View>
				) : null}
				<MoreSheet
					title={title}
					open={more}
					onClose={() => setMore(false)}
					actions={rest}
					more={extra}
				/>
			</View>
		</HeadingContext.Provider>
	);
}

// plugins/solid-ui/src/ui/components/screen/index.tsx
import type { Act, IconAct } from "@fcalell/ui-core/descriptors";
import { text } from "@fcalell/ui-core/variants";
import { A } from "@solidjs/router";
import { ChevronLeft, Ellipsis } from "lucide-solid";
import {
	createEffect,
	createSignal,
	For,
	type JSX,
	onCleanup,
	Show,
} from "solid-js";
import { BarContext } from "#lib/bar.ts";
import { Circle, circle, glyph } from "#lib/circle.tsx";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { FitContext } from "#lib/fit.ts";
import { useCover } from "#lib/frame.ts";
import { HeadingContext } from "#lib/heading.ts";
import { MeasureContext, measured } from "#lib/measure.ts";
import { useWords } from "#lib/words.tsx";
import { IconButton } from "../icon-button/index.tsx";
import { ListRow } from "../list-row/index.tsx";
import { Sheet } from "../sheet/index.tsx";

// A screen pushed over a place: a back circle, the title compact and centred
// in the top bar, its actions; no tab bar. An `ItemHeader` inside claims the
// heading: the item's large title is the page's one heading, and the top
// bar's title appears once it scrolls away. The body is measured
// at the reading width, centred. On the phone it covers the
// shell; from tablet it sits in its slot. A pinned `ActionBar` child sits
// above the home indicator. `more` acts are labelled rows under the more
// circle, never circles of their own.
export type ScreenProps = Closed & {
	title: string;
	back?: string;
	actions?: IconAct<string>[];
	// Labelled acts under the more circle, after the actions past two: the
	// place for an act that is not a move, such as ending or removing.
	more?: Act[];
	children?: JSX.Element;
};

const SHOWN = 2;

export function Screen(props: ScreenProps) {
	const words = useWords();
	useCover();
	const [compact, setCompact] = createSignal(false);
	const [more, setMore] = createSignal(false);
	const [whole, setWhole] = createSignal(false);
	const [claimed, setClaimed] = createSignal<HTMLElement | null | undefined>();
	// Under a claim the top bar's title shows once the item's heading has
	// scrolled away; with no claim it is the heading and always shows.
	createEffect(() => {
		const target = claimed();
		if (!target) return;
		const observer = new IntersectionObserver(([entry]) => {
			setCompact(entry ? !entry.isIntersecting : false);
		});
		observer.observe(target);
		onCleanup(() => observer.disconnect());
	});
	const shown = () => (props.actions ?? []).slice(0, SHOWN);
	const rest = () => (props.actions ?? []).slice(SHOWN);
	return (
		<BarContext.Provider value="pinned">
			<HeadingContext.Provider value={setClaimed}>
				<MeasureContext.Provider value={setWhole}>
					<div class="fixed inset-x-0 top-(--banner-height) bottom-0 z-40 flex flex-col bg-surface tablet:static tablet:z-auto tablet:min-h-0 tablet:flex-1">
						<FitContext.Provider value="bar">
							{/* Three columns keep the title centred whatever the sides
				    hold: each side is at least its content, the title shrinks. */}
							<header class="grid min-h-14 grid-cols-[minmax(max-content,1fr)_minmax(0,auto)_minmax(max-content,1fr)] items-center gap-row px-inset tablet:px-section">
								<div class="flex items-center">
									<Show when={props.back}>
										{(back) => (
											<A
												href={back()}
												aria-label={words.back}
												class={circle("bar")}
											>
												<ChevronLeft class={glyph("bar")} aria-hidden="true" />
											</A>
										)}
									</Show>
								</div>
								<Show
									when={claimed() !== undefined}
									fallback={
										<h1
											class={cn(
												text({ role: "heading" }),
												"min-w-0 truncate text-center",
											)}
										>
											{props.title}
										</h1>
									}
								>
									{/* The item's heading is the accessible title; this
					    repeats it for the eye once it has scrolled away. */}
									<span
										aria-hidden="true"
										class={cn(
											text({ role: "heading" }),
											"min-w-0 truncate text-center transition-opacity duration-(--duration-base) ease-ui",
											compact() ? "opacity-100" : "opacity-0",
										)}
									>
										{props.title}
									</span>
								</Show>
								<div class="flex items-center justify-end gap-row">
									<For each={shown()}>
										{(action) => (
											<IconButton
												icon={action.icon}
												label={action.label}
												onAct={action.onAct}
											/>
										)}
									</For>
									<Show when={rest().length + (props.more?.length ?? 0) > 0}>
										<Circle
											glyph={Ellipsis}
											label={words.more}
											onAct={() => setMore(true)}
										/>
									</Show>
								</div>
							</header>
						</FitContext.Provider>
						<div class="flex min-h-0 flex-1 flex-col overflow-y-auto px-inset pb-section tablet:px-section">
							<div
								class={cn(
									"flex flex-1 shrink-0 flex-col gap-section *:shrink-0",
									measured(whole()),
								)}
							>
								{props.children}
							</div>
						</div>
						<Sheet
							open={more()}
							onClose={() => setMore(false)}
							title={props.title}
						>
							<For each={rest()}>
								{(action) => (
									<ListRow
										leading={{ icon: action.icon }}
										title={action.label}
										onOpen={() => {
											setMore(false);
											action.onAct();
										}}
									/>
								)}
							</For>
							<For each={props.more ?? []}>
								{(act) => (
									<ListRow
										title={act.label}
										meta={act.blocked ? [act.blocked] : undefined}
										onOpen={
											act.blocked === undefined
												? () => {
														setMore(false);
														act.onAct();
													}
												: undefined
										}
									/>
								)}
							</For>
						</Sheet>
					</div>
				</MeasureContext.Provider>
			</HeadingContext.Provider>
		</BarContext.Provider>
	);
}
