// plugins/solid-ui/src/ui/components/switch/index.tsx
import { SWITCH_THUMB, switchTrack, text } from "@fcalell/ui-core/variants";
import * as SwitchPrimitive from "@kobalte/core/switch";
import { Show } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { useRowLabel } from "#lib/row.ts";

// The label is part of the atom so the hit area is the whole line at the floor.
// With none, the `DefinitionRow` it is the value of names it by the row's label.
export type SwitchProps = Closed & {
	checked: boolean;
	onChange: (checked: boolean) => void;
	label?: string;
};

export function Switch(props: SwitchProps) {
	const rowLabel = useRowLabel();
	return (
		<SwitchPrimitive.Root
			checked={props.checked}
			onChange={props.onChange}
			class={cn(
				"relative flex min-h-floor w-full cursor-pointer items-center gap-row",
				props.label ? "justify-between" : "justify-end",
			)}
		>
			<SwitchPrimitive.Input
				class="peer"
				aria-labelledby={props.label ? undefined : rowLabel}
			/>
			<Show when={props.label}>
				<SwitchPrimitive.Label class={text({ role: "body" })}>
					{props.label}
				</SwitchPrimitive.Label>
			</Show>
			<SwitchPrimitive.Control
				class={cn(
					switchTrack({ state: props.checked ? "on" : "off" }),
					"inline-flex h-8 w-13 shrink-0 items-center px-0.5 transition-colors duration-(--duration-base) ease-ui peer-focus-visible:outline-2 peer-focus-visible:outline-offset-2 peer-focus-visible:outline-tint peer-disabled:opacity-50",
				)}
			>
				{/* 20px travel: 52 track − 2×2 padding − 28 thumb. */}
				<SwitchPrimitive.Thumb
					class={cn(
						SWITCH_THUMB,
						"size-7 shadow-float transition-transform duration-(--duration-base) ease-ui",
						props.checked && "translate-x-5",
					)}
				/>
			</SwitchPrimitive.Control>
		</SwitchPrimitive.Root>
	);
}

// plugins/react-ui/src/ui/components/switch/index.tsx
import { Switch as Base } from "@base-ui/react/switch";
import { cn } from "@fcalell/ui-core/cn";
import { switchThumb, switchTrack } from "@fcalell/ui-core/variants";
import type { Closed } from "../../lib/closed.ts";

// The switch element is the target-sized hit box, so a press anywhere in it
// toggles; the track inside draws the states and the focus ring.
const HIT =
	"group/toggle inline-flex shrink-0 items-center justify-center min-h-target min-w-target outline-none";
const RING =
	"group-focus-visible/toggle:outline-2 group-focus-visible/toggle:outline-offset-2 group-focus-visible/toggle:outline-ring";
const OFF =
	"inline-flex shrink-0 items-center justify-start group-not-aria-disabled/toggle:group-hover/toggle:bg-switch-off-hover group-not-aria-disabled/toggle:group-active/toggle:bg-switch-off-hover group-aria-disabled/toggle:bg-fill-disabled";
const ON =
	"inline-flex shrink-0 items-center justify-start group-not-aria-disabled/toggle:group-hover/toggle:bg-toggle-on-hover group-not-aria-disabled/toggle:group-active/toggle:bg-toggle-on-hover group-aria-disabled/toggle:bg-fill-disabled";
const THUMB =
	"transition-transform duration-fast ease-in-out data-disabled:bg-ink-disabled";

/** A setting that takes effect at once, on or off. */
export interface SwitchProps extends Closed {
	/** Whether it is on. */
	checked: boolean;
	/** Hears the next value when the viewer flips it. */
	onChange: (checked: boolean) => void;
	/** Its name, read aloud; the row around it draws the visible label. */
	label: string;
}

/** A track and its thumb, drawn alone inside a target-sized hit box. */
export function Switch({ checked, onChange, label }: SwitchProps) {
	const state = checked ? "on" : "off";
	// A field around it disables it through Base UI's field context, which
	// sets `aria-disabled` on the hit box and `data-disabled` on the thumb.
	return (
		<Base.Root
			checked={checked}
			onCheckedChange={(next) => onChange(next)}
			aria-label={label}
			className={HIT}
		>
			<span className={cn(switchTrack({ state }), checked ? ON : OFF, RING)}>
				<Base.Thumb className={cn(switchThumb({ state }), THUMB)} />
			</span>
		</Base.Root>
	);
}
