// plugins/native-ui/src/ui/components/empty-state/index.tsx
import type { Act } from "@fcalell/ui-core/descriptors";
import { text } from "@fcalell/ui-core/variants";
import type { ReactNode } from "react";
import { Text as RNText, View } from "react-native";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { Button } from "../button";

export interface EmptyStateProps extends Closed {
	title?: string;
	sentence: string;
	act?: Act;
	children?: ReactNode;
}

// One sentence and the way to make the first one; with a title it centers as
// a first screen. What the screen still has to show goes in the children.
export function EmptyState({
	title,
	sentence,
	act,
	children,
}: EmptyStateProps) {
	return (
		<View
			accessibilityRole="summary"
			className={cn(
				"items-center gap-stack py-room",
				title !== undefined && "flex-1 justify-center",
			)}
		>
			{title !== undefined ? (
				<RNText className={cn(text({ role: "heading" }), "text-center")}>
					{title}
				</RNText>
			) : null}
			<RNText className={cn(text({ role: "meta" }), "text-center")}>
				{sentence}
			</RNText>
			{act ? <Button act="secondary" {...act} /> : null}
			{children}
		</View>
	);
}

// plugins/solid-ui/src/ui/components/empty-state/index.tsx
import type { Act } from "@fcalell/ui-core/descriptors";
import { text } from "@fcalell/ui-core/variants";
import type { JSX } from "solid-js";
import { Show } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { Button } from "../button/index.tsx";

// One sentence and the way to make the first one; with `title` it centers as
// a first screen. What the screen still has to show goes in the children.
export type EmptyStateProps = Closed & {
	title?: string;
	sentence: string;
	act?: Act;
	children?: JSX.Element;
};

export function EmptyState(props: EmptyStateProps) {
	return (
		<div
			role="status"
			class={cn(
				"flex flex-col items-center gap-stack py-section text-center",
				props.title && "min-h-0 flex-1 justify-center",
			)}
		>
			<Show when={props.title}>
				<h1 class={text({ role: "title" })}>{props.title}</h1>
			</Show>
			<p class={cn(text({ role: "meta" }), "max-w-reading")}>
				{props.sentence}
			</p>
			<Show when={props.act}>
				{(act) => (
					<Button
						act="secondary"
						label={act().label}
						onAct={act().onAct}
						blocked={act().blocked}
						loading={act().loading}
					/>
				)}
			</Show>
			{props.children}
		</div>
	);
}
