// plugins/solid-ui/src/ui/components/form-field/index.tsx
import type { FieldBinding, FieldControl } from "@fcalell/ui-core/descriptors";
import { text, textStrong } from "@fcalell/ui-core/variants";
import { createUniqueId, type JSX, Show, untrack } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { FieldContext } from "#lib/field.ts";

// A labelled typing control in a form: the label over the control, the
// description under the label, the error under the control. Bound to a form
// field (`field={form.bind("name")}`), it draws the field's error and hands
// the control its value and change handler, and an autosaving binding's
// commit, so the control is one spread: `{(control) => <Input {...control} />}`.
export type FormFieldProps<V = unknown> = Closed & {
	label: string;
	description?: string;
} & (
		| {
				field?: never;
				error?: string;
				children?: JSX.Element;
		  }
		| {
				field: FieldBinding<V>;
				error?: never;
				children: (control: FieldControl<V>) => JSX.Element;
		  }
	);

export function FormField<V>(props: FormFieldProps<V>) {
	const id = createUniqueId();
	const error = () => props.field?.error ?? props.error;
	// The control reads the binding through getters, so it follows the form
	// without the render function running again.
	const control: FieldControl<V> = {
		get value() {
			return (props.field as FieldBinding<V>).value;
		},
		onChange: (value) => props.field?.onChange(value),
		get onCommit() {
			return props.field?.onCommit;
		},
	};
	const body = () => {
		const children = props.children;
		return typeof children === "function"
			? untrack(() => children(control))
			: children;
	};
	return (
		<FieldContext.Provider value={{ id, invalid: () => error() !== undefined }}>
			<div class="flex flex-col gap-pair">
				<label
					for={id}
					class={cn(text({ role: "body" }), textStrong({ role: "body" }))}
				>
					{props.label}
				</label>
				<Show when={props.description}>
					<p class={text({ role: "meta" })}>{props.description}</p>
				</Show>
				{body()}
				<Show when={error()}>
					<p role="alert" class={cn(text({ role: "meta" }), "text-danger")}>
						{error()}
					</p>
				</Show>
			</div>
		</FieldContext.Provider>
	);
}

// plugins/native-ui/src/ui/components/form-field/index.tsx
import type { FieldBinding, FieldControl } from "@fcalell/ui-core/descriptors";
import { text, textStrong } from "@fcalell/ui-core/variants";
import type { ReactNode } from "react";
import { Text as RNText, View } from "react-native";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { FieldError, FieldNameContext } from "../../lib/field";

interface FormFieldBase extends Closed {
	label: string;
	description?: string;
}

// Unbound, the consumer gives the error and the control; bound, the form
// gives both, and the control is a function of the field's value.
export type FormFieldProps<V = unknown> = FormFieldBase &
	(
		| {
				field?: never;
				error?: string;
				children?: ReactNode;
		  }
		| {
				field: FieldBinding<V>;
				error?: never;
				children: (control: FieldControl<V>) => ReactNode;
		  }
	);

// A typing control with its label, its description and its error, stacked;
// the label names the control. Bound to a form field, it draws the field's
// error and hands the control its value and change handler, and an
// autosaving binding's commit: `{(control) => <Input {...control} />}`.
export function FormField<V>(props: FormFieldProps<V>) {
	const { label, description } = props;
	const error = props.field ? props.field.error : props.error;
	const body = props.field
		? props.children({
				value: props.field.value,
				onChange: props.field.onChange,
				onCommit: props.field.onCommit,
			})
		: props.children;
	return (
		<View className="gap-pair">
			<RNText
				className={cn(text({ role: "body" }), textStrong({ role: "body" }))}
			>
				{label}
			</RNText>
			<FieldNameContext.Provider value={label}>
				<FieldError.Provider value={Boolean(error)}>{body}</FieldError.Provider>
			</FieldNameContext.Provider>
			{description ? (
				<RNText className={text({ role: "meta" })}>{description}</RNText>
			) : null}
			{error ? (
				<RNText
					accessibilityLiveRegion="polite"
					className={cn(text({ role: "meta" }), "text-danger")}
				>
					{error}
				</RNText>
			) : null}
		</View>
	);
}
