// plugins/solid-ui/src/ui/components/qr-code/index.tsx
import qrcode from "qrcode-generator";
import { createMemo, For, Show } from "solid-js";
import type { Closed } from "#lib/closed";
import { LoadingRows } from "#lib/loading";

// A square code in ink on the surface; a meta line is the consumer's, beneath.
export type QrCodeProps = Closed & {
	value: string;
	loading?: boolean;
};

const QUIET = 2;

export function QrCode(props: QrCodeProps) {
	const modules = createMemo(() => {
		const code = qrcode(0, "M");
		code.addData(props.value);
		code.make();
		const count = code.getModuleCount();
		const cells: Array<[number, number]> = [];
		for (let y = 0; y < count; y++) {
			for (let x = 0; x < count; x++) {
				if (code.isDark(y, x)) cells.push([x, y]);
			}
		}
		return { count, cells };
	});
	const size = () => modules().count + QUIET * 2;
	return (
		<Show when={!props.loading} fallback={<LoadingRows />}>
			<svg
				viewBox={`0 0 ${size()} ${size()}`}
				role="img"
				aria-label={props.value}
				shape-rendering="crispEdges"
				class="aspect-square w-full max-w-64 fill-ink"
			>
				<For each={modules().cells}>
					{([x, y]) => (
						<rect x={x + QUIET} y={y + QUIET} width="1" height="1" />
					)}
				</For>
			</svg>
		</Show>
	);
}

// plugins/native-ui/src/ui/components/qr-code/index.tsx
import qrcode from "qrcode-generator";
import { useState } from "react";
import { View } from "react-native";
import Svg, { Rect } from "react-native-svg";
import type { Closed } from "../../lib/closed";
import { LoadingRows } from "../../lib/loading";
import { useTokenColor } from "../../lib/theme";

export interface QrCodeProps extends Closed {
	value: string;
	loading?: boolean;
}

// A square code on the surface; a meta line may sit beneath it.
export function QrCode({ value, loading }: QrCodeProps) {
	const [size, setSize] = useState(0);
	const ink = useTokenColor("--color-ink");
	const surface = useTokenColor("--color-surface");
	if (loading) return <LoadingRows />;
	const code = qrcode(0, "M");
	code.addData(value);
	code.make();
	const modules = code.getModuleCount();
	const cell = size / (modules + 2);
	const cells: Array<[number, number]> = [];
	for (let r = 0; r < modules; r++) {
		for (let c = 0; c < modules; c++) if (code.isDark(r, c)) cells.push([r, c]);
	}
	return (
		<View
			accessibilityLabel={value}
			onLayout={(event) => setSize(event.nativeEvent.layout.width)}
			className="aspect-square w-full self-center overflow-hidden rounded-group"
		>
			<Svg width={size} height={size}>
				<Rect x={0} y={0} width={size} height={size} fill={surface} />
				{cells.map(([r, c]) => (
					<Rect
						key={`${r}:${c}`}
						x={(c + 1) * cell}
						y={(r + 1) * cell}
						width={cell}
						height={cell}
						fill={ink}
					/>
				))}
			</Svg>
		</View>
	);
}
