// plugins/native-ui/src/ui/components/picker/index.tsx
import type { Option } from "@fcalell/ui-core/descriptors";
import { GROUP, row, text } from "@fcalell/ui-core/variants";
import { Check, ChevronDown } from "lucide-react-native";
import { useState } from "react";
import { Pressable, Text as RNText, View } from "react-native";
import type { Closed } from "../../lib/closed";
import { cn } from "../../lib/cn";
import { Glyph } from "../../lib/glyph";
import { Input } from "../input";
import { List } from "../list";
import { Sheet } from "../sheet";

export interface PickerProps extends Closed {
	label: string;
	options: readonly Option[];
	value?: string;
	onChange: (value: string) => void;
}

// Up to this many options the sheet is a plain list; above it, a search field
// sits on top.
const SEARCHABLE_ABOVE = 6;

// A control showing its value; a tap opens one-line rows with a tick. A pick,
// never a form.
export function Picker({ label, options, value, onChange }: PickerProps) {
	const [open, setOpen] = useState(false);
	const [query, setQuery] = useState("");
	const current = options.find((option) => option.value === value);
	const searchable = options.length > SEARCHABLE_ABOVE;
	const shown = searchable
		? options.filter((option) =>
				option.label.toLowerCase().includes(query.trim().toLowerCase()),
			)
		: options;
	return (
		<>
			<Pressable
				accessibilityRole="button"
				accessibilityLabel={label}
				accessibilityValue={{ text: current?.label }}
				onPress={() => setOpen(true)}
				className={cn(
					GROUP,
					"min-h-11 flex-row items-center gap-row px-4 active:bg-edge",
				)}
			>
				<RNText className={cn(text({ role: "body" }), "flex-1")}>
					{current?.label ?? label}
				</RNText>
				<Glyph icon={ChevronDown} tone="ink-meta" size={16} />
			</Pressable>
			<Sheet open={open} onClose={() => setOpen(false)} title={label}>
				{searchable ? (
					<Input kind="search" value={query} onChange={setQuery} />
				) : null}
				<List>
					{shown.map((option) => {
						const selected = option.value === value;
						return (
							<Pressable
								key={option.value}
								accessibilityRole="radio"
								accessibilityState={{ selected }}
								onPress={() => {
									onChange(option.value);
									setOpen(false);
								}}
								className={cn(
									row({ state: "rest" }),
									"flex-row items-center active:bg-edge",
								)}
							>
								<View className="min-w-0 flex-1 gap-pair">
									<RNText numberOfLines={1} className={text({ role: "body" })}>
										{option.label}
									</RNText>
									{option.description ? (
										<RNText
											numberOfLines={1}
											className={text({ role: "meta" })}
										>
											{option.description}
										</RNText>
									) : null}
								</View>
								{selected ? <Glyph icon={Check} tone="tint" /> : null}
							</Pressable>
						);
					})}
				</List>
			</Sheet>
		</>
	);
}

// plugins/solid-ui/src/ui/components/picker/index.tsx
import type { Option } from "@fcalell/ui-core/descriptors";
import { GROUP, row, text } from "@fcalell/ui-core/variants";
import * as PopoverPrimitive from "@kobalte/core/popover";
import { Check, ChevronDown } from "lucide-solid";
import { createMemo, createSignal, For, Show } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { useWords } from "#lib/words.tsx";
import { Input } from "../input/index.tsx";
import { Sheet } from "../sheet/index.tsx";

// A control showing its value; a tap opens one-line rows with a tick,
// anchored, up to six options, and a searchable sheet above six. A pick,
// never a form.
export type PickerProps = Closed & {
	label: string;
	options: Option[];
	value: string;
	onChange: (value: string) => void;
};

const ANCHORED_MAX = 6;

const ROW =
	"flex w-full cursor-pointer items-center text-left transition-colors duration-(--duration-fast) ease-ui hover:bg-edge focus-visible:outline-2 focus-visible:-outline-offset-2 focus-visible:outline-tint";

function Rows(props: {
	options: Option[];
	value: string;
	onPick: (value: string) => void;
}) {
	return (
		<ul class="flex flex-col">
			<For each={props.options}>
				{(option) => (
					<li>
						<button
							type="button"
							role="option"
							aria-selected={option.value === props.value}
							onClick={() => props.onPick(option.value)}
							class={cn(row({ state: "rest" }), ROW)}
						>
							<span class={cn(text({ role: "body" }), "flex-1 truncate")}>
								{option.label}
							</span>
							<Show when={option.value === props.value}>
								<Check class="size-5 shrink-0 text-tint" aria-hidden="true" />
							</Show>
						</button>
					</li>
				)}
			</For>
		</ul>
	);
}

export function Picker(props: PickerProps) {
	const words = useWords();
	const [open, setOpen] = createSignal(false);
	const [query, setQuery] = createSignal("");
	const current = () =>
		props.options.find((option) => option.value === props.value);
	const searchable = () => props.options.length > ANCHORED_MAX;
	const filtered = createMemo(() => {
		const needle = query().trim().toLowerCase();
		if (!needle) return props.options;
		return props.options.filter((option) =>
			option.label.toLowerCase().includes(needle),
		);
	});
	const pick = (value: string) => {
		props.onChange(value);
		setOpen(false);
		setQuery("");
	};
	const control = (
		<button
			type="button"
			aria-label={props.label}
			aria-haspopup="listbox"
			aria-expanded={open()}
			onClick={() => setOpen(true)}
			class={cn(
				GROUP,
				text({ role: "body" }),
				"inline-flex min-h-11 cursor-pointer items-center gap-row rounded-full px-4 transition-colors duration-(--duration-fast) ease-ui hover:bg-edge focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tint",
			)}
		>
			<span class="truncate">{current()?.label ?? props.label}</span>
			<ChevronDown class="size-4 shrink-0 text-ink-meta" aria-hidden="true" />
		</button>
	);
	return (
		<Show
			when={searchable()}
			fallback={
				<PopoverPrimitive.Root
					open={open()}
					onOpenChange={setOpen}
					placement="bottom-start"
				>
					<PopoverPrimitive.Anchor>{control}</PopoverPrimitive.Anchor>
					<PopoverPrimitive.Portal>
						<PopoverPrimitive.Content
							class={cn(
								GROUP,
								"z-50 min-w-48 overflow-hidden bg-surface shadow-float outline-none animate-content-hide data-[expanded]:animate-content-show",
							)}
						>
							<Rows options={props.options} value={props.value} onPick={pick} />
						</PopoverPrimitive.Content>
					</PopoverPrimitive.Portal>
				</PopoverPrimitive.Root>
			}
		>
			{control}
			<Sheet open={open()} onClose={() => setOpen(false)} title={props.label}>
				<Input
					kind="search"
					value={query()}
					onChange={setQuery}
					placeholder={words.search}
				/>
				<Rows options={filtered()} value={props.value} onPick={pick} />
			</Sheet>
		</Show>
	);
}
