// plugins/solid-ui/src/ui/components/code/index.tsx
import { CODE, text } from "@fcalell/ui-core/variants";
import { createMemo, createSignal, Show } from "solid-js";
import type { Closed } from "#lib/closed.ts";
import { cn } from "#lib/cn.ts";
import { RING, TEXT_ACT } from "#lib/interact.ts";
import { LoadingRows } from "#lib/loading.tsx";
import { useWords } from "#lib/words.tsx";

// Mono, scrolling sideways, never wrapping. `title` heads the block with what
// the text is (a file's name, the tool it goes into); `tail` is the number of
// last lines shown before a tap unfolds the rest; `copy` draws the copy act
// beside the text, never over it: in the title's row when there is one,
// else centred on one line and at the top of more.
export type CodeProps = Closed & {
	text: string;
	title?: string;
	tail?: number;
	copy?: boolean;
	loading?: boolean;
};

const COPIED_MS = 2000;

export function Code(props: CodeProps) {
	const words = useWords();
	const [unfolded, setUnfolded] = createSignal(false);
	const [copied, setCopied] = createSignal(false);
	const lines = createMemo(() => props.text.split("\n"));
	const folded = () =>
		props.tail !== undefined && !unfolded() && lines().length > props.tail;
	const shown = () =>
		folded() ? lines().slice(lines().length - (props.tail ?? 0)) : lines();
	const hidden = () => lines().length - shown().length;
	const copy = async () => {
		await navigator.clipboard.writeText(props.text);
		setCopied(true);
		setTimeout(() => setCopied(false), COPIED_MS);
	};
	const copyAct = () => (
		<button
			type="button"
			onClick={() => void copy()}
			class={cn(
				text({ role: "meta" }),
				"-my-stack -mr-row min-h-floor shrink-0 px-row",
				TEXT_ACT,
			)}
		>
			{copied() ? words.copied : words.copy}
		</button>
	);
	return (
		<Show when={!props.loading} fallback={<LoadingRows />}>
			<figure class={cn(CODE, "flex flex-col gap-row")}>
				<Show when={props.title}>
					{(title) => (
						<figcaption class="flex min-h-6 items-center gap-row">
							<span
								class={cn(text({ role: "meta" }), "min-w-0 flex-1 truncate")}
							>
								{title()}
							</span>
							<Show when={props.copy}>{copyAct()}</Show>
						</figcaption>
					)}
				</Show>
				<Show when={folded()}>
					<button
						type="button"
						onClick={() => setUnfolded(true)}
						class={cn(text({ role: "meta" }), "self-start", TEXT_ACT)}
					>
						… {hidden()}
					</button>
				</Show>
				<div
					class={cn(
						"flex gap-row",
						shown().length === 1 ? "items-center" : "items-start",
					)}
				>
					{/* Scrolling sideways, it takes focus so a keyboard can scroll it. */}
					<pre
						tabindex="0"
						class={cn(
							text({ role: "mono" }),
							"min-w-0 flex-1 overflow-x-auto whitespace-pre",
							RING,
						)}
					>
						{shown().join("\n")}
					</pre>
					<Show when={props.copy && !props.title}>{copyAct()}</Show>
				</div>
			</figure>
		</Show>
	);
}

// plugins/react-ui/src/ui/components/code/index.tsx
import { Button as BaseButton } from "@base-ui/react/button";
import { cn } from "@fcalell/ui-core/cn";
import { counted } from "@fcalell/ui-core/tokens";
import {
	CODE_ACT,
	CODE_FOLD,
	CODE_HEAD,
	CODE_UNDER_HEAD,
	CONTENT_FRAME,
	codeText,
	lineBox,
	skeleton,
	text,
} from "@fcalell/ui-core/variants";
import { useId, useRef, useState } from "react";
import type { Closed } from "../../lib/closed.ts";
import { useCopy } from "../../lib/copy.ts";
import { InsetRing } from "../../lib/ring.ts";
import { useWords } from "../../lib/words.tsx";
import { Icon } from "../icon/index.tsx";
import { IconButton } from "../icon-button/index.tsx";

const FRAME = "flex flex-col min-w-0 overflow-hidden";
const HEAD = "flex items-center";
const TITLE = "grow min-w-0 truncate";
const BODY = "flex min-w-0";
// The text scrolls sideways and never wraps; focusable so a keyboard scrolls
// it, its ring inward inside the frame's clip.
const TEXT =
	"overflow-x-auto whitespace-pre focus-visible:outline-2 focus-visible:-outline-offset-2 focus-visible:outline-ring";
const TEXT_BESIDE = "grow min-w-0";
const ACT = "shrink-0";
const LINE = "flex items-center h-lh";
const FOLD =
	"flex items-center w-full hover:bg-wash-hover active:bg-wash-press focus-visible:outline-2 focus-visible:-outline-offset-2 focus-visible:outline-ring";
const WAIT = "flex flex-col";
const FOLD_WAIT = "flex items-center w-full";
// The loading lines, each at the length of the line it stands in for, in
// turn; the fold's word at a third.
const BARS = ["w-2/3", "w-1/2", "w-3/4"] as const;
const FOLD_BAR = "w-1/3";
const BAR = "w-full";

/** Text a machine reads, in mono, whole. */
export interface CodeProps extends Closed {
	/** The text, its lines split on newlines. */
	text: string;
	/** What the text is (a file's name, the tool it goes into), in a head over it; it names the text. */
	title?: string;
	/** Shows only the last lines, this many, behind an act that reveals the earlier ones. */
	tail?: number;
	/** Adds the copy act: in the head with a title, else in its own column beside the first line. */
	copy?: boolean;
	/** The text waits: line boxes stand in for it under the head, `tail` of them under the fold's when it folds. */
	loading?: boolean;
}

// The copy act: a check and the word Copied for two seconds once copied.
function CopyAct(props: { name: string; text: string }) {
	const words = useWords();
	const [done, copy] = useCopy();
	return (
		<InsetRing value>
			<IconButton
				icon={done ? "Check" : "Copy"}
				label={done ? words.copied : `${words.copy} ${props.name}`}
				onAct={() => copy(props.text)}
			/>
		</InsetRing>
	);
}

/** Mono at the code role in the frame Code, Diff and ProseDiff share; never wraps, the text scrolling sideways inside the frame. A head names it (`title`) and carries the copy act; without a title the act stands in its own column beside the first line. `tail` folds the earlier lines behind a one-way act that reveals them and leaves, the focus landing on the text. */
export function Code({ text: source, title, tail, copy, loading }: CodeProps) {
	const words = useWords();
	const id = useId();
	const textRef = useRef<HTMLPreElement>(null);
	const [unfolded, setUnfolded] = useState(false);
	const name = title ?? words.code;
	const head = title ? (
		<div className={cn(CODE_HEAD, HEAD)}>
			<span className={cn(text({ role: "meta" }), TITLE)}>{title}</span>
			{copy && !loading ? <CopyAct name={name} text={source} /> : null}
		</div>
	) : null;
	// A folding text waits as it lands: the fold's row over `tail` lines.
	const waiting =
		tail === undefined
			? BARS
			: Array.from({ length: tail }, (_, at) => BARS[at % BARS.length]);
	if (loading)
		return (
			<div aria-busy className={cn(CONTENT_FRAME, FRAME)}>
				{head}
				{tail === undefined ? null : (
					<div className={cn(CODE_FOLD, title && CODE_UNDER_HEAD, FOLD_WAIT)}>
						<span className={cn(lineBox({ role: "meta" }), LINE, FOLD_BAR)}>
							<span className={cn(skeleton({ kind: "line" }), BAR)} />
						</span>
					</div>
				)}
				<div
					className={cn(
						codeText({ act: "none" }),
						title && tail === undefined && CODE_UNDER_HEAD,
						WAIT,
					)}
				>
					{waiting.map((width, index) => (
						// biome-ignore lint/suspicious/noArrayIndexKey: the lines are fixed stand-ins
						<span key={index} className={cn(lineBox({ role: "code" }), LINE)}>
							<span className={cn(skeleton({ kind: "line" }), width)} />
						</span>
					))}
				</div>
			</div>
		);
	const lines = source.split("\n");
	const hidden =
		tail !== undefined && !unfolded ? Math.max(0, lines.length - tail) : 0;
	const shown = hidden > 0 ? lines.slice(hidden) : lines;
	const beside = copy === true && !title;
	const fold =
		hidden > 0 ? (
			<BaseButton
				aria-expanded={false}
				aria-controls={id}
				onClick={() => {
					// The act leaves with the lines it folded: the focus moves to the
					// text, mounted already, before the act goes.
					textRef.current?.focus();
					setUnfolded(true);
				}}
				className={cn(CODE_FOLD, title && CODE_UNDER_HEAD, FOLD)}
			>
				<Icon name="ChevronUp" fit="meta" />
				<span className={text({ role: "meta" })}>
					{counted(words.earlierLines, hidden)}
				</span>
			</BaseButton>
		) : null;
	const body = (
		// biome-ignore lint/a11y/useSemanticElements: a named text, not a form's fieldset; a group adds no landmark per block
		<pre
			ref={textRef}
			id={id}
			// biome-ignore lint/a11y/noNoninteractiveTabindex: a keyboard scrolls the text sideways
			tabIndex={0}
			role="group"
			aria-label={name}
			className={cn(
				text({ role: "code" }),
				codeText({ act: beside ? "beside" : "none" }),
				title && !fold && CODE_UNDER_HEAD,
				TEXT,
				beside && TEXT_BESIDE,
			)}
		>
			<code>{shown.join("\n")}</code>
		</pre>
	);
	return (
		<div className={cn(CONTENT_FRAME, FRAME)}>
			{head}
			{fold}
			{beside ? (
				<div className={BODY}>
					{body}
					<span className={cn(CODE_ACT, ACT)}>
						<span className={cn(lineBox({ role: "code" }), LINE)}>
							<CopyAct name={name} text={source} />
						</span>
					</span>
				</div>
			) : (
				body
			)}
		</div>
	);
}
